### ISSUE TITLE
구글 드라이브에서의 한글 입력 문제.

### ISSUE THREAD

**Issue by homuramagica** [gureum/gureum#102]
구글 드라이브 문서(예전 구글 문서도구 워드)에서
숫자 1234567890을 입력하면
뒤의 문자가 앞에 입력한 부분을 먹어버리면서
2244668800 이렇게 되어버립니다..;; 이것 뿐만이 아니라 연속되는 숫자를 입력하면 전부 이런 종류의 입력 오류가 발생하지요.

예전엔 스프레드시트에서도 좀 심각한 문제가 있었던 것 같습니다만 구름도, 스프레드시트도 업데이트 된 덕분인지 이 쪽에서의 문제는 발견되지 않는군요.

**Comment by soomtong** [comment]
#195
