### ISSUE TITLE
세벌식 한자입력모드(옵션+엔터)​ 에서 '표' 자 입력이 되지 않음.

### ISSUE THREAD

**Issue by rkJun** [gureum/gureum#105]
한자입력모드 (옵션+엔터) 상태에서,  '표' 자를 입력하면, 초성 'ㅍ' 을 입력할 때에는 기호목록이 나오고,
'ㅛ' 중성을 입력해서 '표' 글자가 완성될 때에는 'Ｄ' 라고 글자가 변경되어 버립니다.

세벌식최종, 세벌식390, 세벌식최종 (종성결합허용) 에서 동일한 오류가 발생되고 있는 것을 확인했습니다.

**Comment by youknowone** [comment]
macOS의 버그였고 근래의 macOS에서는 해결된 문제입니다
