### ISSUE TITLE
Shift + Space 로 한영 전환시에 미리보기(훑어보기)가 실행이 됩니다.

### ISSUE THREAD

**Issue by toorn** [gureum/gureum#123]
1.8.4 로 업데이트후 Shift + Space 로 한영 전환을 하면 OSX 의 기본기능중에 있는 space 를 눌러서 실행하는 미리보기(훑어보기)가 실행이 됩니다. 이전에는 이런 증상이 없었습니다.

환경설정에서 '자판 전환 시 스페이스 입력 방지' 를 체크해 보아도 증상은 같습니다.

그리고 환경설정 창이 닫히지 않습니다. 창 좌측상단의 'x' 을 눌러도 반응이 없고, '취소' 버튼을 눌러라 닫힙니다.

**Comment by soomtong** [comment]
최근 버전(1.8.9 이상) 확인 결과 이상 없음을 확인했습니다.

**Comment by youknowone** [comment]
환경 설정 창이 닫기지 않는 문제는 발생하지 않는 것 같습니다.
shift space시 Finder에서 미리보기가 보이는 것은 (그것도 심지어 느리게..) 여전히 발생하는것으로 보입니다.
이유는 OS X가 입력기에 무관하게 키 입력을 가로채기 때문으로 보이는데. 구름의 자판 전환은 시스템을 거치지 않고 자체전환하는 식이라 쉬운 해결방법을 찾기는 어려워 보입니다.
