### ISSUE TITLE
두벌식에서 모음만 쓰다 자음을 쓰면 초성으로 달라붙는 문제

### ISSUE THREAD

**Issue by swcheon** [gureum/gureum#124]
예: 'ㅜㅜㅜㅜ' 를 쓰다가 '흥'을 쓰면
'ㅜㅜㅜ후으' 이렇게 됩니다.

버그 맞나요?

**Comment by youknowone** [comment]
#388

**Comment by youknowone** [comment]
다음 버전부터 이 동작은 기본으로 꺼져 있어 입력한 순서대로 입력되게 됩니다. 테스트버전은 다음 링크에서 받아보실 수 있습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1
