### ISSUE TITLE
PhpStorm에서 구름 입력기 사용 시 문제점

### ISSUE THREAD

**Issue by kimhongsu** [gureum/gureum#128]
PhpStorm version 8.0.1
구름입력기 1.8.6

안녕하세요? 전 스페인어를 쓸 일이 있어서, 키보드 입력기를 구름입력기 쿼티와 구름입력기 세벌식390(종성결합허용), 스페인어를 등록 하였습니다. 

PhpStorm을 사용하면 (JetBrains의 제품들에는 동일하게 나타날 것 같습니다.)
;에 해당하는 부분을 구름입력기 쿼티에서 타이핑 하면, ñ가 나타납니다. 
또 구름입력기 세벌식 390(종성결합허용)에서 shift와 ;를 누르면 Ñ가 나타납니다. 
Ñ와 ñ는 모두 ;의 자판 위치에 해당하는 스페인어 자판 글자입니다. 

이와 비슷한 문제를 이전에도 리포트 하였고, 구름입력기 1.8.4에서 해결되어 메일을 받았습니다. 

구름입력기에 항상 감사드립니다.

**Comment by youknowone** [comment]
최신버전(1.9.0)에서 다시 발생하게 될 예정입니다.
