### ISSUE TITLE
JIS키보드인데 특수문자가 키보드에 인쇄된 상태가 아닌 쿼티식으로 입력이 됩니다.

### ISSUE THREAD

**Issue by kaitoex** [gureum/gureum#130]
안녕하세요.
백투더맥 블로그에서 알게되어서 잘 쓰고 있습니다. 

저는 일본에 있기 때문에 일본 표준인 JIS키보드가 설치된 맥을 쓰고 있습니다.

요세미티 출시 후 며칠간 맥을 쓰지 않다가 업데이트를 하게 되었는데 키보드에 인쇄된 특수문자가 아닌 다른 특수문자가 입력되어 깜짝 놀랐습니다.

JIS키보드는 쿼티 키보드와는 다르게 특수문자가 위치하고 있습니다. 예를 들면,

@ 이 숫자 2가 아닌 리턴 키 근처에 있다든지,
&가 숫자 6에 위치해 있다든지... 

등입니다.
어차피 쿼티에 익숙한 마당이라 JIS식이 더 불편한 게 사실이지만 일본어 입력 상태도 있어서 헷갈리게 되었습니다.
고쳐주시면 감사하겠습니다.

**Comment by youknowone** [comment]
#526 을 활용해 해결할 방법이 있는지 검토해 볼수 있겠습니다

**Comment by youknowone** [comment]
새 버전에 시스템 자판 설정할수 있는 기능이 들어갔는데, JIS키보드에서 쓰는 값으로 넣으면 될것 같습니다. 확인해보지 않아 수정되었나 확인하는데 어려움이 있으니 혹시 문제가 재현되면 다시 열어 주세요.

https://github.com/gureum/gureum/releases/tag/1.11.1
