### ISSUE TITLE
신세벌식-2012

### ISSUE THREAD

**Issue by irongaea** [gureum/gureum#132]
안녕하세요. 
구름입력기를 무척 좋아하는 열혈 이용자 입니다. 저는 세벌식 사용자입니다.
개발자님의 수고로 mac에서도 편하게 세벌식-2012을 사용하고 있습니다.
욕심이 있다면 구름입력기에서도 [신세벌식-2012]를 지원해 주셨으면 합니다.
키 배열이 기존의 [세벌식-2012]와는 비교도 할 수 없을 만큼 단순하고 편해졌는데, 윈도우즈에서는 [날개셋 입력기]를 통하여 사용할 수 있는데... mac에서도 쓸 수 있으면 좋겠습니다.
다음 버전에는 추가를 해 주실 수 있을지, 개발자님께 조심스럽게 부탁드려 봅니다.
미리 감사합니다.

**Comment by Sinseiki** [comment]
숨통 님께서 http://cafe.daum.net/3bulsik/623N/250 에 신세벌식이 포함된 구름 입력기를 올려주셨습니다.
