### ISSUE TITLE
About 창이 다른 창 위로 뜨지 않습니다

### ISSUE THREAD

**Issue by mollax** [gureum/gureum#135]
1.8.7 이 나왔길래 설치해 보았습니다.
1. about 창이 이상하게 맨 위로 뜨지 않아 보기가 힘듭니다.
2. about 창에 나온 버젼이 1.8.7 이 아닌, 1.8.6-5-g9390d1a 로 나옵니다. (pkg 가 아닌, tar.gz 으로 설치했습니다.)
3. 버젼 문제인지, 아니면 아직 업데이트가 안 되어서인지 최신 버젼이 아니니 1.8.6 을 설치하라고 나옵니다.

다들 사소한 문제이긴 합니다만... : )

**Comment by youknowone** [comment]
macOS 에서 about 창 지원이 사라진 것으로 보입니다. 구름에서도 기능을 제거하려고 합니다.

**Comment by youknowone** [comment]
#360
