### ISSUE TITLE
요세미티에서 한자입력이 불가능한 문제

### ISSUE THREAD

**Issue by YunjungLee** [gureum/gureum#138]
요세미티에서 alt+enter로 한자 입력이 안 됩니다.
1.8.7 설치했더니 최신버전이 1.8.6이라네요... ??????
![2014-11-03 1 09 40](https://cloud.githubusercontent.com/assets/5165728/4875858/c7cb40c0-62aa-11e4-9785-bddb452d01c4.png)

**Comment by youknowone** [comment]
한자 입력에 여러 문제가 남아 있지만 크래시 문제는 해결된것으로 보여 닫습니다. 나머지 문제는 #213 에서 추적합니다.
