### ISSUE TITLE
Option 키 조합 문제

### ISSUE THREAD

**Issue by jaeyeun97** [gureum/gureum#140]
US 자판에서 스페인어를 입력할때, Option 키와 N키를 같이 누르면 ˜이 입력되고 그다음 n을 입력해서 글자를 완성합니다. 1.8.0 버전에서까지는 잘 쓰고 있었는데 1.8.7에서는 입력이 되지 않네요.
이 옵션을 다시 넣어주셨으면 합니다.

**Comment by youknowone** [comment]
새 버전에서 영어 자판을 '로마자'로 선택하면 수정됩니다

https://github.com/gureum/gureum/releases/tag/1.11.1
