### ISSUE TITLE
Safari에서 Google Drive 입력 문제

### ISSUE THREAD

**Issue by jaeyeun97** [gureum/gureum#141]
Google Drive에서 문서작성을 하려고 하면 스페이스 후 첫 키가 없어지는 현상이 발견됩니다. 한글, 영어 모두 그러며, Safari에서만 이 문제가 생기는 것 같습니다.

**Comment by lanterrt** [comment]
1.8.9c에서 스페이스 뿐만 아니라 DELETE키 이후에도 동일한 문제가 있습니다

**Comment by soomtong** [comment]
#195
