### ISSUE TITLE
사파리에서 한글 입력이 되지 않는 문제

### ISSUE THREAD

**Issue by toorn** [gureum/gureum#15]
사파리에서 페이스북을 접속해서 글을 쓰려고 하면 한글 입력이 되지 않습니다. 
첫글자를 쓰고 다음 글자를 쓰면 다음 글자가 첫 글자를 먹어들어갑니다.
영문에서는 전혀 문제가 없습니다.

사파리와 크롬에서 시도해 보았는데, 크롬에서는 문제가 없고, 사파리에서만 그런 문제가 나타납니다.

**Comment by soomtong** [comment]
너무 오래된 이슈라 그리고 지금은 재현이 불가능해 닫아 둡니다.
현재 페이스북에서 비슷한 류의 환경에서 한글 입력을 진행했을 경우 문제가 발생하지 않고 있습니다.
같은 문제가 다시 발생했을 경우 알려주세요.
