### ISSUE TITLE
종성 퀵 시프트와 관련하여 제작자 님께 죄송합니다.

### ISSUE THREAD

**Issue by Sinseiki** [gureum/gureum#156]
이번에 드린 세벌식 모아치기 2014 수정 libhangul 풀 리퀘스트에는 종성 시프트 개념이 들어 있습니다.
그런데 제가 이 종성 시프트를 적용하고 발표하면서, 먼저 세벌식 최종 순아래 자판에서
종성 퀵 시프트를 개발하여 쓰셨던 제작자 님을 언급하지 않았습니다...

지금 와서 생각해보니, 이로 인해서 마치 종성 시프트를 제가 먼저 개발한 것처럼 되어 버렸고,
이는 제작자 님께서 먼저 개발하신 공을 제가 가로챈 것이 된 것 같아서,
3벌식 카페 http://cafe.daum.net/3bulsik/6CY8/319 에도 글을 올리고,
여기에도 이렇게 글을 드리게 되었습니다.

이에 대해 Youknowone 님께 정말 죄송합니다.

신세기 드림

**Comment by Sinseiki** [comment]
Youknowone 님, 최종 순아래의 아이디어가 전체적으로 좋지만 특히 모음 조합 부분은 정말 획기적이라고 생각합니다. 최종 순아래 자판의 날개셋 파일을 세벌식 카페 같은 곳에 공개해 주시면 보다 많은 사람들이 함께 연구할 수 있으리라고 생각합니다. 좋은 자판 배열을 소개해 주셔서 감사합니다. 새해 복 많이 받으세요!

**Comment by youknowone** [comment]
@lhuntr 어떤식으로 운지하냐에 따라 다르겠지만 종성 시프트의 위치가 9인건 두 가지 부적합 요인이 있어 보입니다.
첫째로는 자주 쓰이는 자음일수록 좌측으로 몰려있는 경향이 있는데, 중지 혹은 약지 운지만 가능한 9위치에 종성 시프트가 들어가면 초성과 함께 누르기가 어려워집니다. 예를 들어 '많'자를 입력할 경우 i를 중지로 누를 경우 9는 중지로 연타하거나 i를 중지에, 9를 약지에 두고 동시에 눌러야 하는데 둘 모두 쉽지 않은 방법입니다.
둘째로는 4단이 결코 다른 단과 함께 누르기 쉬운 단이 아니라는 점입니다. 가급적이면 2단에, 멀어도 3단에는 배치가 되어야 다른 글쇠와 함께 누르기가 용이합니다. (그런 관점에서 2단을 쓰는 2014는 정말 최적의 위치에 종성 시프트를 배치하고 있는 셈이죠.)

제가 [ 위치를 고집하는건 아무래도 그 위치 자체보다는 최종 배열을 지키면서도 한 낱자에서 같은 손가락을 두번 쓰지 않도록 배열을 조정하기 때문인듯 합니다. 그 조건을 다 만족시키고 2단에 가장 가깝고 소지로 누르기 편하면서 다른 자음을 새끼손가락으로 누를 때 약지를 쓸 수 있는 위치가 당장은 거기밖에 없네요. 만약 최종 배열을 일부 포기하고 초성 위치를 조금 조정하자면 '과 [의 역할을 교환해 [에서 ㅌ을 입력하고 '을 종성시프트로 쓰면 훨씬 편하지 않을까 하는 생각이 드는데, ㅌ이 얼마나 비중 높은 글자인지 몰라 정말 좋은 방법인지는 모르겠습니다. 빈도 데이터도 궁금하고 사용하시는 신세벌 배열에서 '위치엔 어떤 글쇠가 배당되어 있는지도 궁금합니다.

()와 []의 배치는 말씀을 듣고 보니 정말 그렇네요. 세벌식에서 ()가 내려와 있어서 편했었는데, 마찬가지로 로마자 자판에서도 내려 쓰는 편이 좋은 것 같습니다.

@Sinseiki 날개셋에서 쓰던 설정 파일을 찾아냈습니다. 안 쓴지 오래 된 터라 최신 버전에서 사용이 가능한지 보고 올려보도록 하겠습니다.

두분 모두 새해 복 많이 받으세요.

**Comment by youknowone** [comment]
배열 이야기를 길게 하게 되었는데, 지금 보니 제목이 조금 부담스러운것 같습니다. 죄송할 만한 일을 하신게 아니시니 자판 이야기가 길어질 것 같으면 제목을 조금 바꾸어 보면 어떨까요?

**Comment by lhuntr** [comment]
youknowone 님, 신세기 님, 새해 복 많이 받으십시오. 본문을 적기 전에, 저도 신세기 님께서 필요 이상으로 예의를 차리신 것 같아 보입니다. 세사모 다른 글들에서도 종종 그러셨거든요. 

![default](https://cloud.githubusercontent.com/assets/10352632/5593580/fc608d9c-925a-11e4-9b2a-391db93f6079.png)
음절 당 자모 빈도표입니다. 즉 어떤 글자를 입력할 때 그 글자에 종성ㄴ 이 등장할 확률은 15.5%이고 받침이 없을 확률은 53.1%쯤 된다는 뜻입니다. 출처는 http://blog.joins.com/media/folderlistslide.asp?uid=malipres&folder=72&list_id=6754009 이고 이것을 편집해서 엑셀 파일로 만들었습니다만, 나중에 보니 세사모에서 같은 작업을 예전에 하신 분(라온누리님)이 계셨더군요.

[ 키를 종성 시프트로 쓰실 때에 밭, 탉 등의 글자를 입력할 때 소지 연타가 발생합니다. 말씀의 내용으로 추측컨대 밭을 입력하실 땐 ㅂ 를 약지, [ 를 소지로 입력하고, 탉을 입력하실 땐 ㅌ을 소지, [ 를 약지로 입력하시는 것 같습니다. 사실 이 문제는 빈도가 높은 조합ㅗ 의 봐, 퇴 등에서 더 심각하게 발생하는데 짐작컨대 이들도 약지/소지 콤보로 입력하실 것 같군요.

자판 배열이 민감한 문제인 이유는, 여러 가지 요소가 혼재해 있는데 모두를 챙기기는 쉽지 않고, 사용자에 따라 더 심각하게 느끼는 불편함의 요소가 다르기 때문이 아닐까 합니다. 가령 youknowone님이 쓰시는 자판에서는 9 키를 누를 일이 크게 적어졌지만 대신 새끼손가락의 부담이 높아졌습니다. / 키의 누름 빈도가 기존의 3.4%에서 4.2% (조합모음 4.7% 에서 ㅟ 의 0.5%를 뺀 숫자) 로 증가했으니까요. 

 아무튼 넷째줄 사용을 피할 것인지, 혹은 소지의 부담을 줄일 것인지는 사실 선택의 문제입니다. 종성 시프트는 약 1.7% 발생하는데 이는 초성ㅌ 의 1.3%, 초성ㅍ 의 1.2% 보다 높습니다만 조합ㅗ 의 3.4% 보다는 낮은 수치입니다. 개인적인 취향으로는 9 의 위치가 / 의 위치보다 오히려 편하게 느껴질 정도입니다. 그런데 이는 사람마다 취향이 천차만별일 것으로 예상됩니다. 그러나 조합ㅗ/ㅜ(ㅟ 제외)와 종성 시프트를 모두 소지에 맡기면 아마 소지의 사용이 약지보다 많아질 것 같습니다. 이와 같이, 자판엔 생각할 요소가 많습니다.

자판의 위치는 2단-3단-1단-4단 순으로 가치가 높습니다. 조합ㅗ 는 1단, ㅍ 는 3단에 위치해 있는데 ㅗ 는 3.4% (youknowone 님의 경우 4.2%), ㅍ 는 1.2% 의 빈도로 등장합니다. 많은 세벌식 사용자들이 이중모음 정석을 지키지 않고 왼손 모음만으로 ㅘ, ㅚ 등을 조합하는 이유 중 하나가 / 위치의 불편함이라고 조심스레  짐작합니다. / 위치는 특히 다른 초성과 같이 치다 보면 (쾌, 뢰 등) 손톱으로 눌러야 할 때가 많거든요. ㅗ 와 ㅍ 의 위치를 뒤바꾸면 좀더 낫지 않을까 생각합니다만, 이것은 파격적인 주장입니다.

끝으로 덧붙이면, 저는 신세벌식을 쓰지 않습니다. 몇 가지 아이디어만 제 자판에 차용했을 따름입니다. 신세벌식은 여러 가지 장점에도 불구하고, 모아치기/오타 수정 이 불가능한 치명적 단점이 있습니다. 다만 4단을 사용하지 않으므로 운지 거리가 짧고, 따라서 종성 시프트를 도입한다면 동시치기 자판으로써의 가능성이 있습니다. 또한, 제 자판에서 초성ㅌ 의 위치는 기존 자판과 같은 ' 입니다. ㅌ 의 빈도는 1.3% 에 달하므로 그 자리를 종성 시프트에 쓰는 것은 바람직하다고 생각하지 않습니다. 다른 초성 글쇠를 침범하지 않아야 한다면 역시 [ 위치가 최적이라 생각합니다.

**Comment by youknowone** [comment]
좋은 자료 감사합니다. 앞으로는 참고해서 작업할 수 있도록 해야겠습니다.

지금 테스트를 해보니 밭은 그냥 소지 연타를 하고 있고 탉은 [를 약지로 입력하고 있습니다. 조합ㅗ는 말씀대로 약지/소지 콤보로 입력하고 있습니다.

ㅋ 같은 경우는 조합ㅗ와 쓰기가 쉽지 않아서 ㅋ-조합ㅜ를 약지/중지로 치고 있습니다. 이쪽은 전반적으로 모아치기 비중을 어떻게 두느냐가 중요하다고 생각됩니다. 아무래도 저는 모아치기 비중을 높게 치고 왼손 부담이 원래 크다고 생각해서 참고 쓰는 것 같긴 합니다. 실제로 종성 시프트 도입 후의 소감은 원배열로 시프트를 쓸 때 보다는 부담이 줄었지만 종성 연타를 쓸 때 보다는 부담이 늘었다는 것입니다. 1단과 3단을 자주 오가서 그런지 다른 손가락에 비해 피로가 좀 느껴지는 편입니다.

저는 종성시프트의 경우 어차피 시프트가 소지로 들어가는 키이니 소지로 넣는게 손해는 아니라고 생각했지만, 손가락 꼬임 없이 옮길 수 있으면 더 낫겠다는 생각은 듭니다.

9가 /보다 편하다는 이야기는 사실 처음 들어보는 이야긴데, 역시 자판이 그만큼 사용자 취향을 많이 타는 문제라는 생각이 듭니다. 정말 어려운 문제네요.

ㅍ/ㅗ 교환은 최종 배열을 포기하면 충분히 테스트해볼만한 배열 같습니다. ㅍ는 보통 소지로 입력하지만 사실은 약지도 쓸 수 있는 위치입니다. 말씀대로 ㅍ의 빈도가 훨씬 낮다면 입력된 초성에 따라 유연하게 손가락을 바꿔 쓸 수 있는 ㅍ 위치가 ㅗ에 훨씬 적합해 보입니다.

자판 설명 글을 준비중인데, 먼저 찾아낸 날개셋 파일 공유해 드리겠습니다.

https://github.com/youknowone/3finalnoshift/raw/master/%EC%84%B8%EB%B2%8C%EC%8B%9D%20%EC%B5%9C%EC%A2%85%20%EC%88%9C%EC%95%84%EB%9E%98%20%ED%98%B8%ED%99%98.ist

옛날에는 분명히 낱자 조합 규칙에 "역순 결합 허용" 같은게 있어서 한 방향만 넣었던 느낌인데 도저히 찾을수 없어 그 부분은 다 역순조합을 추가해 넣었더니 대충 고쳐진 것 같네요. 종성시프트 관련해서 버그가 좀 있습니다. 테이블을 수백줄 만들기가 힘들어 약식으로 구현했었습니다. 지금보니 날개셋에 추가된 기능이 많아 요즘은 쉽게 만들수 있을지도 모르겠다는 생각이 드는데 아직은 잘 모르겠습니다.

**Comment by youknowone** [comment]
날개셋으로 조합ㅜ를 없애는 방안을 테스트해보았는데 ㅋ가 들어가는 경우에 너무 불편합니다. 저는 제가 ㅜ 조합을 안쓴다고 생각하고 있었는데 저도 모르게 ㅋ에는 계속 쓰고 있었네요. 조합ㅜ가 줄여주는 스트레스를 생각하면 4단 약지 - 1단 소지 이동은 거의 불가능한 배치라고 생각됩니다.

**Comment by lhuntr** [comment]
쾌 입력 문제는 ㅗ 와 ㅍ 를 맞바꾸면 해결됩니다. 사실 쾰른이나 쾨니히스베르크와 같은 경우가 있어서 youknowone님의 경우에도 4단 약지-1단 소지가 나오는 경우가 완전히 없어지진 않지요. 저는 아예 ㅍ 나 ㅗ 나 ㅍ 와 ㅗ 의 기능을 둘 다 하도록 바꿔 볼까 생각하고 있습니다. 이 편이 그냥 ㅍ/ㅗ 를 서로 교환하는 것보다 자판 호환성에도 맞고요. 사실 9키를 종성 시프트로 쓰는 것은 기존 세벌식 사용자들이 쉽게 받아들이기 힘들 것이라 생각됩니다. 기존 세벌식과 되도록 같을수록 좋다는 건 사실이거든요.

**Comment by lhuntr** [comment]
모아치기 관련해서 생각하면, 오른손 조합은 두 가지로 생각할 수 있습니다.
1. 된소리식 조합
초성 ㄲ = ㄱ ㅇ = ㅇ ㄱ 으로 입력한다고 가정하면, 까 = ㄱ ㅇ ㅏ  = ㅇ ㄱ ㅏ  이 됩니다. 이 때 ㄱ 와 ㅇ 의 조합은 순서에 상관 없지만, 모음이 나오는 순간 오른손 조합은 중단됩니다. ㄱ ㅏ ㅇ 이나 ㅏ ㄱ ㅇ 은 가ㅇ 일 뿐이지 까 가 될 순 없거든요.
2. ㅗ/ㅜ 식 조합
와 = ㅇ ㅗ ㅏ 로 입력하는 것이 표준입니다. 이 때 허용되는 조합이 무엇인지에 따라 갈리는데,
ㅗ ㅇ ㅏ 를 허용하면 이는 ㅗ 를 초성처럼 취급하는 것이고 1번과 같아집니다.
반면, ㅇ ㅏ ㅗ 를 허용할 수도 있는데 1번과 비교하여 장단점이 있습니다.
장점은, 이어치기할 때 오타가 줄어듭니다. 타이핑 시 같은 손인 ㅇ 와 ㅗ 의 순서를 틀리는 경우는 잘 없지만 좌우 손의 순서를 틀리는 것은 몰아칠 때 왕왕 나오는 경우거든요.
단점은, 동시치기할 때 문제가 됩니다. '이왕' 을 입력하고자 할 때, ㅇ ㅣ ㅇ ㅗ ㅏ ㅇ 이 아닌 ㅇ ㅣ ㅗ ㅇ ㅏ ㅇ 으로 치게 되면 이왕이 아닌 외앙 으로 입력돼 버립니다. 

즉, 오른손 입력 순서가 명확한 사람일 경우 두번째 방법이 좋고, 오른손 조합에서 동시에 누르는 버릇이 있는 경우 첫번째 방법이 좋습니다. 동시에 누르는 것을 습관화 하면 까 = ㄱ ㅇ ㅏ 에서 ㄱ 와 ㅇ 사이나 그 앞에 ㅏ 가 올 확률이 줄어듭니다. 즉 둘 다 장단점이 있다고 할 수 있습니다.

1번 외에는 선택의 여지가 없는 된소리와는 달리, ㅗ/ㅜ 나 종성 시프트는 2번을 선택할 수도 있습니다.

**Comment by Sinseiki** [comment]
날개셋 파일을 보니 최종 순아래 자판의 조합과 특성이 한 눈에 들어옵니다. 아주 효율적으로 되어 있군요. 날개셋 파일을 올려주셔서 감사합니다 ^^

**Comment by youknowone** [comment]
글 정리를 마치고 까페에도 링크를 올려보았습니다 :)
