### ISSUE TITLE
기본 설정 하에서의 옛한글 오토마타 관련 문제

### ISSUE THREAD

**Issue by ParanScreen** [gureum/gureum#157]
두벌식 옛글 자판에서, 구름 입력기의 기본 설정인 "채움 문자 제거"가 선택된 경우 옛한글 낱자의 조합이 정상적으로 이루어지지 않습니다. 예를 들어 `ᄒᆞᆫ글`을 입력하면 `ᄒᆫ글`로, `낭즁ᄎᆔ물`을 입력하면 `낭중ᄎ`+(NULL문자)+`물`로 입력됩니다.

**Comment by youknowone** [comment]
최신 베타에서 채움문자 관련 설정을 제거하였고 옛한글 입력 버그도 수정되었습니다

https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre9

**Comment by youknowone** [comment]
1.10을 정식으로 릴리즈하였습니다. 문제가 지속되면 다시 알려주세요. https://github.com/gureum/gureum/releases/1.10.0
