### ISSUE TITLE
구름 build issue

### ISSUE THREAD

**Issue by isty2e** [gureum/gureum#158]
build instruction대로 따라했습니다만, 2SetHangul.keylayout 경로가 이상하게 잡혀 있는 것 같습니다.

Gureum.xcodeproj/project.pbxproj
195:		38EE97771A00061000AD19B8 /* 2SetHangul.keylayout */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = text.xml; name = 2SetHangul.keylayout; path = ../../../../../Users/youknowone/Downloads/2SetHangul.keylayout; sourceTree = "<group>"; };

저 경로에 파일이 있을 리 만무하니 XCode에서 빌드하다 에러가 뜨는 것 같습니다. 해당 파일은 어디서 구할 수 있나요?

**Comment by youknowone** [comment]
테스트하다 뺐다고 생각했는데 실수로 넣은 것 같습니다. 빌드할 파일에서 제외해야 하겠습니다

**Comment by youknowone** [comment]
수정해서 새로 올렸습니다. 오랫동안 클린빌드를 안해봤더니 이런 문제가 생겨 있었네요. 알려주셔서 감사합니다.
