### ISSUE TITLE
여전히 build fail

### ISSUE THREAD

**Issue by isty2e** [gureum/gureum#159]
.../gureum/GureumTests/GureumMockObjects.m4 

...

Ld /Users/isty2e/Library/Developer/Xcode/DerivedData/Gureum-fxypezfazzndcdgrotllqywlrwoo/Build/Products/Debug/OSXTests.xctest/Contents/MacOS/OSXTests normal x86_64
    cd /Users/isty2e/Desktop/gureum
    export MACOSX_DEPLOYMENT_TARGET=10.9
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -L/Users/isty2e/Library/Developer/Xcode/DerivedData/Gureum-fxypezfazzndcdgrotllqywlrwoo/Build/Products/Debug -F/Users/isty2e/Library/Developer/Xcode/DerivedData/Gureum-fxypezfazzndcdgrotllqywlrwoo/Build/Products/Debug -F/Applications/Xcode.app/Contents/Developer/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -filelist /Users/isty2e/Library/Developer/Xcode/DerivedData/Gureum-fxypezfazzndcdgrotllqywlrwoo/Build/Intermediates/Gureum.build/Debug/OSXTests.build/Objects-normal/x86_64/OSXTests.LinkFileList -mmacosx-version-min=10.9 -bundle_loader /Users/isty2e/Library/Developer/Xcode/DerivedData/Gureum-fxypezfazzndcdgrotllqywlrwoo/Build/Products/Debug/Gureum.app/Contents/MacOS/Gureum -ObjC -framework Cocoa -framework XCTest -fobjc-arc -fobjc-link-runtime -framework XCTest -Xlinker -dependency_info -Xlinker /Users/isty2e/Library/Developer/Xcode/DerivedData/Gureum-fxypezfazzndcdgrotllqywlrwoo/Build/Intermediates/Gureum.build/Debug/OSXTests.build/Objects-normal/x86_64/OSXTests_dependency_info.dat -o /Users/isty2e/Library/Developer/Xcode/DerivedData/Gureum-fxypezfazzndcdgrotllqywlrwoo/Build/Products/Debug/OSXTests.xctest/Contents/MacOS/OSXTests

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_CIMMockInputController", referenced from:
      objc-class-ref in GureumMockObjects.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

역시 cloning부터 시작했는데 빌드가 안 됩니다. 수정하시기 전에는 2sethangul 관련된 부분만 지우면 빌드는 잘 됐는데요...

**Comment by youknowone** [comment]
아이고.. 번거롭게 해서 죄송합니다.

일단 예전 버전으로 돌려서 하실 수 있을까요? 0bb2cc0 버전이고, 터미널에서 하시려면

```
git checkout 0bb2cc0
```
명령으로 하시면 됩니다.

휴가 중이라 다음 주에 돌아가서 다시 확인하도록 하겠습니다.
