### ISSUE TITLE
libhangul/구름 테스트에 관해

### ISSUE THREAD

**Issue by isty2e** [gureum/gureum#160]
libhangul에 신세벌식 관련 기능과 새로운 배열을 넣어 보았습니다만, 맥에서 터미널로 libhangul-gureum 빌드하기가 어렵습니다. ​Homebrew 기본으로 딸려 오는 automake/autoconf는 gettext와 libiconv가 링크가 되어 있지 않아서 곤란하고 말이죠. 그렇다면 결국 구름 입력기와 같이 빌드해서 테스트해야 하나요?

구름 입력기의 경우, 정확히 어떻게 테스트해야 하나요? XCode에서 빌드하고 OSX/tools에서 install_debug.sh 실행시켜서 나온 Gureum.app을 /Library/Input Methods에 넣고 테스트해야 하나요? ​HACKING.md에 나와 있는 instruction대로는 자판 추가가 안 되고, /Library/Input Methods/Gureum.app도 그대로인 것 같습니다. Gureum.app을 /Library/Input Methods에 넣고 로그아웃 후 로그인하는 것만으로는 구름이 정상적으로 실행되지 않고, XCode에서 run을 해야 실행이 되는 것 같습니다만... 제가 맥 애플리케이션 개발 쪽은 잘 몰라서 여쭙니다만, 정상적인 작동인지도 궁금합니다.

음 그리고, libhangul 수정하면 혹시 Objective C wrapper도 고쳐야 하나요? 제가 코드를 대충 훑어본 바로는 그럴 필요는 없었던 것 같습니다만...

일단 수정한 libhangul 혹시 모르니 링크 걸어 둡니다.

http://syhs4.cafe24.com/sebeol/libhangul-gureum_isty2e.zip

**Comment by youknowone** [comment]
답이 늦었습니다. 정신이 좀 없었는데, 빌드/디버그 관련은 최우선으로 응답해드리려고 하고 있습니다. 앞으로는 빠르게 응답해 드리겠습니다.

libhangul 빌드 및 테스트: libhangul 자체 테스트는 리눅스머신에서 하시면 편할 것 같습니다. homebrew로 빌드해보긴 했었는데 번거롭습니다.

터미널에서 빌드하기: xcode 이용해서 다음과 같이 빌드할 수 있습니다.
```
cd libhangul-objc
xcodebuild -project Hangul.xcodeproj
```

구름 바이너리 테스트하기:
OSX/tools 들어가시면 install_debug.sh가 있습니다. 이 스크립트가 디버그 빌드를 만들어 `/Library/Input Methods`에 넣고 기존의 프로세스는 죽이는 스크립트입니다. 수동으로 하시든 이 스크립트로 하시든 동작은 똑같습니다. 간혹 프로세스 죽이고 나면 입력기 인식이 안되는 경우가 생깁니다. 이 경우 사용자 로그아웃 하시고 다시 로그인하면 됩니다. xcode에서 run하는 것으로는 실행은 되지만 입력기로서 기능하지는 않습니다.

libhangul 수정: libhangul API를 고치지 않으면 objc wrapper도 수정하실 필요 없습니다.

**Comment by isty2e** [comment]
답변 감사합니다. libhangul 테스트는 다른 분들의 도움으로 끝냈고, 정상작동 확인했습니다.

구름 바이너리의 경우, install_debug.sh를 실행해도 /L/IM에는 추가가 되지 않는 것 같았습니다. 생성일/수정일도 그대로고, 시스템 환경설정-키보드-입력 소스에도 새로운 자판이 뜨지 않습니다. 그래서 빌드된 .app을 직접 /L/IM에 넣고 로그아웃-로그인을 합니다만, 이 경우도 일단은 메뉴 바에서 구름 아이콘을 눌러도 "..."만 뜨더군요. 이 상태에서 XCode로 xcworkspace를 다시 열어서 run을 하면 실행이 되긴 합니다만, 어떨 때는 input method가 죽었다면서 이 프로세스에서는 더 사용할 수 없다는 식으로 뜨기도 하고, 어떨 때는 작동하기도 합니다. 원래 이런 것인지, 아니면 뭔가 빌드-테스트상에 착오가 있는지도 궁금합니다.

아무튼, 제가 테스트할 수 있는 범위 내에서는 3-2015 자판을 테스트해 보았습니다. 시간 나시거든 pull request 검토해 주시면 감사하겠습니다.

**Comment by youknowone** [comment]
... 만 뜨는 경우는 입력기가 정상적으로 실행되지 않거나 동작을 멈춘 경우입니다.

실행 중인 입력기를 죽이고 다시 켜는 것 자체가 10.9 이후로 조금 동작 예측이 어려워졌습니다. 잘 되기도 하고 안되기도 합니다. 로그아웃-로그인을 하면 반드시 정상으로 동작하고, 그 후에도 동작하지 않는 경우는 잘못된 경우입니다.

xcode에서 실행하신 경우는 프로세스 자체는 실행되지만, OS의 입력기 서버로서 실행되는게 아닙니다. 그래서 실행 직후에 당장 크래시가 나는가 안나는가 테스트하는 정도 외에는 의미가 없습니다. 반드시 /Library/Input Methods에 설치한 상태에서 테스트 하셔야 합니다.

구름 설치한 상태에서 3-2015가 정상으로 동작하신다는 말씀이시죠?

**Comment by isty2e** [comment]
좀더 정확히 말씀드리자면, /L/IM에 설치하고 또한 XCode에서 run을 해야 테스트를 할 수 있게끔 정상작동했습니다. 후자만 하는 것은 당연히 별 의미가 없고, 전자만 하면 "..."만 떴습니다. 수정 없는 코드에서(옛날 버전으로도) clean build를 해도 그랬습니다. 뭐가 문젠진 아직 모르겠습니다만...

아무튼 전체 소스 코드를 수정하고 빌드한 결과 3-2015가 작동하는 것을 확인했습니다. 그런데 어떨 때는 정상작동하는 반면, 어떤 입력 방식을 선택해도 바로 죽는 경우도 있었습니다. 분명 build-test 과정 어딘가에서 문제가 있을 텐데 아직도 그 원인은 모르겠습니다.

**Comment by isty2e** [comment]
배포한 바이너리(.pkg)로 설치한 경우와 달리, XCode로 직접 빌드해서 테스트하면 /L/IM/Gureum.app/Contents/MacOS/Gureum을 실행했을 때 다음과 같은 메시지가 뜨는군요.

dyld: Library not loaded: @rpath/ShortcutRecorder.framework/Versions/A/ShortcutRecorder
  Referenced from: /Library/Input Methods/Gureum.app/Contents/MacOS/./Gureum
  Reason: image not found
zsh: trace trap  ./Gureum

Gureum.app을 /L/IM에 가져다 놓는 것으로만은 불충분한 건가요? .../Gureum.app/Contents/Frameworks/ShortcutRecorder.framework/Versions/A/ShortcutRecorder 자체는 존재하는데요. 배포용으로 archiving하는 것과, test용으로 target=debug 빌드를 하는 것의 차이인지, 아니면 제가 놓친 부분이 있는지 알고 싶습니다.

**Comment by isty2e** [comment]
우선 빌드 세팅 안에 있는 @rpath를 ../Frameworks로 바꾸어 빌드한 결과, Gureum.app/Contents/MacOS/Gureum 자체는 실행이 잘 됩니다. 로그아웃-로그인을 하고 나면 당장은 구름 아이콘을 클릭해도 "..."만 뜨지만 터미널에서 수동으로 /L/IM/Gureum.app/Contents/MacOS/Gureum을 실행하면 3-2015 자판이 정상작동하는 것을 확인했습니다. 

문제는 @rpath를 못 잡고 있는 것이 빌드상의 문제인지(즉, release가 아닌 debug로 빌드해서인지), 그리고 왜 별도로 ​Contents/MacOS/Gureum을 실행해야 하는지 정도인 것 같습니다.

어쨌든, 그렇게 편법(?)적으로 설치-실행을 하면 3-2015 자판의 구현과 작동에 문제가 없음을 확인했습니다.
