### ISSUE TITLE
Firefox로 Facebook 사용 중 입력 전환시 발생하는 문제.

### ISSUE THREAD

**Issue by Kjwon15** [gureum/gureum#162]
Firefox에서 Facebook Post 를 입력하는 도중 Shift+Space로 입력기 전환을 하는 순간 입력창이 초기화가 되어버립니다.
Facebook에서 스크립트를 잘 못 작성한 건지 어떤 건지는 모르겠지만 Cmd+Space로 전환을 하면 발생하지 않는 것을 보아 유니코드 공백문자가 입력되면서 발생하는 문제 같습니다.

**Comment by ujuc** [comment]
저도 그렇습니다... 이게 페이스북 문젠지 입력기 문젠지를 모르겠네요.ㅡ.ㅡ;;;

**Comment by soomtong** [comment]
파이어폭스의 한글 문제로 추측됩니다. 파이어폭스 특정 버전의 경우 기본입력기로도 구글 (웹)앱에서 한글입력이 불가능하기도 했습니다.
