### ISSUE TITLE
libhangul branch 와 관련하여...

### ISSUE THREAD

**Issue by Sinseiki** [gureum/gureum#163]
안녕하세요 제작자님? 저번에 크로스플랫폼 한글 입력기 백엔드를 개발하신다고 하셨었는데, 요즘 잘 지내시나요?

다름이 아니라 요즘 새로운 세벌식 자판들이 많이 만들어졌습니다.
그런데 마침, https://github.com/3beol/libhangul 에서 3beol 님께서 수정하시는 
libhangul 소스를 보게 되었는데, 이 libhangul 소스에는,

남한 두벌식, 북한 두벌식, 두벌식 순아래, 두벌식 옛글,
세벌식 314, 세벌식 389, 세벌식 390, 세벌식 최종 순아래,
세벌식 최종, 세벌식 393 옛한글, 세벌식 3-2011, 세벌식 3-2012,
세벌식 3-2014, 세벌식 3-2015, 세벌식 3-2015 옛한글, 세벌식 3-2015P,
세벌식 안마태 소리글판, 세벌식 김국 38A, 세벌식 모아치기 2014 (v150210), 세벌식 두벌 자판,
수정 신세벌식, 신세벌식 2012, 세벌식 순아래, 세벌식 새 순아래
자판이 들어 있었습니다.

혹시 이 소스 전체가 구름 입력기에 적용될 수 있을지 여쭐 수 있을까요?
저번에 신세벌식 2012를 구름 입력기에서 쓸 수 있었으면 좋겠다고 말씀하신 분도 생각나고 해서 이렇게 여쭙습니다...

**Comment by youknowone** [comment]
libhangul내장 배열 이외의 기타 자판배열에 관해서는 패치를 보내주시면 넣어드리는 것을 원칙으로 하고 있습니다. 패치를 만들어주시는 분이 있으면 다음 배포 때 포함하겠습니다.
다만 아무래도 주 사용자는 두벌식 사용자인 관계로 실 사용자가 없는 자판은 제외해 주셨으면 하고, 혹시 모두 포함해 주시면 임의로 배제하고 배포하도록 하겠습니다.

**Comment by isty2e** [comment]
gureum/libhangul과 3beol/libhangul은 좀 구조가 많이 달라져서 그대로 적용하려면 libhangul-objc wrapper를 뜯어고쳐야 할 겁니다. 제가 신세벌식을 쓸 수 있도록 gureum/libhangul에 조금 패치를 하긴 했는데, 어떻게 테스트해야 할지도 모르겠고 구름 자체도 정확히 어떤 과정을 거쳐서 테스트/디버그를 해야 하는지 모르겠네요.

**Comment by Sinseiki** [comment]
3-2015, 신세벌식 2012 자판들이 신세벌식 입력 방식을 사용하기 때문에 만일 패치를 만든다면 코드를 많이 만져야 할 것 같습니다. isty2e 님 말씀대로 libhangul-objc wrapper 까지 고쳐야한다면 어려운 문제가 되는군요... 원본 libhangul 처럼 리눅스에서 구름 입력기의 libhangul 빌드가 가능하다면 우분투에서 실험해볼 법도 한데, 구름 입력기에 있는 libhangul 만 따로 configure 와 make 를 이용해서 리눅스에서 빌드할 수 있는 방법이 있는지 모르겠네요...

**Comment by isty2e** [comment]
그건 그냥 autogen.sh 이용해서 컴파일하시면 될 겁니다. 리눅스라면 gnu gettext가 깔려 있을 테니까요.
