### ISSUE TITLE
Telegram에서 한글 사용시 엔터시 전송이 안되요

### ISSUE THREAD

**Issue by iamchanghyunpark** [gureum/gureum#165]
어느순간부터 구름 입력기로 OSX용 탤레그램 앱에서 메시지를 보낼때 글작성중에 엔터키를 치면 텔레그램 앱에서 line break되는 현상이 발생합니다. 물론 맞춤표와 같은 Symbol이나 숫자를 입력하고 엔터치면 전송되고요 ㅋ
이게 처음에는 텔레그램 문제인줄 알았는데, 입력기 문제 같더라구요... 한글 조합중에 엔터 누를때 엔터키가 영어/숫자/심볼이랑 같게되도록 부탁드립니다

**Comment by lbjcom** [comment]
구름입력기 사용자는 아니지만, 기본 한글 입력기를 사용해도 동일한 문제가 있습니다. 예제는 다음과 같습니다.
* ㅋㅋ(엔터) => 줄바꿈
* ㅋㅋ.(엔터) => 전송됨
* 크크(엔터) => 줄바꿈

텔레그램에서 원래 문제가 없다가 언젠가부터 (아마 업데이트 된 후?) 생긴 것 같습니다.

**Comment by ryush00** [comment]
이거 말고 다른 문제도 있습니다.. Telegram Native 클라이언트를 사용하면 글씨 두글짜가 따라오는 현상도 있습니다.

overtake/telegram#217

**Comment by youknowone** [comment]
이 문제는 텔레그램 클라이언트의 버그로 보입니다. 오래된 문제 같은데 아직도 안고쳐졌네요.
텔레그램에 return 키 입력시 조합중인 문자 commit 과 return 키 입력이 동시에 들어가는 경우 메시지 전송으로 처리해 달라고 요청하셔야 할것 같습니다.
