### ISSUE TITLE
구름입력기 개인정보 수집 질문 입니다..

### ISSUE THREAD

**Issue by idcklee** [gureum/gureum#166]
어제 구름 입력기를 설치 했는데요 .. 혹시나 해서 물어보고 싶은데요 .. 개인정보 수집은 없죠?...

**Comment by youknowone** [comment]
닫혔지만 중요한 이슈라 생각해 답변 드립니다.

구름입력기에서는 다음 버전 업데이트가 있는지 확인하는 용도 외에는 인터넷 연결을 하지 않습니다. 업데이트 확인을 하는 주소는 http://gureum.github.io/version.txt 입니다. 애플리케이션이 어떤 주소로 접근하는지 감시하는 도구들이 있는데, 그런 프로그램을 활용해서 확인해 보시면 어떤 주소로 접근하는지 하지 않는지 명확히 확인하실 수 있습니다.
