### ISSUE TITLE
블루투스 외장 키보드 배열과 관련하여

### ISSUE THREAD

**Issue by Sinseiki** [gureum/gureum#168]
안녕하세요? 블루투스 외장 키보드 배열 중에 세벌식과 잘 맞지 않는 배열이 나오는 게 좀 있는 것 같습니다. 특히 '/' 가 방향키 오른편에 있는 것이 많은데요, 이로 인해 세벌식을 사용하고자 하는 분들이 외장 키보드를 다시 사거나 해야 하는 일이 있는 듯 합니다. 혹시 이를 해결할 수 있도록 '/'나 따옴표를 다른 키로 대체하게 하는 기능이 있는지 여쭐 수 있을까요?

**Comment by Sinseiki** [comment]
생각해보니 맥북에서는 블루투스 외장 키보드를 쓸 일이 적군요, 신경쓰시게 해 드려서 죄송합니다. 바로 질문을 닫겠습니다...

**Comment by youknowone** [comment]
그런 키보드를 본적이 없어서 몰랐는데, 방향키 오른쪽의 /는 입력기 문제가 될 수 있다는 생각이 듭니다. 모음 조합을 허용해서 왼쪽에 있는 모음을 쓰거나 하는게 일단은 쉬운 해법인 것 같습니다.

**Comment by Sinseiki** [comment]
답글을 주셔서 감사합니다. 왼쪽의 모음을 사용할 수 있다면 바로 해결될 수 있는 문제인 것 같습니다. 신경써 주셔서 감사합니다.
