### ISSUE TITLE
세벌식 모아치기

### ISSUE THREAD

**Issue by elbaro** [gureum/gureum#169]
안녕하세요.

세벌식 모아치기 2014 자판에서 모아치기가 안되는 경우들이 있습니다.
ㅇ+ㅂ+ㅏ = 빠
ㅇ+ㅏ+ㅂ = 아ㅂ

온라인 입력기에선 두 경우 모두 빠 로 나옵니다.
http://3beol.github.io/

**Comment by youknowone** [comment]
2014는 현재 구름 메인스트림이 지원하는 자판이 아닌 별도의 포트로 관리되는 것으로 보입니다.
