### ISSUE TITLE
요세미티에서 한자 입력시 창이 보이지 않는 문제 + 발음이 아닌 뜻이 먼저 오는 문제..

### ISSUE THREAD

**Issue by likewind86** [gureum/gureum#170]
요세미티에서 한자를 입력하려고 할 때 간혹 선택창이 보이지 않는 문제가 있습니다. 커서를 이동한 후 엔터를 치면 한자가 들어가는 걸로 보아서는 단순히 창만 안 보이는 문제인 것 같아요. 두번째는 '성'을 입력 후 한자 입력창으로 들어가면 '성'발음이 나는 한자가 아니라 '성'으로 시작하는 뜻을 가진 한자들이 앞에 보입니다. 성 외에 몇몇 글자에서도 확인을 한 것 같은데 기억은 미처 나지 않네요;ㅁ;

**Comment by dahlia** [comment]
저도 같은 현상을 겪고 있습니다. 가령 ‘성’의 한자를 찾으려고 하면 아래와 같이 음이 ‘성’인 한자보다 뜻의 부분문자열로 ‘성’이 포함되는 글자들이 굉장히 높은 순위로 나옵니다.

<img width="680" alt="‘성’의 한자를 찾으려고 할 때" src="https://cloud.githubusercontent.com/assets/12431/13903461/bc0f69bc-eebf-11e5-8fc1-118be2c648ca.png">

뜻으로도 검색이 되는 것은 가끔 유용하긴 하지만, 보통 한자 입력할 때는 음을 기준으로 찾는 경우가 더 많을 것 같습니다. 그래서 음이 일치하는 한자를 우선적으로 보여주는 게 더 편할 것 같습니다.

**Comment by youknowone** [comment]
한자 입력엔 여전히 문제가 있지만, 창이 보이지 않는 문제는 재현이 되지 않습니다. 다음 버전부터 검색 순서가 교정됩니다. 테스트버전은 다음 링크에서 받아보실 수 있습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1
