### ISSUE TITLE
업데이트 확인 창 안뜨게 하는 법은 없나요?

### ISSUE THREAD

**Issue by rcts** [gureum/gureum#171]
![2015-05-27 8 45 44](https://cloud.githubusercontent.com/assets/12619037/7826621/b2d6a7fa-0457-11e5-865c-ba5f9ac00fd7.png)

부팅때마다 업데이트 확인 창이 뜨는데... 좀 거슬리네요 ㅜㅜ
업데이트가 더이상 안되는 os 10.6.8 이라..... 업데이트를 할수도없고....
혹시 안뜨게 설정하는 법은 없나요?

**Comment by soomtong** [comment]
안녕하세요. 생각해보니 몹시 불편하셨을 것 같아요. 1.4.1 의 코드는 지금 코드와 변경된 것이 무척 많아 개발자 분께서 해당 소스코드를 수정해서 다시 컴파일해서 보내드리긴 어려울 것 같다는 생각이 들어 코멘트 합니다.

이게 업데이트 기능을 차단한 패키지를 드려도 업데이트 조차 할 수 없는 상황이라 어쩔수 없이 해당 버전(1.4.1)을 계속 사용하실 수 밖에 없으시구요.

결국 버전 체크를 하는 코드를 우회하지 못하니 버전 체크하는 방법을 차단하는 것이 가장 손쉬울 것 같네요.

오에스텐의 hosts 파일에서 gureum.org 주소를 localhost 로 강제 바인딩 해 주시면 버전 체크 기능이 동작하지 않을 것 같습니다.

```
~ ❯❯❯ cd /etc/
/etc ❯❯❯ cat hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost

localhost 		gureum.org

/etc ❯❯❯
```

위 텍스트를 참고해주세요.

**Comment by rcts** [comment]
localhost 로 강제바인딩이 뭔지..... 너무어렵네요 저같은 일반인에겐..
어떻게 하는건지... 알수있는 사이트라던지 블로그알려주심 따라해볼게요 ㅜ.ㅜ

**Comment by soomtong** [comment]
명령 창에서 다음과 같이 입력해보세요 ^^

```
sudo vim /etc/hosts (엔터 후 패스워드 넣으세요)
(편집화면이 나타납니다)
('Go' 쉬프트 누르고 G 누르고 소문자 o 누릅니다)

127.0.0.1   gureum.org (옆의 문자열 입력해주세요 그리고 엔터 한번 쳐주세요)
(esc 키 누르고 ':wq' 세미콜론 위의 콜론과 w, q 를 연달아 눌러주세요)
```
이후 다시 로그인 하면 아마 적용되어 있을 거에요

**Comment by rcts** [comment]
감사합니다! 해결했어요.

**Comment by soomtong** [comment]
​
