### ISSUE TITLE
input sources에 한글과 영문 두개만 존재함에도 불구하고  한글전환이 안됩니다.

### ISSUE THREAD

**Issue by JaeyunJun** [gureum/gureum#172]
현재 10.11 El Capitan DP1을 올린 2014mid 맥북프로 레티나입니다.
1.8.9.c 최신버전을 사용중인데, 입력소스를 구름입력기의 han2set과 qwerty로 하든, 기본입력기와 섞어쓰든
사파리 주소창이나 메모, 카카오톡 등 일반적인 환경에서 영문만 되고
한영전환이 되지않는 버그가 있습니다.
대신 입력칸 외부를 클릭후 다시 입력하는 등의 방법으로 어떻게든 입력하고 있긴한데, 불편을 겪고 있습니다.

10.11이 비록 베타버전이긴 하나, yosemite보다 환경이 월등히 뛰어나 이용중입니다. 버그리포트 합니다.

**Comment by chaoswith** [comment]
저도 베타버전을 올린후 동일한 증상이 나타납니다.

**Comment by flankerz** [comment]
DP2 설치 후 같은 문제가 발생하여
입력기를 목록에서 삭제한후 재부팅, 
이후 다시 추가 하니 정상적으로 동작됩니다.
혹시 안되시면 해보세요~

**Comment by chaoswith** [comment]
![screen shot 2015-06-25 at 12 13 42 am](https://cloud.githubusercontent.com/assets/485090/8333681/2398546a-1acf-11e5-9c2f-f9c34d0ce5cf.jpg)
위와 같은 방법으로 고쳐지긴하나 어느순간부터 스크린샷의 상태가 되면 또 변환이 되질 않습니다
