### ISSUE TITLE
Android Studio ', " 키

### ISSUE THREAD

**Issue by goodhyun** [gureum/gureum#174]
Android Studio (1.2, 1.3)에서 
', " 키가 전혀 입력이 되지 않습니다. 
순정입력기로 돌아가서 입력해야 합니다. 원인을 잘 모르겠군요?

**Comment by soomtong** [comment]
![image](https://cloud.githubusercontent.com/assets/906974/8451629/96b39a90-201f-11e5-8ccf-89a403dc89fa.png)

안녕하세요. 국현님~

제 환경에서는 입력기가 정상 작동하고 있어서 스크린샷 첨부 드립니다.

OSX 10.10.4 / 구름입력기 1.8.3c 사용 중입니다.

**Comment by goodhyun** [comment]
네 감사합니다. 저도 issue 보고 후, 그 후 어쩐 일인지 다시 잘 되었습니다. :)
