### ISSUE TITLE
Alternote 앱에서 작동하지 않습니다

### ISSUE THREAD

**Issue by Canorus** [gureum/gureum#175]
아예 입력소스 리스트에서 회색처리되고
 ![default](https://cloud.githubusercontent.com/assets/7209435/8612809/b2ddb9fa-2711-11e5-82ea-157b46b520ca.png)
cmd+space로 변경하려고 보면 아예 선택사항에도 나오지 않습니다
![cmd space](https://cloud.githubusercontent.com/assets/7209435/8612810/b319d53e-2711-11e5-8ba9-16beb87258cf.png)
Finder에서 구름입력기로 놓고 Alternote 실행하면 다른 입력기로 자동으로 빠지네요

**Comment by soomtong** [comment]
![image](https://cloud.githubusercontent.com/assets/906974/15242238/03d4f1f0-1930-11e6-83a5-183b0ebabe1c.png)
현재 버전에서 이상 없음
