### ISSUE TITLE
안마태 자판 관련

### ISSUE THREAD

**Issue by solidsnake33** [gureum/gureum#176]
안녕하세요, 늘 감사히 잘 쓰고 있습니다.
사용자가 너무 적어서 그렇겠지만 안마태 자판을 선택하면 영문이 나오는데 계속 이슈가 안되고 있는 것 같아요.
혹시 수정이 가능하실지요?
자판배열이나 낱자 처리 등 제가 도울 수 있는 일이 있으면 돕겠습니다.

감사합니다.

**Comment by solidsnake33** [comment]
안녕하세요.
혹시나 새 OS와 더불어 새 버전에 지원 될 수 있을까 하는 기대에 또 올려 봅니다.
즐거운 추석 되세요.

**Comment by soomtong** [comment]
​답이 좀 늦긴 했지만 도움이 되실까 남깁니다.
비공식 구름입력기를 빌드했는데 안마테 자판이 포함되어 있습니다.
자판의 배열이나 입력 방식은 확인하지 않았지만
안마테 자판이 선택 가능하고 키 입력에 따라 한글은 잘 나타납니다.
https://github.com/soomtong/gureum/releases/tag/GureumKIM-1.9.1

**Comment by solidsnake33** [comment]
아! 정말 감사드립니다.
큰 불편을 덜었습니다.
이제 안심하고 애플 코리아에 입사 지원해도 되겠네요! 흐
다시 한 번 감사드립니다.

2016. 5. 13. 17:38 soomtong <notifications@github.com> 작성:

​답이 좀 늦긴 했지만 도움이 되실까 남깁니다.
비공식 구름입력기를 빌드했는데 안마테 자판이 포함되어 있습니다.
자판의 배열이나 입력 방식은 확인하지 않았지만
안마테 자판이 선택 가능하고 키 입력에 따라 한글은 잘 나타납니다.
https://github.com/soomtong/gureum/releases/tag/GureumKIM-1.9.1
