### ISSUE TITLE
OS X 10.11 El Capitan에서 사파리의 메모 공유기능에서 입력 문제 

### ISSUE THREAD

**Issue by neoadam** [gureum/gureum#178]
새로 추가된 사파리 공유 항목 중 메모로 보내기를 실행하면 구름입력기로 한글 입력이 안됩니다.
확인해보니 구름 입력기만 비활성화되네요. OS 기본 키보드는 문제 없이 작동합니다.

확인 부탁드려요. :-)
![2015-10-03 9 59 58](https://cloud.githubusercontent.com/assets/5254512/10263062/16d02f64-6a1b-11e5-8d77-8e3c5751a3c7.png)

**Comment by soomtong** [comment]
10.11 엘 캡 사용중입니다.

저는 잘 돼요.
![screen shot 2015-10-04 at 12 51 48](https://cloud.githubusercontent.com/assets/906974/10263696/308d5884-6a32-11e5-8ecc-f6f1ab3c51db.png)

**Comment by neoadam** [comment]
맥을 재부팅하니 해결되었습니다. 감사합니다.

**Comment by youknowone** [comment]
저보다 이슈 더 잘 확인해주시는 @soomtong 님~

OS 업데이트나 구름 버전 올릴때마다 비슷한 이슈가 올라오는데 어떻게 하면 안내가 되고 좋을까요 ㅎㅎ

**Comment by soomtong** [comment]
@youknowone 가장 편한 방법은 저 같은 사람을 많이 ~~고용~~ 확보하고 계시면 될 것 같아요.
어떤 분야든 사용자 많아지면 에반젤리스트도 생기고 전문 테크니션도 생기고... (세벌식 세상은 안될거야...)
어쩌겠어요. 이렇게 그냥 이슈를 잘 사용(지난 이슈 검색도 해보고 사용자가 적극적으로 문제 해결해서 피드백 주고 참여하도록 유도)는 방법이 좋겠죠 ㅋㅋ;
어서 새로운 백앤드 기반의 구름 2.0 을 만드세요! ㅋㅋㅋ;
