### ISSUE TITLE
쌍자음 연타

### ISSUE THREAD

**Issue by goodhyun** [gureum/gureum#181]
2벌식에서도 쌍자음 연타가 가능하게 되면 좋겠습니다. 

ㅂ+ㅂ = ㅃ

모음도 가능하면 더욱 좋겠습니다. 

ㅐ+ㅐ = ㅒ

좋은 프로그램 감사합니다.

**Comment by soomtong** [comment]
![guruem](https://cloud.githubusercontent.com/assets/906974/11243227/2e7ed004-8e4a-11e5-8652-d8164c35b917.gif)

두벌식도 됩니다. 

세벌식에는 자음 모음 조합하는 또다른 방법(주변 키와 함께 누르면 - 두 번 누르는 대신 두 손가락을 사용하는거죠.)도 있는데 두벌식에는 쌍자음만 제공되고 있네요.

**Comment by youknowone** [comment]
자음 연타 결합이 원래는 됐었는데 예측 불가능한 동작으로 불편하다는 이슈 접수가 많이 되어서 지금은 빠져 있습니다. @soomtong 님처럼 옛한글로 설정하면 되는 모양인데 옛한글 자판은 용도가 조금 다르지 않을까 싶네요.

**Comment by soomtong** [comment]
@youknowone 그렇군요!

**Comment by goodhyun** [comment]
모두 답변 감사합니다. 
다음 버전에서는 옵션으로라도 자음/모음 연타가 가능하면 참 좋겠습니다. 핸드폰이 타자 버릇을 바꿔버렸네요.
