### ISSUE TITLE
El Capitan 10.11.2 언어표시 문제

### ISSUE THREAD

**Issue by ysyukr** [gureum/gureum#182]
El Capitan 10.11.1까지는 한영 전환시 언어표시(국기)가 정확하게 이루어졌으나, 10.11.2 업데이트 이후로는 언어표시(국기)가 정확하게 나타나지 않습니다.

입력기의 기능은 정상적으로 작동합니다.

**Comment by Fantasy-Shin** [comment]
같은 버전입니다만, 저는 잘 표시되고 있는걸요?
