### ISSUE TITLE
구름입력기에서 알트를 조합한 특수문자 입력에 버그가 있네요.

### ISSUE THREAD

**Issue by Fantasy-Shin** [gureum/gureum#183]
두벌식 한글, 쿼티 영어자판 모두 버그가 있네요

Alt를 누르고 I, J, N 을 눌러도 특문이 입력되지 않거나 다음 문자를 입력하기 전 까지 딜레이가 생깁니다.
맥 기본 순정 자판은 정상적으로 특문이 입력되는걸로 보아 구름입력기만의 문제인 것 같습니다.

확인바랍니다.

**Comment by youknowone** [comment]
새 버전에서 영어 입력기로 '로마자'를 선택하면 시스템 자판과 동일하게 나오도록 수정하였습니다.

https://github.com/gureum/gureum/releases/tag/1.11.1
