### ISSUE TITLE
pycharm에서 한글작성시 space bar 오류

### ISSUE THREAD

**Issue by yevgnenll** [gureum/gureum#184]
파이참에서 구름 입력기를 통해 입력할때 스페이스바는 두번 눌러야 입력이 됩니다
확인 부탁드립니다

**Comment by snowdks** [comment]
안드로이드 스튜디오에서도 같은 현상 발생합니다.

**Comment by soomtong** [comment]
https://github.com/gureum/gureum/issues/149

**Comment by incleaf** [comment]
웹스톰에서도 같은 현상이 있습니다.

**Comment by soomtong** [comment]
@incleaf 같은 회사 제품 같은 종류들이라 다 마찬가지입니다. #149 참고하세요.
