### ISSUE TITLE
구름 쿼티 사용시 타 입력기 삭제 불가 문제

### ISSUE THREAD

**Issue by noxowl** [gureum/gureum#187]
아시다시피 맥에서 기본 영문 자판을 없애기 위해서는 다른 로마자 자판을 사용해야 없앨 수 있습니다.

하지만 구름 쿼티만 존재하는 상태에서 다른 로마자 자판이 삭제가 되지 않습니다.

입력 소스 선택에서는 구름 쿼티가 영문 자판 카테고리에 나오기는 하는데...

 히라가나 자판은 사용하지만, 기본 영문 자판을 없애려다 쓰지도 않는 일본어 로마자 자판을 쓰게 생겼습니다...

https://www.dropbox.com/s/6luwa8pvyjjstkc/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202016-02-02%2022.17.51.png?dl=0

**Comment by soomtong** [comment]
​이게 많은 사람이 사용하는 꼼수가 있습니다.
1. 일본어 추가한다.
2. 기본 영문 자판을 삭제한다.
3. 일본어를 다시 삭제한다.
4. 끝!
첨부된 이미지 참고해보세요.
![gureum-only](https://cloud.githubusercontent.com/assets/906974/14892983/7ebf847c-0da8-11e6-8991-20391d4fc42a.gif)

**Comment by noxowl** [comment]
위에 적혀있듯, 저는 일본어 자판도 쓰기 때문에 그 꼼수를 쓸 수 없습니다... ㅜㅜ

**Comment by soomtong** [comment]
삭제하고 싶은 자판이 일본어 키보드에 있는 영문 자판인가요?

**Comment by noxowl** [comment]
네. Romaji를 지우고 쿼티/세벌식/히라가나 이 세 자판만 쓰고 싶은데, 그게 안 되네요.

**Comment by soomtong** [comment]
ㅎㅎ; 이제 알았습니다!
구름입력기 개선 사항에 포함이 될지 안될지 모르겠지만 이런 문제도 있다는 걸 알았네요.

몇가지 테스트를 해본 제 소견으론 일본어 입력기가 구름입력기의 영문 자판을 인식하지 않는 관계로 
최소한의 영문 입력기를 강제하고 다는 것이군요.

구름입력기의 영문 입력기가 개선이 되던가 애플의 일본어 입력기가 구름입력기의 영문상태를 인식해주던가 
또는 둘 다가 되겠네요.

구름입력기의 영문 입력기는 기본 입력기로 작동합니다. 
제 소견으론 일본어 입력기의 문제가 맞지만
구름입력기는 서드파티고 일본어 입력기는 애플 제작이라;;;

아무튼 감사합니다.

**Comment by soomtong** [comment]
그냥 이렇게는 어떠세요?

![image](https://cloud.githubusercontent.com/assets/906974/14894447/a66c2bc8-0dae-11e6-8527-f0e6ca1ae24e.png)

구름입력기의 한글 자판만;;;

**Comment by noxowl** [comment]
터미널 쓸 때, 구름 ESC 전환이 맘에 들어서 현재는 그냥 입력기 4개 등록된 상태로 쓰고 있습니다.
Romaji는 빈 공간 같은거로 생각하고 있어요 ㅜㅜ

만약 이 이슈가 구름이 서드파티 입력기라 결코 해결 불가능한 것으로 판명된다면, 그래도 그냥 4개 등록 된 상태로 쓸 것 같습니다...
감사합니다.

**Comment by youknowone** [comment]
로마자 자판으로 인식되는 자판을 넣으면 사라지는 것 같은데, 어떻게 해야할지 잘 모르겠더라고요. 몇년 전 얘기긴 한데.. 이것 저것 바꿔봤지만 잘 안되는것만 확인했습니다 ㅜㅜ

**Comment by kangbu** [comment]
이런 좋은 꼼수가 있었덕분에 문제를 해결할 수 있었감사합니다.
