### ISSUE TITLE
esc키를 눌러서 로마전환을 체크했음에도 동작하지 않네요.

### ISSUE THREAD

**Issue by heose** [gureum/gureum#188]
저는 현재 요세미티를 사용중입니다.
왠지 저만 안되는것 같은데..
혹시 제가 확인해야할것들이 있을까요?
설치제거만 지금 20번은 한것 같습니다.

**Comment by soomtong** [comment]
보통 이 기능은 글자를 입력할 수 있는 상태. 그러니까 에디터 같은데에 포커스가 가 있는 상태에서 작동하는 기능입니다.
저도 그렇지 않은 상태에서는 작동하지 않네요. 
구름입력기는 글자를 입력할 수 있는 상태가 아니면 언제나 영문 모드로 작동하기 때문에 자판 아이콘이 변하지 않는다 하더라도 영문 상태의 단축키 등을 활용할 수 있습니다. (이게 큰 장점이기도 하구요)

**Comment by youknowone** [comment]
리포트만으로는 어떤 문제인지 확인이 어려워 닫습니다.
vi모드는 일반적인 입력환경에서는 잘 동작하는걸로 보입니다.
문제가 지속되면 문제 있는 애플리케이션 등을 특정해서 다시 알려주세요
