### ISSUE TITLE
영문 Dvorak 자판 사용자입니다.

### ISSUE THREAD

**Issue by pighair** [gureum/gureum#189]
안녕하세요? 바람 입력기를 꾸역꾸역 쓰다가 오늘 디아블로 2 단축키 설정 과정에서 고통을 겪고 검색 중 구름 입력기를 발견해서 방금 설치했습니다.

저는 한글은 세벌식, 영문은 드보락을 씁니다.
OSX 기본 한글 입력기는 단축키를 무조건 QWERTY로 입력받는 문제로 윈도우 쓰던 시절부터 고통받아 왔고, 윈도우에선 날개셋을 쓰다가 맥으로 넘어오면서 바람 입력기를 애용해 왔습니다. 하지만 업데이트가 안 되어 여러 문제가 있었고 새 입력기 프로젝트가 돌아가고 있다는 사실에 넘치는 기쁨으로 설치했는데... 영문 자판 추가 부분에 쿼티밖에 없네요. (시무룩) 설치하고 나서 발견한 문제점들을 나열해 보겠습니다.
- 구름 영문 자판이 쿼티 뿐이라 드보락 사용자는 Shift-Space로 한영 전환이 불가능함 (불편사항)
- OSX 입력기 설정이 쿼티 없이 Dvorak만 존재할 경우 구름의 한글 세벌식 뿐 아니라 쿼티 자판 사용시에도 단축키는 드보락으로 작동함. Option 조합 특수문자도 드보락으로 작동. (버그로 추정. 쿼티로 타자를 친다면 단축키도 Option 조합도 쿼티여야 하지 않는가요? 참고로 바람의 경우 영문 드보락 설정이 가능했으며 단축키를 쿼티로 할지 드보락으로 할지 설정 가능하였음) 현재 설정 상태는 
  ![scr 2016-04-19 00 10 56](https://cloud.githubusercontent.com/assets/18534209/14609307/3c3334a0-05c4-11e6-9f64-bafbf5f8493b.png)
  첨부 이미지 참조.
- 구름 쿼티 자판 상태로 디아블로 2 (영문판 확인) 사용 시 채팅 등 실제 텍스트 입력은 쿼티 입력으로 정상 작동하나 단축키는 어떤 키를 눌러도 A로 인식함. 한글 자판 상태로 구동할 때와 동일한 증상. 한글판은 삭제해서 테스트 불가

당분간 Cmd-Space만 이용하면서 사용해 봐야겠습니다. 아무튼 좋은 프로젝트 감사합니다.

**Comment by pighair** [comment]
드보락 지원 예정은 없나요? 결국 이용을 중단하고 바람 쓰고 있는데 잡다한 문제가 많아 빨리 바꿔 쓰고 싶습니다... 드보락 입력 및 단축키는 바람의 수많은 문제를 감내하며 쓸 만큼 중요한 기능이라서...

**Comment by pighair** [comment]
여전히 고통받고 있습니다 ㅡㅠ 이 쪽은 전혀 계획 없으신가요...

**Comment by youknowone** [comment]
최근에 자판은 구현했는데, 아직 배포는 못했습니다. 다음 업데이트에 포함하도록 해볼게요.
구현한 자판은 완전한 드보락은 아니고, 단축키는 쿼티로 동작하고 입력만 드보락으로 동작하는 방식입니다.

**Comment by youknowone** [comment]
#68 과 중복이므로 닫습니다
