### ISSUE TITLE
사파리 + 구글 문서 도구 사용 시 쿼티 첫 글자 무시 현상

### ISSUE THREAD

**Issue by SonienTaegi** [gureum/gureum#195]
사파리를 이용해 구글 문서도구 ( ​문서, 프레젠테이션 ) 를 이용 시 쿼티 자판을 이용하여 영어를 입력하면 첫 글자가 입력 되지 않는 현상이 있습니다. 좋은 도구 만들어주셔서 감사합니다.

![2016-05-03 1 37 24](https://cloud.githubusercontent.com/assets/8768553/14974785/4c6ce1d8-1134-11e6-864a-4ce382bc654f.png)

**Comment by soomtong** [comment]
![gureum in docs with safari](https://cloud.githubusercontent.com/assets/906974/14975946/0f225124-1142-11e6-9415-1ab7b753d0fc.gif)

구글 독스와 문제가 있네요.
확인했습니다. 감사합니다.

**Comment by youknowone** [comment]
혹시 지금도 발생하는 문제인가요? 저는 재현되지 않는듯 합니다
