### ISSUE TITLE
스카이프 대화창에서 한영전환시 스카이프 다운되는 현상

### ISSUE THREAD

**Issue by rkJun** [gureum/gureum#197]
El Capitan 10.11.5 사용중이고,

SKYPE 에서 한영 전환시 (Shift + Space) 항상 스카이프가 다운되어 버립니다. 

구름입력기에서 한영전환시에만, 발생하여 리포트 올립니다.

SKYPE 버전 7.27 (355)

좋은 프로그램 만들어 주셔서, 매번 감사드리며 사용하고 있습니다.

**Comment by soomtong** [comment]
개인적으로 스카이프를 종종 사용하는데요 (OSX EL Cap, Skype 모두 최신 업데이트) 한글 입력시 문제된 적은 없었어요. 물론 요즘도 사용하고 있구요.

제 경우 기본 입력기를 하나도 사용하지 않고 (또한 글로벌로 정해지는 입력기 변환용 단축키도 모두 클리어한 상태) 구름입력기만 세팅되어 사용하고 있습니다. (Shift+Space 로 한/영 전환)

다른 조건을 한 번 더 점검 해주시면 어떨까요?
그리고, 단축키를 통하지 않고 입력기 아이콘을 눌러서 변경할 경우는 어떤지도 확인해주세요.

**Comment by rkJun** [comment]
안녕하세요. 답변 감사드립니다.

제 경우에는 증상이 지속적으로 발생하여, (단축키 한영전환시 항시 발생)
재설치 등등 여러 방법을 동원해본 뒤, 아래 방법으로 해결하여 공유드립니다.

기존에 자판전환시 스페이스 입력방지 (IntelliJ 등) 옵션을 활성화해서 사용하고 있었는데,
혹시나 비활성해보고, 사용하니 스카이프가 다운되는 현상이 사라졌습니다.
혹시 동일한 증상을 겪을 분이 계실까봐 공유드립니다.

감사합니다.

**Comment by soomtong** [comment]
이유는 잘 모르겠지만 제 경우 해당 옵션을 활성화 해 두고 쓰고 있습니다.
저 역시 Jetbrains 의 IDE 를 사용하고 있는 중이라...

리포트 감사합니다.

**Comment by rkJun** [comment]
감사합니다.

말씀하신 대로, 저 역시 이유는 모르겠지만 집에서 사용하는 맥북에서 재테스트한 결과 (mbpr15-2012 model)
해당옵션이 활성화 되어 있는 상태임에도 불구하고 한영전환시에 스카이프가 다운되지 않고 정상 동작하는 것을
확인 했습니다. (os x, 구름입력기, skype 버전은 모두 동일)

다만, 여전히 회사에서 쓰는 모델(mbpr13-2015)에서는 옵션을 비활성화 해야만 정상동작 하고요.

**Comment by youknowone** [comment]
해당 설정은 의욕 넘치게 만들긴 했는데... 비정상 동작을 일으키는 환경이 있어 기본 설정으로 채택하지도 않고 있고 권장하지도 않고 있습니다. 설정 창에 어떤 앱에서 문제를 일으킬 수 있나 예시를 추가한다던가 해서 좀 더 경고를 명확하게 해볼까 싶네요.
