### ISSUE TITLE
Sierra에서 Caps Lock 으로 전환 기능 지원

### ISSUE THREAD

**Issue by synthresin** [gureum/gureum#199]
기본 한글 입력기를 추가하면 Caps Lock를 통해 한영전환하는 옵션이 활성화 되더군요.
이를 구름 입력기 단에서 지원할 수 있는지 궁금합니다.

**Comment by madnomad1101** [comment]
저도 이거 지원됐으면 좋겠네요

**Comment by pighair** [comment]
저도 이거 지원되었으면 좋겠습니다. 해당 기능은 Non-latin 자판 레이아웃과 영문 사이에서만 작동한다고 하더군요. 그래서 기본 일본어 자판도 안 되긴 합니다만...

**Comment by youknowone** [comment]
#261 다음 버전에 추가됩니다
