### ISSUE TITLE
jetbrain 툴에서 한글 띄어쓰기 이슈

### ISSUE THREAD

**Issue by kimjinwuk** [gureum/gureum#200]
한글을 치다가 띄어쓰기를 하게되면 띄어쓰기가 되지않습니다. 두번눌러줘야 띄어쓰기가 되네요

기본적으로 타이핑할때 커서가 한글의 좌측으로 가있구요.

그래서 띄어쓰기 한번하면 우측으로 이동하고 두번하면 띄어쓰기가 되는형식입니다.

**Comment by soomtong** [comment]
네 관련 이슈는 인지하고 있는 상황이에요 해결을 위해 많은 노력이 있었지만 아직은 ... 상태입니다.
불편하시더라도 감안해주세요.
#149 참고해주세요.
