### ISSUE TITLE
구름입력기 사용 시 텍스트 대치 

### ISSUE THREAD

**Issue by cnaa97** [gureum/gureum#204]
<img width="587" alt="screen shot 2016-11-25 at 3 40 49 pm" src="https://cloud.githubusercontent.com/assets/7259107/20616417/92e5c5d8-b325-11e6-8681-536a8f0d0509.png">

이런식으로 맥에서 텍스트 대치 (text replacement)를 사용중인데요, 구름입력기에서는 구현이 되어있지 않은지요?

**Comment by soomtong** [comment]
이건 입력기와 관계 없이 작동하는 기능입니다.
