### ISSUE TITLE
Sierra 10.12.1, 1.9.2-P2 Can't Using.

### ISSUE THREAD

**Issue by ZereInt** [gureum/gureum#205]
![screen shot 2016-11-27 at 11 54 19 am](https://cloud.githubusercontent.com/assets/7441807/20645152/561230d2-b498-11e6-84fa-d948b9d64426.png)
![screen shot 2016-11-27 at 11 54 41 am](https://cloud.githubusercontent.com/assets/7441807/20645153/5632f06a-b498-11e6-8956-e83122f16066.png)
![screen shot 2016-11-27 at 11 57 12 am](https://cloud.githubusercontent.com/assets/7441807/20645169/a8b3894e-b498-11e6-9d7d-2cd174e64233.png)

Sorry for the Hangul Typing.

Sierra 10.12.1
Gureum 1.9.2-P2

Keyboard Shortcut OK.
But, Can't using in the Textarea.

Take Care.

**Comment by ZereInt** [comment]
Gureum 1.8.9c-2015 Can Using.
But I Wanna use Sinsebul P2. Thanks.

**Comment by soomtong** [comment]
위 스크린 샷을 구름입력기가 제대로 설치되어 있지 않은 경우 나타나는 현상입니다.
이전 버전을 잘 지우시고 https://github.com/soomtong/gureum/releases 에 있는 버전을 다시 설치해보세요.
저도 시에라 12.1 사용중이고 구름입력기 1.9.2 사용 중입니다.

**Comment by ZereInt** [comment]
말씀 주신대로 이전 버전 잘 지운 후에 (AppCleaner App 사용) release 페이지에서 1.9.2, 1.9.2-P2 양쪽 모두 사용 시도해봤습니다만 여전히 동일한 결과가 나오네요. 텍스트 영역에서 어떤 식으로든 입력해봐도 전혀 글자가 나오지 않습니다. crash 로그도 동일하고요. 1.8.9c-2015는 설치 후 이상 현상 없이 잘 사용 가능합니다.
빠른 확인에 대해서는 진심으로 감사 드립니다.

**Comment by soomtong** [comment]
@ZereInt 해당 페이지의 zip 파일을 받아서 압축을 풀고 수동으로 
`/Sys.../Lib.../Inpu...` 이나 사용자 계정의 `~/Lib.../Inpu...` 에 넣어 보시고
입력기가 잘 로딩 되는지 확인 해 주세요. 이전 파일은 덮어 씌우기로 지워주셔도 되구요.
반드시 로그인/아웃 또는 리부팅 과정도 진행해 주세요.
답변 기다리겠습니다.

**Comment by soomtong** [comment]
@ZereInt 커스텀 맥과는 관련이 없습니다. 하...;; 도움이 되고 싶은데 앱이 실행되지 않는 부분이 좀 걸리네요. 입력기 자체가 로딩되지 못하는 문제는 보안 관련이 가장 커 보이지만 이미 이런 부분은 해결 가능하신 수준으로 보이니 그건 아닌 것 같구요.
나중에라도 성공하시면 리포트 한 번 부탁드립니다.

**Comment by ZereInt** [comment]
@soomtong 지금까지도 많이 신경써주셔서 감사할 따름입니다. 말씀대로 나중에라도 사용 가능하게 되면 추가 덧글로든 어떻게든 리포트 드리도록 하겠습니다. 고맙습니다~!
