### ISSUE TITLE
글자(한글)를 조합하는 상태가 selection 상태를 유지함 

### ISSUE THREAD

**Issue by soomtong** [gureum/gureum#206]
1. 미디움(medium.com) 스타일의 웹 입력기에서 흔히 볼 수 있는 문제 아닌 문제로
한글을 조합하는 상태가 글자가 선택된 상태로 판단되기에 
글자의 스타일을 변경할 수 있는 컨트롤 등이 팝업(Pop-up)되는 경우가 있음.

2. iA writer 같은 앱에서 현재 문서의 글자 수를 보여주는 경우가 있는데 
글자들이 selection 상태를 유지하는 경우에는 선택된 영역에 속하는 글자 수를 파악하는 기능이 있는 경우
한글을 입력할 때마다 이 부분이 해당 글자가 선택된 상태로 보고됨에 따라 원하는 대로 앱이 작동하지 않게 됨.

    ![image](https://cloud.githubusercontent.com/assets/906974/20736730/bdb0e878-b6eb-11e6-9625-634c4d824892.png)

**Comment by youknowone** [comment]
marked text와 selected text가 구분되어 있는데 구름은 편집중인 문자열을 marked text로 둡니다.
1의 경우 marked text에서 그런 동작이 있을법도 하다고 생각되는데, 2는 iA writer라는 앱의 버그 같습니다. 그쪽에 버그 리포트를 넣어 보는게 좋을 것 같아요.

**Comment by soomtong** [comment]
편집 상태를 나타내는 방법이 두 종류인 건 몰라네요. 👍
