### ISSUE TITLE
Gureum-192.zip 다운 후 실행 할 경우 열 수 없다며 실행되지 않습니다.

### ISSUE THREAD

**Issue by bitdata777** [gureum/gureum#207]
아래 시에라 설치 후 한글 입력 이슈를 읽고 구름 1.9.2 버전을 받았으나 정상 동작하지 않습니다.
app을 input methods에 추가하고 실행 할 경우 열리지 않으며 확인 결과 "해당 앱의 인증이 무효화되었습니다" 의 문제로
동작하지 않았습니다.
도움 부탁 드립니다.
![2016-12-11 11 03 52](https://cloud.githubusercontent.com/assets/24507417/21080727/c3293686-bff9-11e6-8c7c-3c634f8bc401.png)

**Comment by soomtong** [comment]
네 해당 사항은 알고 있는데 제가 개발자 계정이 없다보니 발생하는 문제 입니다. 
http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/
내용을 보시고 설치해 사용해 보세요. 물론 보안에 대한 위험은 감수하셔야 합니다.

사실 저도 저렇게 쓰고 있어요.

**Comment by bitdata777** [comment]
감사합니다^^
