### ISSUE TITLE
시에라에서 옛한글 입력시 '아래아'등 옛한글이 표시가 안됨니다.

### ISSUE THREAD

**Issue by songmink** [gureum/gureum#208]
좋은 한글 입력기 잘 사용하고 있습니다.
다름이 아니라 최근에 맥에서 "옛한글"을 입력하여야 하는 일이 생겨 사용해보니, 입력은 되는거 같은데 폰트를 제데로 못 불러 오는 거 같습니다. 예로, "ㅎ + , + ㄴ" 을 치면 ㅎ과 ㄴ만 표시되고 그 사이에 ','가 표시 되지 않습니다 혹시 원인과 해결책이 있으시면 알려주세요.

폰트는 은폰트, 나눔옛폰트, 함초롱등 옛한글이 포함된 폰트를 다 사용해봤습니다. 하늘입력기라는 것도 사용해보았는데 결과는 마찬가지더군요. 은폰트가 가장 비슷하게 표현되는데 ㅎ 과 ㄴ이 아래위로 배치는 되는데 ',' 가 표시되지 않네요.

그리고 구름 입력기로 한글 입력시 함초롱등 한글 폰트로 설정하고 편집(텍스트에딧터, 워드등)을 시작하면 설정한 한글 폰트가 아니라 맥 한글 기본 폰트인 '바탕' 으로 자동으로 무조건 바뀌는 현상도 있습니다. 은폰트는 괜찮은데 다른 한글 폰트는 무조건 바탕으로 자동으로 바뀌는데 이 현상 해결방법도 아시는 분 있으시면 알려주시면 감사하겠습니다.

**Comment by youknowone** [comment]
옛한글 입력 관련된 문제가 최신 베타 릴리즈에서 해결되었습니다. https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre8

폰트의 문제는 입력기에서 관여하는 문제가 아닐것 같습니다. 입력기에서는 조합이 끝난 문자의 폰트를 손댈 수 없습니다.

**Comment by youknowone** [comment]
1.10을 정식으로 릴리즈하였습니다. 문제가 지속되면 다시 알려주세요. https://github.com/gureum/gureum/releases/1.10.0
