### ISSUE TITLE
Finder 에서 파일이름 수정시 동작불능

### ISSUE THREAD

**Issue by lovetoken** [gureum/gureum#209]
안녕하세요 오래전부터 구름 한글입력기를 사용한 유저입니다.
어느시점인가 부터인지 모르겠는데 파인더에서 파일이름을 수정할 때 구름을 이용한 한글입력시 아무 반응이 없습니다. (물론 영타로 전환하면 정상적입니다)

두벌식을 사용하는 중에 일어나는 일이며 
동작환경은 아래와 같습니다.

*macOS Sierra 10.12.3*
*MacBook Pro (Retina, 13-inch, Early 2015)*

추가로 부수적인 이슈인데, 작성하자면 

<img width="182" alt="2017-02-09 4 49 26" src="https://cloud.githubusercontent.com/assets/10364468/22773930/0b76e722-eee8-11e6-837b-ee354347f168.png">

위 사진의 메뉴의 6개항목 모두 클릭해도 반응이 없습니다.
또한 가끔씩 항목이 뜨지않고 "........" 으로 표기될 때도 있습니다.
아래처럼요

<img width="197" alt="2017-02-09 4 52 59" src="https://cloud.githubusercontent.com/assets/10364468/22773977/3d400f5e-eee8-11e6-8b13-e7c7fdabb5f1.png">

부가적인 동작환경 제보가 필요하다면 말씀주세요!

**Comment by youknowone** [comment]
구름이 다른 버그로 인해 크래시된 이후 살아난 상황에서 응답이 없는 증상으로 보입니다. 죄송하지만 어떤 문제와 연결된 상황인지 알기 어려우므로 이 이슈는 닫도록 하겠습니다.
