### ISSUE TITLE
간헐적으로 눈에 보이지 않는 문자(BS)가 삽입되는 문제

### ISSUE THREAD

**Issue by reznoa** [gureum/gureum#210]
원인을 알 수 없는 이유, 시기로
눈에 보이지 않는 문자가 삽입되는 문제가 있습니다.
문서 작성 후 최종 결과물이 잘못된 경우도 있고,
값이 달라져 검색에서 누락되거나(예를들어, '구름' 사이에 삽입되면 '구{?}름'이라 '구름'으로 검색 안됨),
브라우저에서 주소를 입력했을 때 삽입된 문자로인해 주소로 인지 못해 검색으로 넘어간 경우도 있었습니다.

삽입 문자는 BS(0x08)로,
구름에서 '스페이스 입력 방지'를 위해 사용한 코드로 인해 이런 문제가 발생하는것 아닌가 싶습니다.

**Comment by Elevista** [comment]
![pasted image at 2017_08_03 02_53 pm](https://user-images.githubusercontent.com/9513647/28908051-4c993a86-785c-11e7-82b8-570e0c083e83.png)
저도 ㅠ

**Comment by youknowone** [comment]
관련된 기능이 유지보수가 불가능한 상태라 새 버전에서는 제거하였습니다.

**Comment by Elevista** [comment]
오 나이수
