### ISSUE TITLE
한자 입력의 다양한 오동작

### ISSUE THREAD

**Issue by sim1204** [gureum/gureum#213]
한자 변환 창을 띄운 경우에, 숫자키로 입력이 되지 않으며 방향키를 사용할 시에는 입력하던 줄이 위아래로 바뀌게 됩니다. 

또, 수水를 치게 되면 이렇게 한글을 남겨두고 변환이 되게 되는데, 이것을 변경하는 환경설정이 어디에 있는지 궁금합니다. 

또, 키보드 환경설정에 구름 입력기를 추가할 때에 키보드 레이아웃 사용불가라고 뜨는데 원인이 무엇인지 모르겠습니다.

**Comment by choi4450** [comment]
'한자 변환 창을 띄운 경우에, 숫자키로 입력이 되지 않으며 방향키를 사용할 시에는 입력하던 줄이 위아래로 바뀌게 됩니다.'

저도 동일합니다. 한자 변환 창을 띄운 이후에는 마우스로만 선택 및 변환이 가능합니다.

**Comment by pighair** [comment]
저는 마우스로도 안 됩니다. 숫자입력/방향키+엔터/마우스클릭 모두 안 먹힙니다. 하이 시에라입니다.

**Comment by youknowone** [comment]
리포트 감사합니다. 수정해 보도록 하겠습니다.

**Comment by Infinitykang87** [comment]
저도 글자(또는 자음)입력 후 한자입력 단축키 사용 시 윗분들 모두의 증상과 같이 숫자키로 입력, 방향키 사용, 마우스 사용까지 먹통이 됩니다.

심지어 이러한 현상 이후에는 언어변환을 하더라도 한글입력이 안되고 영문으로만 입력이되는 현상도 더불어 발견됩니다.

여러 버전으로 다시 설치해보고 하다가 찾아낸 사용상 임시방편을 말씀드리자면 1.8.9c 기준으로 한자(또는 특수문자)를 위한 문자 입력 후 '한자 단축키'를 실행하는 것이 아닙니다.

먼저 '한자 단축키'를 수행 후 문자를 타이핑하면 이전과 같이 동일하게 방향키, 마우스로 한자 변환이나 특수문자 변환이 가능합니다. (숫자키 입력은 여전히 안됨)

한창 단어(또는 자음)입력 후 한자(또는 특수문자)로 변환하여 사용하는데에는 여전히 어려움이 있지만 임시방편으로 크게 어려움 없이 사용 가능한 것으로 확인됩니다.

1. '한자 단축키'를 먼저 수행한다.
2. 원하는 글자(또는 자음)을 입력하면 한자(또는 특수문자) 입력 레이어가 뜨게 된다.
3. 방향키, 마우스로 선택하여 사용한다. (숫자키 입력은 여전히 안됨)

**Comment by youknowone** [comment]
아직 한자 입력기에 많은 문제가 남아있습니다.

- [ ] 방향키로 후보 전환이 되지 않음
- [ ] 한자 입력 모드에서 벗어나도 후보창이 닫기지 않음
- [ ] 숫자 키로 후보 선택이 되지 않음

**Comment by ysBach** [comment]
저도 동일한 현상입니다.

방향키로 후보변환이 안됨 (한자변환 실행하지 않은 상태로 방향키 누르는 것과 동일한 반응)
리턴키로 한자입력이 안됨 (한글만 그대로 남아있는 채로 개행됨)
숫자키로 한자입력이 안됨 (잘못된 키를 눌렀을 때 나는 것 같은 "텅" 소리?만 나고 아무 변화가 없음)

이것 때문에 아직 구름입력기로 넘어가지 못하고 있는데 아쉬워요..

**Comment by soomtong** [comment]
@sim1204 님 리포트 감사합니다.
의도는 이해합니다만 어떤 이유가 되었던 본 프로젝트 담당자들이 해당 이슈에 대해 따로 메일 드리는 일은 적절하지 않습니다. 남겨주신 이메일은 삭제했습니다. 참고해주세요~

**Comment by yous** [comment]
방향키 후보 전환은 #586, 리턴키로 후보 선택은 #621 로 어느 정도 해결될 것 같습니다.

숫자로 후보 선택하는 기능은 `IMKCandidates.selectionKeys()`를 봤을 때 1부터 9에 해당하는 키 코드가 제대로 나오는데, `interpretKeyEvents()`를 해도 변화가 없습니다. 별도로 처리하려고 해보았으나 `candidateStringIdentifier(candidateString:)`, `candidateIdentifier(atLineNumber:)`가 모두 0만 반환해 `selectCandidate(candidateIdentifier:)`를 제대로 호출할 수 없는 상태입니다.

**Comment by youknowone** [comment]
한자 입력 관련 문제가 대폭 수정된 새 실험버전이 배포되었습니다. experimental4를 설치하시면 테스트해보실 수 있습니다.

https://github.com/gureum/gureum/releases/tag/GureumKIM-1.11.0-experimental

**Comment by youknowone** [comment]
모두 수정된 새 버전을 배포하였습니다.

https://github.com/gureum/gureum/releases/tag/1.11.1
