### ISSUE TITLE
Mac의 Things 앱에서 동작을 하지 않습니다.

### ISSUE THREAD

**Issue by seungdols** [gureum/gureum#214]
# 이슈

* Things 앱에서 구름 입력기가 동작하지 않습니다. ​ 
* 단축키 : 쉬프트 + 스페이스를 쓰고 있습니다. 

mac os
* Mac Sierra 10.12.4

gureum 
* 1.8.9c

**Comment by flatcoke** [comment]
같은 증상입니다.

**Comment by mycoolade** [comment]
기본입력기에서도 shift+space를 한번 더 매핑해주세요. 이렇게하면 하늑ㄹ이 잘 인식됩니다.

![20170816235607](https://user-images.githubusercontent.com/25071540/29369766-81f03644-82de-11e7-9012-08ebecdc5fd7.png)

**Comment by seungdols** [comment]
@ghost 감사합니다. 잘 동작 합니다.
