### ISSUE TITLE
기본 한영전환 단축키를 Disable하는 옵션추가

### ISSUE THREAD

**Issue by Xeite** [gureum/gureum#215]
안녕하세요, 입력기 잘사용하고 있습니다. :)
저는 한영전환에 오른쪽 Alt 키를 사용하고 있는데요. 기본 Mapping인 shift + space 는 disable 할 수 있는 옵션이 추가 되었으면 좋겠습니다. space가 기본적으로 단독으로 사용되는 경우가 많다보니 키가 씹히는 경우가 좀 있더라고요.

감사합니다.

**Comment by soomtong** [comment]
안녕하세요!
기본입력키 매핑 자체를 disable 할 수 있지요. 저 역시 그렇게 사용하고 있습니당.

![screen shot 2017-06-04 at 10 10 04 pm](https://cloud.githubusercontent.com/assets/906974/26761882/9836a28a-4972-11e7-9c1c-db8eb2ee7fb3.png)

**Comment by Xeite** [comment]
으아니, 그냥 거기에 있는걸 쓰면 되는거였군요. 감사합니다..;

**Comment by youknowone** [comment]
구름 설정에서 언어바꾸기 단축키에 스페이스 같은걸 넣으면 단축키 제거할수 있습니다. 제거 버튼이 명시적으로 있는 편이 나을까요?

**Comment by soomtong** [comment]
@youknowone 할 수 있으면 나쁘지 않죠!

**Comment by soomtong** [comment]
@Xeite 헉, 미안해요 엉뚱한 답변을 했네요 대충 넘어가요 ㅋㅋ.

**Comment by youknowone** [comment]
새로 릴리즈하면서 기본 전환 단축키를 제거하였습니다.
