### ISSUE TITLE
3-2015를 사용할 수 있는 방법은 없을까요?

### ISSUE THREAD

**Issue by MiRiKan** [gureum/gureum#218]
윈도우만 쓰다가 처음으로 OS X 사용을 시작했는데
모아치기라고 해야하나요? ㅇ+ㄱ=ㄲ 가 익숙해져 있다 보니 대신 2012를 사용하려고 해도 너무 힘드네요.
혹시 3-2015를 사용할 수 있는 방법이 있을까요?

**Comment by soomtong** [comment]
https://github.com/soomtong/gureum/releases
여기에 있는 걸 한 번 사용해보세요.

**Comment by MiRiKan** [comment]
감사합니다.
