### ISSUE TITLE
Bug: slack 에서 입력기 변환시 비활성화 됨

### ISSUE THREAD

**Issue by whomakemecrazy** [gureum/gureum#219]
issue 

- slack 2.7.1 에서  한글입력시 활성화가 안됩니다. 

info 
mac sierra 
gureum 1.8.9.c

**Comment by dialogbox** [comment]
저도 동일 증상 입니다.

OS: Sierra 10.12.6 (16G29)
Gureum: 1.9.2

---
좀 더 자세히 설명 하자면...

* 다른 프로그램이나 vscode 등에서는 정상적으로 한글 입력이 됩니다.
* Slack의 입력창에서는 한글 입력기로 전환이 안되며 입력기 선택 메뉴에서 구름 입력기가 비활성화 되어 있습니다.

---
Quiver라는 프로그램을 사용중인데 이 프로그램에서도 동일합니다.
한가지 특이한 점은 이 프로그램에서 Mac OS의 기본 한글 입력기를 사용하면

* 한글 입력기가 정상적으로 활성화는 됨
* 일반 입력 모드에서는 한글 입력 정상
* Markdown 입력 모드에서는 자소가 풀림 - (ㅇㅏㄴㄴㅕㅇ)

구름 입력기는 비활성화 되어 있어서 선택이 안되고 CMD+Space를 눌러도 전환이 안됩니다.
---
Outlook 2016에서는 증상이 또 약간 다릅니다.

Version: 15.39

이번에는 입력 메뉴에서 활성화는 되어 있으나 선택이 안됩니다.
CMD+Space도 역시 안먹고 영어로만 입력이 됩니다. Mac OS의 기본 한글 입력기는 정상 동작 합니다.

**Comment by soomtong** [comment]
ElectronJS 맥 버전의 경우 간간히 버그가 존재하고 있습니다.
버그 픽스가 빠른 편입니다.

현재 slack 은 버전 3.x 가 진행 중 입니다. 
제 경우 macOS 시에라와 하이 시에라에서 해당 문제가 발생하지 않고 있습니다.

특정 버전의 앱 문제는 낮은 우선 순위로 처리하는 편입니다.
위에 말씀해 주신 이슈들이 현재 재현되고 있다면 다시 코멘트 남겨주세요.

**Comment by zero2young** [comment]
2022.10.21 현재 여전히 Slack에서 한글 변환이 안되는 증상이 있습니다.
키보드 단축키를 누르거나, 마우스로 구름입력기를 클릭해도 한글로 전환이 안되네요.

OS : macOS Monterey
H/W : Mac mini (M1, 2020)

Slack 버전 : 4.28.185

**Comment by jeus0630** [comment]
2022.10.25
슬랙에서 작동하지 않는 현상 발생하여 기본 키보드 설정을 슬랙에서 복구해서 쓰고 있습니다.

OS: macOS Monterey 12.6
Slack: 4.28.184
