### ISSUE TITLE
High Sierra 에서 환경설정이 열리지 않음

### ISSUE THREAD

**Issue by jeongmin96** [gureum/gureum#220]
구름입력기 환경설정이 열리지 않습니다.

**Comment by eunchan** [comment]
저도 동일한 현상을 겪고 있습니다. .. 제작자분께서 바쁘신가봐요...

**Comment by pighair** [comment]
저도 안 됩니다...

**Comment by youknowone** [comment]
OS에서 환경설정 처리 방식이 바뀌었습니다. 일단 동작하지 않는 환경설정을 떼게 되었고, 앞으로 같은 기능을 시스템 환경설정에 업데이트하려고 합니다.

#226

**Comment by UngCheul-Kim** [comment]
그럼 현재로서는  Shift + Space로 한영 전환을 할 방법은 없는 것인가요? Control + Space 로 전환을 하려니 너무 어색하네요. ㅠㅠ

**Comment by youknowone** [comment]
시스템 환경설정에서 Fn + Shift + Space 로 단축키 설정을 하시면 시프트 스페이스로 지정이 됩니다.

급하게 업데이트하느라 제대로 변경사항을 공지드리지 못해서 죄송한데요. 차기버전부터는 환경설정을 별도 창이 아닌 키보드 환경설정에 통합해 제공하려고 합니다.

현재는 단축키 설정에 관한 안내만 텍스트로 들어가 있습니다

![image](https://user-images.githubusercontent.com/69878/33475699-b6c45c1e-d6c2-11e7-9c01-46c5ac72e45e.png)

**Comment by UngCheul-Kim** [comment]
예. 빠른 답변 감사드립니다.
하이 씨에라 사용중인데.. 첨부한 이미지처럼 아무런 안내 메시지가 나오지 않아서...
질문드렸습니다.

좋은 입력기 개발을 해 주신것 감사드립니다.

![keyboard 2017-12-01 18-13-25](https://user-images.githubusercontent.com/18651490/33475891-575dfc20-d6c3-11e7-8c30-9a67b7d399e9.png)

**Comment by youknowone** [comment]
이것도 환경에 따라 문제가 있나보네요. 제보 감사합니다.

**Comment by unconcept** [comment]
안녕하세요, 구름 잘 쓰고 있는 유저인데요,,,
시프트+스페이스로 설정하고 싶어서 단축키에 들어가서
말씀하신대로 펑션+쉬프트+스페이스로 설정을 하려고 해도 설정이 안되는데 (띵 소리가 나면서 바뀌지가 않네요),
왜 그런거인지 궁금합니당!

**Comment by youknowone** [comment]
#261 다음 버전에서 환경설정 관련 이슈를 해결합니다
