### ISSUE TITLE
Bugs: IntelliJ에서 스페이스 문제

### ISSUE THREAD

**Issue by seungdols** [gureum/gureum#222]
# 이슈 

* 인텔리j 프로그램 상에서 한글 두벌식의 경우 스페이스 바를 2번 눌러야 스페이스 인식되는 문제입니다.

## 환경 

* 구름 : 1.8.9c
* 하이 시에라 10.13

**Comment by youknowone** [comment]
ref: #23

**Comment by youknowone** [comment]
안녕하세요. 1.9.0 이후부터 내장 자판전환 버튼을 기본기능에서 제거합니다.
대신 시스템 단축키 사용에 관한 안내를 추가했습니다.
