### ISSUE TITLE
high sierra에서 한영전환 단축키(shift+space) 정상동작하지 않는 경우 발생

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#225]

**Comment by youknowone** [comment]
설치직후에 문제 있었는데 재시작하니 두번 하니 사라졌습니다

**Comment by seungmin84** [comment]
예전버전 아무 이상 없이 잘 쓰고 있었는데
오늘 1.9 버전 업데이트 하라고 떠서 받았더니
한영전환이 안되네요.
몇가지 테스트해보니 쉬프트+스페이스에서
fn+쉬프트+스페이스로 강제 변경되었습니다.
너무 불편한데 패치 해주시면 안되나요?
