### ISSUE TITLE
한자입력 안됨

### ISSUE THREAD

**Issue by haeruori** [gureum/gureum#229]
오늘 오전에 구름 high sierra 업데이트하라고 뜨길레 업데이트하고나서 시스템이 버그걸려서 애먹고
결국 이렇게 문의드립니다.
그전까진 잘되었는데 그 담부터 인디자인에서 한자입력이 안됩니다.
현재 깔린 구름버전을 삭제하는 법은 무엇인가요?
삭제하고 그전 버전으로 다시 깔았으면 해서요. 
제 시스템은 Mac Sierra 10.12.6입니다.

**Comment by youknowone** [comment]
한자 입력이 구버전으로도 high sierra에서 문제가 계속 생긴다는 리포트가 있는 상황이라, 이전버전으로 해결될지는 잘 모르겠습니다.

일단 이전 릴리즈는 다음 페이지에서 모두 찾으실 수 있습니다.
https://github.com/gureum/gureum/releases

**Comment by haeruori** [comment]
GureumKIM-1.8.9c로 다시 설치했는데도 한자입력이 안됩니다.
온종일 이거 설치했다 저거 설치했다 난리를 쳤습니다. 이 앱을 클리닝하고 다시 설치했으면 하는데 제거하는 방법을 모르겠습니다. 쿽에서는 다 되는데 인디자인에서만 안됩니다. 원래 인디자인때문에 설치했었는데요.

**Comment by youknowone** [comment]
#213 과 혹시 유사한 증상이시면, 버전 문제가 아닐수 있습니다.

설치된 위치는 이미지 첨부해드리겠습니다.

![image](https://user-images.githubusercontent.com/69878/33470293-cd62d60c-d6aa-11e7-9bcb-d996a6e88aae.png)

**Comment by haeruori** [comment]
한자 입력창이 아예 뜨지 않으며 옵션 리턴키를 치면 글자가 사라지고 다시 커맨드 스페이스바치면 그 다음부터는 아예 한글 한자 변환이 안되고 먹통이 되어버립니다.

**Comment by haeruori** [comment]
저는 input Methods 폴더에 아무것도 뜨지 않습니다.

**Comment by youknowone** [comment]
'라이브러리' 라는 폴더가 여러군데에 있고, Input Methods라는 폴더도 여러군데에 있는데요. 위에 첨부드린 이미지 하단 바에 뜨는것처럼,
그 중 루트->라이브러리->Input Methods 가 맞는지 확인해 주실수 있을까요? 셸 경로로 표현하면 `/Library/Input Methods` 입니다.
사용자 폴더에 있는 라이브러리를 여셨으면 아무것도 없는게 정상입니다.

**Comment by haeruori** [comment]
사용자 폴더 라이브러리와 시스템 라이브러리 다 뒤져도 구름은 없습니다. ㅠㅠ...

**Comment by youknowone** [comment]
#261 다음 버전에서 한자 관련 이슈를 해결합니다
