### ISSUE TITLE
IntelliJ IDEA 에서 한글 입력시 Space키가 작동하지 않습니다.

### ISSUE THREAD

**Issue by zipuragi** [gureum/gureum#23]
구름입력기로 시프트+스페이스 설정해서 사용중이고요

IntelliJ IDEA를 사용하고 있습니다.(JAVA IDE 프로그램)
한글 입력 후 스페이스를 눌러서 띄어쓰기를 하려고 했으니 되지 않습니다.

스페이스바를 두번씩 눌러줘야 띄어쓰기가 됩니다.

기본입력기로 바꿔서 해보면 정상적으로 띄어쓰기가 됩니다.
구름에서만 안되더군요

시프트+스페이스를 쓰기 위해서 구름을 쓰는거라 기본입력기로 쓸 수는 없는 상황이고요
어떻게 하면 구름입력기에서 스페이스 문제가 해결될까요?

입력되는걸 보니 입력커서의 위치가 마지막 글자 바로 앞자로 표시되더군요
그래서 스페이스 두번을 눌러야 띄어쓰기가 되는것으로 보입니다.
버그라면..개선 부탁드리고요 방법이 있다면 알고 싶습니다.
감사합니다^^

**Comment by pkjoohwan** [comment]
Java 가상 머신으로 구동하는 JAR 파일의 경우에도 나타나는 현상 같습니다. (개인적으로 만든 간단한 앱에서 동일 증상 나타남)
한글 작성 중 스페이스 입력 시 1회 빈칸 입력 안 됨
한글 작성 중 엔터 입력 시 마지막 글자 사라짐

**Comment by kfmes** [comment]
구름 1.8.9c 에서 IntelliJ 사용중입니다.
세벌식 최종을 사용하고 있으며 윗분들이 언급하신 내용들과 중복되는 내용일수 있으나 적어봅니다.
한글 입력상태에서 시프트 jkl; 을 타이핑을하면 1234 와 같이 입력이 되어야 하는데 영문자 그대로 입력이 됩니다.

**Comment by item4** [comment]
1.8.9c
OS X 10.11
InteilliJ 14.1.5

기본 입력기도 이상해서 구름으로 옮겨왔는데 구름도 이상합니다..

**Comment by Kernelzero** [comment]
1.8.9c
OSX 10.12.1 (Sierra)
Android Studio 2.3.0

기본입력기에서는 제대로 작동하나 구름입력기에서는 제대로 동작하지 않습니다.

**Comment by soomtong** [comment]
@Kernelzero 
https://github.com/gureum/gureum/issues/23#issuecomment-64146989
보시면 아시겠지만 이 상태는 이미 알고 있습니다. 시에라의 새로운 입력기는 정상 작동하는데 새로운 입력기가 어떤 API 를 사용했는지 알 수 없는 상태구요. 무엇보다도 애플에서 제공하는 입력기 API 문서가 10.5 쯤 공개되고 그 이후로 업데이트가 되지 않고 있어요. 분명히 뭐가 바뀐 거 같기도 하고 새로운 API 가 추가됐을 법한데 모르겠네요.
우선은 불편하시다면 기본 입력기를 사용하도록 해보세요.
저도 몇 달 전에 기본 입력기로 돌아갔다가 표준 자판을 고쳐 쓰는 저는 다시 구름을 사용하고 있는데요. 
젯브레인 제품에서 그냥 한글을 사용하는 걸 포기했습니다 ^^ 이 외에도 몇 가지 문제가 더 있는데 당장 해결하기가 어려운 상황입니다.

**Comment by Kernelzero** [comment]
@soomtong 
넵 답변감사합니다. 한글처리하는게 여간 까다로운 일이 아니란걸 잘 알고 있습니다. 저도 텍스트뷰에서 한글 처리때문에(네임태그관련) 꽤 애를 먹었었거든요. 혹시 도움이 될까 내용을 로그처럼 적어 드렸는데 지금 읽어보니 상당히 딱딱하게 읽히네요. 좋은 하루 되시길 바랍니다.

**Comment by drshawn** [comment]
1.8.9c
MacOS 10.12.1 (Sierra)
파이어폭스에서 같은 증상이 발생합니다. 사파리에서는 문제가 없네요.

**Comment by youknowone** [comment]
안녕하세요 개발자입니다. 모두 제보 감사드립니다. 이와 유사한 문제는 여러번 수정을 시도했으나 지금은 수정을 포기한 상태에 가깝습니다. 일반적으로 앱이 입력기의 동작 방식을 존중하지 않고 동작하는 경우로 생각이 됩니다. 애플 입력기는 동작 방식을 한번 바꾸면서 이런 경우에 정상동작을 하게 되었는데, (대신 다른 부분이 망가졌죠...) 어떻게 해야 비슷하게 구현할 수 있나 알 수가 없는 상황입니다. 불편을 드려 죄송합니다 🙇

**Comment by youknowone** [comment]
안녕하세요. 1.9.0 이후부터 내장 자판전환 버튼을 기본기능에서 제거합니다.
대신 시스템 단축키 사용에 관한 안내를 추가했습니다.
