### ISSUE TITLE
하이 시에라 세벌식 390 모아치기가 작동이 안돼요

### ISSUE THREAD

**Issue by Jeminaa** [gureum/gureum#233]
세벌식 390은 문제없이 되는데 390 모아치기는 설정에 놓아도 영어만 입력되네요
환경은 하이시에라, 맥북프로 15인치 2017년도 모델이예용
좋은 입력이 개발해주셔서 감사합니다

**Comment by grammaright** [comment]
세벌식 390 뿐만아니라 2011, 2012, Final 전부 동작하지 않고 영어로 입력되는 것 같습니다.

**Comment by ksyoon70** [comment]
저도 동일합니다. 하이시에라에서 한영 전환이 안됩니다. (맥북프로, 아이맥)

**Comment by baekkyoungjung** [comment]
업데이트 이후에.. 갑자기.. 저도 안됩니다.  ㅜㅜ 불편해 죽겠네요 ㅜㅜ 새삼 구름입력기의 소중함을 다시 한번 느끼는 하루네요..

**Comment by mollax** [comment]
저도 동일한 이슈입니다.
혹시나 해서 와 봤더니 동일 문제인 분들이 계시는군요. : )

**Comment by youknowone** [comment]
한글 자판을 정비한 다음 버전이 업데이트 예정입니다. 이전과 달라진 점은, 모아치기 사용을 위해서는 환경설정에서 모아치기 설정을 켜 주셔야 합니다. 기본으로는 꺼져 있습니다. 테스트버전은 다음 링크에서 받아보실 수 있습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1
