### ISSUE TITLE
Excel 엑셀에서 한글 입력이 아예 안 됩니다.

### ISSUE THREAD

**Issue by leoleec** [gureum/gureum#237]
구름입력기 1.8.9c 입니다.
macOS 10.13.2 (하이시에라)이고,
MS office 2016 for mac 최신버전으로 업데이트까지 되있는 상태인데요.

어느날부터 갑자기 한글 입력이 아예 안됩니다. 어떤 상황에서도 강제로 Qwerty 키보드로 전환됩니다.
바로 입력해서도 안 써지고요.
F2키(또는 ctrl+U)를 눌러서 셀에 커서를 띄우고 써봐도 안되고요.
직접 수식입력줄에서 마우스로 커서를 한번 직접 찍어준 이후에만 한글이 입력됩니다.

바쁘고 힘드실텐데 버그만 알려드리네요. 죄송할 따름입니다 ㅠㅠ

**Comment by youknowone** [comment]
현재 Mojave에서 최신버전(1.10.0)으로 엑셀 16.26에서는 문제가 없어 보입니다.
혹시 문제가 지속되면 다시 알려주세요
