### ISSUE TITLE
하이씨에라에서 'esc 키로 로마자 자판으로 변환' 옵션을 기본으로 켜서 실행할수 있을까요?

### ISSUE THREAD

**Issue by neocoin** [gureum/gureum#238]
구름 입력기를 감사하게 사용하고 있습니다. 

그간 vim 사용시 esc 키로 로마자 전환을 유용하게 사용하였습니다. 
그런데 최근 하이 씨에라로 업데이트를 하면서 환경설정에 진입을못해서 해당 기능을 사용하지 못하게 되었는데요.

혹시 콘솔에서 기본값을 변경시켜서 킬수 있는 방법이 있을까요? 
패키징된 바이너리에 포함된 기본 설정을 수정하는 방법이 있는지 문의 드립니다. 

(다행히도 1.8.9c 가 현재 환경에서 문제없이 동작하고 있습니다. )

**Comment by khwon** [comment]
1.9.0에서는 `defaults write org.youknowone.inputmethod.Gureum CIMRomanModeByEscapeKey YES`로 되는데 1.8.9c도 동일하지 않을까 싶네요

**Comment by youknowone** [comment]
환경설정을 새로 만든 버전이 업데이트될 예정입니다. 테스트버전은 다음 링크에서 받아보실 수 있습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1
