### ISSUE TITLE
Caps lock을 이용한 언어 변경

### ISSUE THREAD

**Issue by ilkyu95** [gureum/gureum#239]
macos에 capslock을 언어 전환 키로 사용할 수 있어서 편리해졌는데요,
구름 입력기에서는 capslock이 어쩐 일인지 막혀 있어서 (편집수정: capslock으로 한영전환이 안됨) 사용할 수가 없습니다.
사용할 수 있게 해주세요~~

**Comment by azaraks2** [comment]
Karabiner-elements에서 f20 같은걸로 스왑하고 잡으면 잘 됩니다.

**Comment by azaraks2** [comment]
키맵핑 툴이고 임시방편입니다. 구름 고쳐질떄까지 쓰시면 좋을것 같아서요.

**Comment by ilkyu95** [comment]
아, F20으로 맵핑하고 키보드 변환 shortcut을 F20으로 하라는 말씀이시군요.
말씀하신대로 해서 (F20은 왠지 안돼고 F19는 되는군요) 잘 설정하였습니다.
단지 무선 키보드에서 capslock 기능을 할당할 키가 없는 게 아쉽군요.
감사합니다.

**Comment by youknowone** [comment]
다음 버전에 꼭 내장하고 싶은 기능입니다. 제안 감사합니다.

**Comment by youknowone** [comment]
https://stackoverflow.com/questions/4752427/osx-detect-system-wide-keydown-events

**Comment by youknowone** [comment]
https://gist.github.com/youknowone/46b47c34d2ee49c5c012e0ac6bde1449

**Comment by youknowone** [comment]
https://superuser.com/questions/285103/is-it-possible-to-control-the-caps-lock-led-on-os-x

**Comment by youknowone** [comment]
https://apple.stackexchange.com/questions/256342/use-caps-lock-to-switch-to-and-from-languages-on-sierra

**Comment by youknowone** [comment]
https://developer.apple.com/library/archive/technotes/tn2450/_index.html

**Comment by yous** [comment]
- Using IOHIDManager to Get Modifier Key Events https://stackoverflow.com/questions/7190852/using-iohidmanager-to-get-modifier-key-events
- HID Class Device Interface Guide - Accessing a HID Device https://developer.apple.com/library/archive/documentation/DeviceDrivers/Conceptual/HID/new_api_10_5/tn2187.html#//apple_ref/doc/uid/TP40000970-CH214-SW2

위의 자료를 기반으로 캡스락 pressed 상태 이벤트를 받는 샘플 구현을 남겨둡니다. https://github.com/yous/gureum/commit/424047ba1123c6651d268136890f17b794ef9558

**Comment by youknowone** [comment]
다음 버전에서 이 기능이 추가됩니다. 테스트버전은 다음 링크에서 받아보실 수 있습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1
