### ISSUE TITLE
[요청]Blender 라는 3D 제작툴 한글 입력기가 필요해요...

### ISSUE THREAD

**Issue by echoseok** [gureum/gureum#240]
안녕하세요? 이쪽으로는 전혀 문외한입니다.
그래서 도움을 구하고자 합니다. GNU GP라이센스로 배포 개발중인
blender라는 프로그램이 있는데...
한글 입력이 되지 않습니다. 외국프로그램이려니 하고 편법으로 한글입력을 하고 있지만..
여간 불편한 것이 아닙니다. 혹시 도움을 주실 수 있을까요?

http://www.blender.org

**Comment by youknowone** [comment]
안녕하세요. 말씀대로 소프트웨어 제작시 입력기를 고려하지 않으면 한글입력이 정상적으로 동작하지 않는 경우가 있습니다. blender에서 문제를 해결해주어야 할 것으로 보이는데요. 구름이 아닌 기본 입력기에서도 한글 입력이 되지 않는다면 해당 내용을 바탕으로 blender쪽에 문의를 하시는 편이 좋을것 같습니다.
