### ISSUE TITLE
1.9.0c, 대다수의 세벌식 자판 배열이 작동하지 않습니다.

### ISSUE THREAD

**Issue by ParanScreen** [gureum/gureum#241]
입력 소스 선택 상태에서 한글 대신 로마자가 입력:

- 세벌식 최종 (종성결합허용)
- 세벌식 390 (종성결합허용)
- 세벌식 2011 
- 세벌식 2012
- 세벌식 모아치기 2015
- 세벌식 2015
- 세벌식 2011 (종성결합허용) 
- 세벌식 2012 (종성결합허용)
- 안마태

입력 소스의 작동에 문제:

- 세벌식 옛글 (작동하는 것처럼 보이지만 오토마타에 문제가 있음)

**Comment by yous** [comment]
모하비에서도 동일한 문제가 발생합니다.

**Comment by yous** [comment]
현재 버전의 구름 입력기에서 사용하는 libhangul에서 해당 자판의 지원이 빠진 것으로 보입니다. 3-2011, 3-2012 자판을 다시 추가하는 PR을 만들었습니다. https://github.com/gureum/libhangul/pull/13

**Comment by youknowone** [comment]
다음 버전에서 종성결합허용은 옵션으로 추가되고 망가진 자판이 복구됩니다. 옛글은 여전히 문제가 있는데 별도로 수정해야 합니다 #55 

테스트버전은 다음 링크에서 받아보실 수 있습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1
