### ISSUE TITLE
구름입력기 업데이트 확인 창이 자꾸 떠서 입력을 방해 합니다

### ISSUE THREAD

**Issue by hanhwe-kim** [gureum/gureum#244]
구름입력기 업테이트 창을 안뜨게 설정 할 수가 있었으면 합니다.

재부팅을 했어도 이전에 이미 확인을 하였으면 안떠도 되는데 입력을 하던중에 창이 떠서 입력을 방해 하고 오타를 유발하고 오작동으로 인하여 피해를 입은 적도 있습니다. 

가능한 빨리 시정을 하여 주시기 바랍니다.

![screen shot 2018-03-28 at 9 20 59 pm](https://user-images.githubusercontent.com/35706629/38069955-fa8769a2-32cd-11e8-87c5-42e25aede4a5.png)

**Comment by EugeneChung** [comment]
저도 이거 얼른 고쳤으면 좋겠어요~~

**Comment by pighair** [comment]
저도 마찬가지입니다. 알림을 무시하고 그대로 써도 된다는데 알림이 종종 계속 뜨니까 너무 불편합니다.

**Comment by hanhwe-kim** [comment]
어떻게 하다보니 현재 1.8.9c 버전을 설치했더니 업데이트 알림창이 자꾸 뜨는 문제는 없는 것 같네요.

**Comment by pighair** [comment]
저의 경우는 1.8.9c를 다운받아서 설치했는데 1.9.0이 유지되고 있어서 해결이 안 되네요.

**Comment by hanhwe-kim** [comment]
@pighair 님, 혹시 Macintosh HD/Applications/Library/Input Methods 폴더에 있는 Gureum.app을 쓰레기통에 버리고 1.8.9c를 다운 받으셨나요?

여기 숨어있는 Gureum.app 파일 정보(File Info) 를 한번 보시고 만일 1.9.0라고 나오면 그 파일을 버리고 다시 설치를 해보세요.
![screen shot 2018-07-01 at 4 10 29 pm](https://user-images.githubusercontent.com/35706629/42139789-c5cd8b58-7d49-11e8-820a-6ebb6687ce3b.png)

**Comment by pighair** [comment]
<img width="420" alt="2018-07-02_09-02-32" src="https://user-images.githubusercontent.com/18534209/42140204-ac8b3f9a-7dd6-11e8-80a5-bccf0d5bab73.png">
입력소스에서 뺐는데도 삭제가 안되는 걸 보니 로그아웃했다 다시 로그인해서 지우든가 해야겠네요... 말씀해주신 대로 하면 될 것 같습니다! 감사합니다~

**Comment by youknowone** [comment]
다음 버전부터 자동으로 뜨는 업데이트 확인 창이 사라집니다
