### ISSUE TITLE
구름 입력기 입력할 때 밑에 뜨는 바

### ISSUE THREAD

**Issue by pcr910303** [gureum/gureum#245]
하이 시에라, 구름 입력기 1.9.0 입니다. 잘 쓰고 있는데요, 기본 입력기는 한글을 쓸 때 한글 밑에 바가 안뜨는데 구름 입력기는 밑에 바가 뜹니다. 처음 구름입력기를 쓰는 사람으로써 너무 거슬리는데, 혹시 없앨 수 있는 방법 없나요?

**Comment by pcr910303** [comment]
아... 하루 이상 써보니까 이 바의 문제점을 더 자세히 알게 됬네요. 스팟라이트 같이 실시간 검색이 되는 모든 검색창에서 바가 들어가 있는 글자는 아예 인풋으로 인식을 안해주네요. 예를 들어서 제가 스팟라이트에서 `추출'을 검색하려고 했어요, 근데 스팟라이트에다가 추출을 치면 `출'에 바가 그어져 있어가지고 실시간으로 추출에 대해 검색이 되지 않고, 마우스로 클릭을 하거나 스페이스 바 등 수동으로 바에서 커서를 빼줘야 `추' 검색 결과에서 `추출' 검색 결과로 넘어가요. 이게 스팟라이트나 사전 같은데서 (특히 키보드를 사용해서 많은 일을 처리하려고 할때) 되게 불편해요;; 이 문제를 조속히 해결해 주셨으면 합니다.

**Comment by youknowone** [comment]
안녕하세요. 자세한 리포트 감사합니다. 말씀하시는 밑줄 문제는 조합중인 글자에 대한 표시인데요. OS에서 붙이는거라 쉽게 없애지는 못할것 같습니다. (기본 입력기와 구름 입력기의 구현 방식이 좀 다른데, 어떤 식으로 동작하는지는 이해하고 있지만, 구름을 그렇게 만들려면 어떻게 해야하는지를 잘 모르는 상황입니다. 제가 관련된 자료를 갖고 있지 않습니다)

말씀하신 문제는 스팟라이트와 사전에서 재현해보았는데, 스팟라이트에서는 문제가 없어서 동작 지연을 오인하신게 아닌가 싶고, 사전에서는 문제 발생을 확인했습니다.
