### ISSUE TITLE
구름 입력기에서 한자가 안쳐집니다.

### ISSUE THREAD

**Issue by readingsnail** [gureum/gureum#247]
하이 시에라로 인해 1.9.0을 사용중인데 한자를 치려고 Option-Enter를 누르면 글이 지워지면서 업데이트 확인글이 나옵니다.

한자를 쳐야 할 일이 있는데, 업데이트 확인만 주구장창 뜨는 일이 발생하네요... 그래서 macOS 의 기본 한글셋으로 전환하고 넣었습니다.

<img width="504" alt="2018-05-18 2 54 13" src="https://user-images.githubusercontent.com/1904967/40218230-5bec1d00-5aab-11e8-82e1-f300ed9e68de.png">

**Comment by youknowone** [comment]
#261 다음 버전에서 한자 관련 이슈를 해결합니다
