### ISSUE TITLE
단축키 설정을 초기화 할 수가 없어요(한영 전환 안됨)

### ISSUE THREAD

**Issue by abcchoco** [gureum/gureum#248]
한영전환 단축키가 먹히지 않는데, 단축키 설정을 삭제/수정할 수도 없어요.
왜일까요?

기본 캡스락으로도, 단축키인 쉬프트 스페이스로도 한영 전환이 안 됩니다.
단축키 설정을 초기화하려 해도 적용을 누르고 이동하면 이전 설정 상태로 되돌아갑니다.
이에스씨로 로마자 자판 전환도 안 되구요.
임시방편으로 키보드 설정에서 입력소스 선택을 체크 해제해 봤지만 여전히 캡스락이 작동하지 않습니다.

왜 이럴까요? 시에라를 사용하고 있습니다.

2. 구름입력기를 삭제하고 다시 깔아도 제가 해놓은 설정이 남아 있네요. 완전히 지우고 깔 방법이 없을까요?

**Comment by yous** [comment]
이전 버전 구름 입력기를 사용해서 단축키 설정을 한 경우 `~/Library/Preferences/org.youknowone.inputmethod.Gureum.plist`에 보시면 `CIMInputModeExchangeKeyModifier` 항목이 있습니다. 해당 `<key>`와 `<integer>` 부분을 삭제한 후 다시 사용해보세요. 제 경우 이전에 Shift + Control + Option + Command + Space로 설정해둬서 아래와 같이 저장되어 있습니다. 해당 숫자의 의미는 다음 링크를 참고하세요. <https://stackoverflow.com/q/21878482/3108885>

``` plist
<key>CIMInputModeExchangeKeyModifier</key>
<integer>1966080</integer>
```

**Comment by youknowone** [comment]
환경 설정을 새로 만든 버전이 업데이트 될 예정입니다. 테스트버전은 다음 링크에서 받아보실 수 있습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1
