### ISSUE TITLE
에버노트에서 사용시 자음분리 현상

### ISSUE THREAD

**Issue by gruming** [gureum/gureum#249]
제 사양은 

맥북프로 High Sierra v10.13.5 를 사용중이고 

구름입력기는 v1.8.9c 을 사용 하고 있습니다.

현상은 에버노트에서 일반적으로 작성을 할 때는 문제가 없지만

글머리 기호 기능이나 번호매기기 목록을 사용할 때 자음 분리가 나타나네요~

아래 현상을 첨부합니다

혹시 해결방법이 있으면 알려주시면 감사할게요~

![ScreenShot](https://im2.ezgif.com/tmp/ezgif-2-bb9700fa1f.gif)

ps: 에버노트에서만 이러한 현상이 나타나니 에버노트에 문의를 해야 되는건가요~? ㅠ
그리고 에버노트 이외에서는 잘 사용하고 있습니다 ^^/

**Comment by ghatdev** [comment]
quiver 라는 앱에서도 같은증상이 발생하는것 같습니다.

**Comment by ritter4u** [comment]
spark 라는 메일툴과 firefox 주소창 에서도 같은 증상으로 자소분리가 나타납니다

**Comment by youknowone** [comment]
최신 버전인 [1.10.1](https://github.com/gureum/gureum/releases/tag/1.10.1)과 에버노트 앱스토어 최신버전에서 테스트해 보았는데, 재현되지 않는것 처럼 보입니다.

@gruming  스크린샷 링크가 깨져있어 자세한 확인이 어려운데, 정상적으로 수정되었는지 확인 가능할까요?

@ghatdev quiver는 상용 소프트웨어여서 확인하지 못했습니다. 문제 여전히 발생하는지 확인 가능할까요?

**Comment by ghatdev** [comment]
@youknowone 기존 자음분리현상은 해결된 듯 보이나 스페이스바와 엔터키가 정상 작동하지 않는듯 보입니다(무시되는듯 합니다.즉 두번 스페이스 쳐야 한번으로 인식)
맥 내장 두벌식 자판에서는 문제없음이 확인되었습니다.

**Comment by gruming** [comment]
@youknowone 죄송합니다 답변이 엄청 늦었네요 제가 지금은 에버노트를 사용하지 않고 있어서 그냥 지나쳐버렸네요 ㅠ
에버노트 설치 후 1.10.1 버전에서 확인 해보니 제가 올린 증상은 나타나지 않습니다.
감사합니다.
