### ISSUE TITLE
모하비에서의 오류

### ISSUE THREAD

**Issue by riple12** [gureum/gureum#250]
가끔씩 사파리 입력창에서 구름입력기가 작동하지 않는 경우가 있습니다. 주로 잠자기 해놓고 다시 켜서 사용할 때 일어나는 현상 같습니다.

**Comment by youknowone** [comment]
베타버전에서 잠자기 관련 문제는 베타8에서 수정되었습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre8

#438
