### ISSUE TITLE
JIS 자판에 관한 부탁

### ISSUE THREAD

**Issue by minority25** [gureum/gureum#260]
안녕하세요.
한국어입력 상태에서의 단축키 입력이 필요해서 구름입력기를 잘 쓰고 있습니다.
한가지 저에게 큰 문제가 있는데요,
제가 일본인이라 일본 JIS키보드를 사용하고 있는데, 구름입력기의 기호배열이 JIS키보드와 전혀 맞지 않습니다.
윈도우 표준 한구어 키보드는 JIS키보드에 대응되고 있어 아래와 같이 입력이 가능한데요.

<img width="1181" alt="jis1" src="https://user-images.githubusercontent.com/42452851/44237781-cb4d6180-a1ec-11e8-8425-a26c26efcbb9.png">

Shift를 누른 상태
<img width="1178" alt="jis2" src="https://user-images.githubusercontent.com/42452851/44237786-d0121580-a1ec-11e8-903b-f6508c2a0272.png">

구름입력기는 이 키보드에 맞게 기호가 안나와 글자판 각인과 다른 기호가 나오므로 굉장히 불편합니다.
JIS키보드에 맞는 자판배열도 만들어주시면 안될까요?

**Comment by youknowone** [comment]
#526 을 활용해서 해결 가능한지 검토해 보겠습니다

**Comment by soomtong** [comment]
Rel. #130

**Comment by youknowone** [comment]
새 버전에 시스템 자판 설정할수 있는 기능이 들어갔는데, JIS키보드에서 쓰는 값으로 넣으면 될것 같습니다. 확인해보지 않아 수정되었나 확인하는데 어려움이 있으니 혹시 문제가 재현되면 다시 열어 주세요.

https://github.com/gureum/gureum/releases/tag/1.11.1

**Comment by fball00n** [comment]
시스템 자판 설정은 가능합니다만, 선택지에 JIS가 없습니다. 추가가 필요한 듯 합니다.

**Comment by kentakang** [comment]
@youknowone 

![Screenshot 2024-03-17 at 15 48 29](https://github.com/gureum/gureum/assets/11825619/f76a9ae4-e03a-4534-9095-e65c96a67a0d)

혹시 시스템 설정이 위 설정인가요?

해당 옵션으로 설정 시 로마자에서는 정상 동작하지만, 한글 입력기 상태에서는 특수문자 배열이 쿼티 기본 배열로 돌아가서 일관성이 없는 문제가 있습니다.
