### ISSUE TITLE
구름 2018 릴리즈

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#261]
기능 복구
- [x] 한자 입력 단축키 복구
- [x] 한/영 전환 단축키 복구
- [x] preference pane 개발

기능 추가
- [x] capslock on일 때 영문 입력 모드 (환경설정) #199 #239
- [x] dvorak/colemak 지원
- [x] 이모티콘 입력기

버그 수정
- [x] #39
- [x] #170 

배포 체크리스트
- [ ] Preferences에 동작하지 않는 기능이 없어야 함
- [ ] 두벌식, 세벌식최종, 세벌식390 지원
- [ ] 지원하지 않는 자판 제거
- [ ] 한자 입력 기능이 크래시 없이 동작

**Comment by ghatdev** [comment]
언제쯤 업데이트될지 혹시 알수잇을까요?

**Comment by soomtong** [comment]
한/영 전환 단축키에 CapsLock 바인딩 가능하면 좋겠어요. 카라바이너를 사용해 캡스락으로 토글 하는데 나름 편해요. 애플이 이러는(공식 자판 토클에 캡스락을 사용한) 이유가 있는 것 같아요 ―ㅅ―

**Comment by soomtong** [comment]
에모지 입력기는 여기를 참고하셔도 좋을 것 같습니다.
https://github.com/mzp/EmojiIM

**Comment by youknowone** [comment]
caps lock: https://github.com/unofficial-opensource-apple/IOKitUser

**Comment by solidsnake33** [comment]
이곳에 적어도 되는 문제인지는 모르겠습니다만 안마태 자판 등 일부 자판이 작동하지 않고 영문으로 나오는 부분도 이번에 해결되었으면 좋겠습니다.

**Comment by youknowone** [comment]
베타 배포했습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1

@solidsnake33 안마태 자판도 수정되었습니다
