### ISSUE TITLE
채움 문자 관련

### ISSUE THREAD

**Issue by pighair** [gureum/gureum#318]
초성 없이 모음과 종성만 입력할 경우 아래와 같이 표시되고 커서의 위치가 이상해져서 bs나 del로 편집할 때 애로가 생깁니다.

ㅏ+ㄹ: ᅟᅡᆯ
ㅕ+ㄴ: ᅟᅧᆫ
ㅗ+ㄱ: ᅟᅩᆨ

환경설정에서 한글 탭 고급 설정에 미완성 문자 조합 옵션을 둘 다 '채움 문자 제거'로 설정하면 HFC라고 표시된 글자는 안 나타납니다만 ᅧᆫ 부분이 한 글자로 인식되는데 이건 정상인가요? HFC라고 표시된 글자가 혹시 다른 분께는 그렇게 안 보일까봐 위에 입력한 부분을 캡쳐하여 첨부합니다.

<img width="90" alt="2018-09-19_00-12-04" src="https://user-images.githubusercontent.com/18534209/45697403-b6c00880-bba0-11e8-8f8f-da7ee65b801f.png">

**Comment by youknowone** [comment]
현재 master 버전에서는 채움문자 관련 설정이 제거되었습니다. 한글자로 인식되는건 수정해 보려 합니다.

**Comment by kth2624** [comment]
// ㄱ~ㅎ.  한글호환자모 : 한글자모 
Let table=[0x3131: 0x1100, 0x3132: 0x1101, 0x3134: 0x1103, 0x3137: 0x1104, 0x3138: 0x1105, 0x3139: 0x1106, 0x3141: 0x1107, 0x3142: 0x1108, 0x3143: 0x1109, 0x3145: 0x110A, 0x3146: 0x110B, 0x3147: 0x110C, 0x3148: 0x110D, 0x3149: 0x110E, 0x314a: 0x110F, 0x314b: 0x1110, 0x314c, 0x314d: 0x1111, 0x314e: 0x1112]

**Comment by kth2624** [comment]
0x0000: 0x0000, 0x11A8 :0x3131, 0x11A9 :0x3132, 0x11AA :0x3133, 0x11AB :0x3134, 0x11AC:0x3135, 0x11AD:0x3136, 0x11AE:0x3137,  0x11AF:0x3139, 0x11B0:0x313a,  0x11B1:0x313b,  0x11B2:0x313c,  0x11B3:0x313d, 0x11B4:0x313e,  0x11B5:0x313f, 0x11B6:0x3140,  0x11B7:0x3141, 0x11B8:0x3142,  0x11B9:0x3144, 0x11BA:0x3145, 0x11BB:0x3146,  0x11BC:0x3147,  0x11BD:0x3148,  0x11BE:0x314a, 0x11BF:0x314b,  0x11C0:0x314c,  0x11C1:0x314d, 0x11C2:0x314e

**Comment by yous** [comment]
#456

**Comment by youknowone** [comment]
이 문제를 수정한 1.9.0 베타2가 배포되었습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre2
