### ISSUE TITLE
테스트 실행시 IMKServer 초기화 실패

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#355]
시스템에 이미 구름이 떠 있는 경우 새 서버 초기화에 실패합니다.

실제 구름과 테스트가 다른 connection name을 쓰게 해야할듯

**Comment by yous** [comment]
https://github.com/gureum/gureum/commit/44a43dd2cc09b68b06e847572708127f73607e4d

**Comment by yous** [comment]
#481
