### ISSUE TITLE
한자 후보 방향 키로 전환했을 때 crash

### ISSUE THREAD

**Issue by dorururu** [gureum/gureum#359]
[Gureum_2018-10-05-222249_hyewon-ui-MacBook-Pro.crash.zip](https://github.com/gureum/gureum/files/2450473/Gureum_2018-10-05-222249_hyewon-ui-MacBook-Pro.crash.zip)

**Comment by dorururu** [comment]
[Gureum_2018-10-05-222249_hyewon-ui-MacBook-Pro.crash.zip](https://github.com/gureum/gureum/files/2453743/Gureum_2018-10-05-222249_hyewon-ui-MacBook-Pro.crash.zip)

**Comment by youknowone** [comment]
크래시 리포트를 보니 한자 합성기가 아닌 한글 합성기로 전환된 후 후보선택을 시도해서 난 오류여서, 한자 합성기를 종료할때 후보 창을 제대로 닫으면 해결될 문제 같네요.

**Comment by youknowone** [comment]
#213
