### ISSUE TITLE
Preference 창에서 글자가 겹쳐서 보이는 문제

### ISSUE THREAD

**Issue by JimJeon** [gureum/gureum#379]
<img width="780" alt="screen shot 2018-10-14 at 5 31 13 pm" src="https://user-images.githubusercontent.com/16199830/46914366-435eba80-cfd7-11e8-969c-0e6b97c3c864.png">

MacOS 10.14 Mojave 사용하고 있습니다.
위처럼 ```캡스락으로 자판 전환```과 ```기본 한글 자판```이 겹쳐서 보이고 있습니다.

**Comment by youknowone** [comment]
#382 머지로 수정되었나 확인해 주실수 있으세요?

**Comment by tobark** [comment]
이 이슈는 #382 에서 해결되었으므로 닫혀야 합니다.
