### ISSUE TITLE
사파리 주소창에서 입력중인 글자 사라지는 문제

### ISSUE THREAD

**Issue by loliiilol** [gureum/gureum#384]
1.8.9c 버전 사용중입니다.
모하비에서도 나타나는 문제지만 그 이전 버전들에서도 동일하게 나타난 문제입니다.
사파리 주소창에 입력할 경우, 입력하는하는대로 추천 검색어가 주소창 아래에 나열되는 과정에서
입력중인 글자 혹은 마지막 글자가 사라지는 문제가 있습니다.
구체적으로는 입력이 완료되지 않은, 글자 아래 언더바가 있는 상태의 글자가 없어집니다.
예를 들어 주소창에 '네이버' 입력하면 '네이'만 남으면서 아래에 추천 사이트가 나옵니다.
보다 긴 문장이나 단어의 경우 입력 중간에 추천 검색어/사이트가 나열되면서
나열되는 순간의 입력 중인 글자(언더바가 있는 글자)가 없어집니다.
추천 검색어/사이트가 뜨기 전에 스페이스 키 등으로 입력을 완료하면 되지만 여간 불편한게 아닙니다 ㅠㅠ
개발자님들 이 문제 꼭 좀 없애주세요 ㅠㅠ

**Comment by youknowone** [comment]
모하비에서 최신 구름(1.10.0) 사용시 문제가 없는 것으로 보입니다.
구름이 고친 건 아닌것 같은데, 혹시 문제가 재발하면 알려주세요.
