### ISSUE TITLE
환경설정에 한글입력기 옵션 추가

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#388]
libhangul에서 몇몇 기능이 옵션으로 추가됨

hangul_ic_set_option

- HANGUL_IC_OPTION_AUTO_REORDER: 순서 교정 기능. "모아치기" 기능으로 체크박스 추가
- HANGUL_IC_OPTION_COMBI_ON_DOUBLE_STROKE: 두벌식에서 초성 연달아 쳐서 조합해주는 기능 (ㄱㄱ-> ㄲ)
- HANGUL_IC_OPTION_NON_CHOSEONG_COMBI: ㄱㅅ -> ᅩᆪ 등을 해주는 기능 (MS윈도 호환)

**Comment by yous** [comment]
#403

**Comment by youknowone** [comment]
#406

**Comment by youknowone** [comment]
HANGUL_IC_OPTION_COMBI_ON_DOUBLE_STROKE 는 구현하지 않고 닫습니다
