### ISSUE TITLE
Preferences warnings

### ISSUE THREAD

**Issue by yous** [gureum/gureum#397]
다음 빌드 경고가 발생합니다.
- Attribute Unavailable
  - Detaches Hidden Views before OS 10.11
  - Distribution before OS X 10.11

https://forums.developer.apple.com/thread/88447

StackView를 사용하면서 생기는 문제인 것 같은데, 10.10을 지원하려면 constraint나 priority 등의 조정이 필요할 것 같습니다.

**Comment by youknowone** [comment]
High Sierra 이전 버전에서는 현재 버전의 환경설정이 지원되지 않으므로 구름의 최소 버전 타겟을 10.13 으로 두면 될것 같습니다
