### ISSUE TITLE
환경설정에서 스크롤바가 이중으로 뜨는 문제

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#414]
<img width="780" alt="2018-10-27 1 16 53" src="https://user-images.githubusercontent.com/69878/47599516-b3fbd300-d9ea-11e8-8c7e-067c2f2c3f6e.png">

**Comment by yous** [comment]
height이 300으로 고정되어 있다 보니 자판을 추가, 제거함에 따라 높이가 변하면서 스크롤바가 생기거나, 아랫 부분이 잘린 것처럼 보이는 것 같습니다.
