### ISSUE TITLE
'Esc 키로 로마자 자판으로 전환(vi 모드)' 옵션이 작동하지 않습니다.

### ISSUE THREAD

**Issue by chacham** [gureum/gureum#423]
'Esc 키로 로마자 자판으로 전환(vi 모드)' 옵션이 작동하지 않습니다.
1.9 버전을 사용하다가 오늘 새 버전을 설치했는데 작동하지 않네요.
맥북 프로 13인치 2017 논터치바, 모하비 10.14 (18A391) 버전 사용중입니다.

---

좋은 입력기 만들어주셔서 정말 감사합니다 :D
VS Code에서 vim 확장 설치해서 사용중이었는데, 구름 입력기에서 esc 버튼으로 영어자판으로 넘어가는게 너무 편해서 계속 사용중입니다.
VS코드에서 한글 입력하다가 영어로 넘어가면 마지막 글자가 커서를 따라와서 불편했는데, 이번 버전에서는 깔끔하게 잘 되네요 고맙습니다~

**Comment by yous** [comment]
해당 문제를 #425 통해 해결했고, 이를 포함한 베타2 버전이 릴리스되었습니다.
https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre2
