### ISSUE TITLE
한영 전환시 캡스락 옵션 켜지는 버그

### ISSUE THREAD

**Issue by JaeungHyun** [gureum/gureum#424]
어떻게 이 버그가 나오는지 모르겠지만

한영전환 하다보면 캡스락이 켜지네요

**Comment by youknowone** [comment]
이전 베타에서 발생하던 문제이고 안정버전/최신베타에서는 해결되었습니다

**Comment by JaeungHyun** [comment]
최신 버전을 써봐야겠네요

**Comment by youknowone** [comment]
최신 베타 배포입니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre8
