### ISSUE TITLE
이모티콘 db에 자주 쓰는 특수문자 추가

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#427]
- apple logo
- shift, command, option 등의 기호로 쓰이는 기호에 alias 추가
- 에모지 db엔 없지만 널리 알려진 다른 alias 추가

기존의 emoji generator: https://github.com/gureum/gureum/blob/master/OSX/data/hanja/generate_emoji.py

1. 같은 포맷으로 이모티콘 db 만드는 파이썬 코드 추가
2. 데이터 추가 (참조할 데이터 있나 확인)

**Comment by kla0629** [comment]
Apple logo

**Comment by yous** [comment]
#452
