### ISSUE TITLE
Han 3Set Final No Shift(Gureum)에서 쌍따움표 

### ISSUE THREAD

**Issue by nowage** [gureum/gureum#428]
제가 못찾었을 수도 있는데, 아무리 찾아도 없네요. 
당장은 DashApp에서 자동완성 기능으로 쓰고 있는데 추가해 주시면 감사하겠습니다.

**Comment by youknowone** [comment]
qwerty 호환으로 Shift+ㅌ 자리에 배정하는게 의도인데 안들어가있네요. 수정하겠습니다.

**Comment by nowage** [comment]
감사합니다.^^
