### ISSUE TITLE
테스트를 Swift로 포트

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#432]
- objc 테스트: https://github.com/gureum/gureum/blob/master/GureumTests/GureumObjCTests.m
- swift 테스트: https://github.com/gureum/gureum/blob/master/GureumTests/GureumTests.swift

옮기는 예시: (보충 예정)

**Comment by tkdqlsii** [comment]
testCommandkeyAndControlkey

**Comment by m1nari** [comment]
testCapslockRoman

**Comment by tkdqlsii** [comment]
testColemak

**Comment by m2bi** [comment]
(void)testHanjaSelection

**Comment by sdp1422** [comment]
testHanjaSelection

**Comment by jinmay** [comment]
testDvorak

**Comment by tkdqlsii** [comment]
> testColemak

**Comment by yous** [comment]
- #443 (`testDvorak`)
- #444 (`test3Number`, `testBlock`, `test3final`)
- #447 (`testCapslockRoman`)
- #453 (`testHanjaSelection`)
- #457 (`testColemak`, `test2`, `testCapslockHangul`, `testRomanEmoticon`)
