### ISSUE TITLE
구름 1.10 기준으로 문서(위키) 업데이트

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#434]
현재 버전은 1.8~1.9 기준의 문서: https://github.com/gureum/gureum/wiki

1.10 업데이트 내역: https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1

**Comment by namehak** [comment]
저 환경설정이요

**Comment by jiyeopjang** [comment]
한자입력기 하겠습니다.

**Comment by wjswodnWkd** [comment]
저 한자 입력기 요

**Comment by MakeDroneMan** [comment]
저 디버그요 : )

**Comment by jung-taesoo** [comment]
직접빌드

**Comment by kangyejin** [comment]
구름 입력기요

**Comment by wjswodnWkd** [comment]
설치하기

**Comment by MakeDroneMan** [comment]
> 구름 입력기요

와우! 대단합니다!

**Comment by ptera21** [comment]
남은게 도움말이네요^^....

**Comment by MakeDroneMan** [comment]
패치노트에 디버그 항목 내용이 없는것같아요.
그래서 페이지만 일단 만들어 놓았습니다.
다른 항목 수정할게요😅

**Comment by ptera21** [comment]
> 남은게 도움말이네요^^....

도움말 업데이트 완료! 😄

**Comment by youknowone** [comment]
모두 수고하셨습니다 감사합니다!
