### ISSUE TITLE
Mac Os 잠자기에서 깨어날 때 CPU 99% 점유 하는 문제

### ISSUE THREAD

**Issue by samslow** [gureum/gureum#438]
Mac Os 잠자기에서 깨어날 때 CPU 99% 점유 하는 문제

이로인해 전체 버벅임 현상이 일어납니다.
문제를 찾지 못했었는데 '활성상태 보기'로 잠자기 직후(최소 5분 이후) 확인 해 보니 CPU를 이상적으로 많이 먹는 문제가 발견되었습니다.

**Comment by ghatdev** [comment]
같은 문제가 발생합니다

**Comment by bekker** [comment]
같은 문제 발생합니다~~
macOS 10.14.1입니다

![2018-12-06 6 05 30](https://user-images.githubusercontent.com/4366401/49573530-8a3ab200-f981-11e8-8a13-fe47b33a816c.png)

**Comment by youknowone** [comment]
저도 재현했습니다. 이번에  IOKit 을 쓰는 코드가 추가되었는데 이쪽이 좀 의심스러운 상황입니다

**Comment by synthresin** [comment]
저도 겪는 증상입니다.

**Comment by daejoon** [comment]
macOS 10.14.2, 구름 1.10.0-pre6에서 같은 증상 입니다.

**Comment by ssut** [comment]
macOS 10.14.4, 구름 1.10.0-pre6에서 동일 증상 발생합니다. 잠금 해제할 때마다 activity monitor에서 구름 입력기를 강제 종료하는 식으로 버벅임을 해결하고 있습니다.

**Comment by youknowone** [comment]
pre7에서 IOKit 관련 코드 수정후 문제가 사라지는 것을 확인했습니다. pre7엔 다른 버그가 많아서, 이 변경만 pre6으로 옮기고 다시 릴리즈하려고 합니다

**Comment by 1ilsang** [comment]
이 부분 pre6에 릴리즈 되어있나요?

**Comment by youknowone** [comment]
@1ilsang 아직 안되어 있습니다. 새로 수정한 버전은 pre8이 될 예정입니다

**Comment by youknowone** [comment]
베타8에서 수정되었습니다. https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre8

혹시 베타8에서도 재현되면 알려주세요
