### ISSUE TITLE
콜맥 배열

### ISSUE THREAD

**Issue by kiesel95kgh** [gureum/gureum#467]
콜맥 추가해주셔서 감사합니다^^
그런데 F, T와 K, M 등 일부 자리가 뒤바뀐 것 같습니다.

**Comment by youknowone** [comment]
베타8에 콜맥 배열 수정이 포함되었습니다.  @yous 님께서 수고해 주셨습니다

**Comment by youknowone** [comment]
https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre8
