### ISSUE TITLE
한자 입력 문제

### ISSUE THREAD

**Issue by dexion752** [gureum/gureum#480]
한자 입력을 위해 '옵션+엔터'를 누르면 대상 한글이 사라지는 현상이 발생합니다. 이전 버전에서는 한자 변환 목록은 떴으나 선택을 할 수 없는 에러가 있었는데 이번 버전에서는 대상 한글이 사라질 뿐 한자 변환 목록 전혀 뜨지 않습니다. 한자 변환을 실패한 다음에는 입력 소스가 한글임에도 영문자만 타이핑되는 에러도 함께 발생합니다. 입력 소스 선택에서 구름입력기의 입력 소스를 선택하면 팝업 메뉴에서 '구름 …. '으로 뜨는 것으로 보아선 한자 변환에 실패한 후에는 구름입력기가 죽는 것으로 보입니다.

시스템 환경: macOS 10.14.2
구름입력기 버전: pre-5, 쿼티/세벌식 390
오류 요약
1. 세벌식 390에서 한자 변환 시, 한자 변환 목록이 뜨지 않고 대상 한글은 삭제됨.
2. 실패 후, 구름입력기의 입력 소스가 한글이라고 하더라도 한글 입력이 되지 않음.

**Comment by xldesignjeju** [comment]
저는 디자이너다 보니 일러스트레이터에서 옵션 리턴으로 한자 입력이 안되서 구름입력기를 깔았는데.... 
비슷한 문제가 있습니다. 몇번 시도해보다가 실패하고 일단 지웠는데 ㅜㅜ
(하이시에라에 일러스트레이터CC입니다.) 검색해보다가 비슷한 문제가 있어서 댓글달게 되었습니다.

댓글다는 김에...   수고하시는 개발자분께도 감사드립니다. 모두 새해 복 많이 받으세요.

**Comment by youknowone** [comment]
한자 입력 문제가 수정된 새 베타가 배포되었습니다. https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre6

@xldesignjeju 원래의 이슈와 같은 이슈인지 일러스트레이터에 한정된 문제인지 모르겠네요. 업데이트 후에도 재발하면 새 이슈 부탁드립니다

**Comment by xldesignjeju** [comment]
감사합니다. 위 버전 깔고 일단 일러스트레이터에서 한자 입력은 성공했습니다.

제가 사용법을 잘모르는 것일 수도 있는데..... 일단 문제 나열해봅니다.

1.현재 한자입력하면 앞에 한글이 있는 채로 한자가 뒤이어 입력이 됩니다.
혹시 한글(한자) 또는 한자만 입력될수 있게 되는지요?

2.혹시 한자입력시 한자단어도 입력 가능하게 되는지요?

3.옵션 리턴으로 나오는 한자창(? 한자와 훈과 음이 나오는 곳...)에서 상하단 커서키가 제대로 안 먹어서
밑에 있는 한자를 선택하려면 마우스로 해야 합니다.

4.구름입력기에서는 캡스락키를 한/영 전환키로 사용할수 없는지요?

당장 해보고 바로 피드백 드리는데... 제가 사용법을 잘몰라 그럴 수도 있으니 이해바랍니다.


그리고 혹시 제가 잘몰라서 그러는데.... 
커피값 밥값이라도 지원하고픈데.... 혹시 지원 방법이 있으면 말씀해주세요. 감사합니다.
