### ISSUE TITLE
Caps Lock 전환이 켜져 있을 때 qwerty 자판 내 기존 Caps Lock 기능 동작 안함

### ISSUE THREAD

**Issue by itsmo1031** [gureum/gureum#483]
기본 입력기에서 Caps Lock 전환을 킬 경우 Caps Lock을 짧게 누르면 언어 전환, 살짝 길게 누르면 대/소문자 전환이 가능한데요
구름 입력기의 경우 언어 전환만 가능할 뿐 대소문자 전환은 동작하지 않네요.
추가되었으면 좋겠습니다!

**Comment by youknowone** [comment]
베타8에서 길게 눌러 대소문자 전환이 추가되었습니다. https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre8
