### ISSUE TITLE
한자 입력 문제

### ISSUE THREAD

**Issue by dexion752** [gureum/gureum#485]
안녕하세요. pre5에서 한자 입력 에러를 제보하였습니다. pre6에서 해결되기 바랐으나 한자 입력 문제가 완벽하게 해결되지 않아 다시 제보합니다. 이와 함께 vi 모드도 정확하게 동작하지 않습니다.

1. pre5에서와 달리 pre6에는 한자 변환 리스트는 나오기는 하는데 한자 변환 리스트에서 화살표로 포커스를 이동할 수 없을뿐더러 엔터를 눌러도 한자로 대치되지 않습니다. 
2. 설정에서 vi 모드를 선택하였습니다. vi(m)에서 esc를 누르면 입력 소스가 영문(쿼티)로 바뀌기는 하나 vim이 입력 모드에서 벗어나지 못합니다. 결국 노멀 또는 명령모드로 들어가기 위해서는 다시 한번 esc를 눌러야 합니다. 즉 esc를 두 번 눌러야 원하는 동작, 입력소스를 영문으로 바꾸고 노멀/명령모드로 진입이 이루어지더군요. esc를 한 번 눌러서 원하는 동작이 되면 좋겠습니다.
 
버그 리포트에 빠르게 대응해 주셔 다시 감사드립니다.

**Comment by yous** [comment]
#586, #621 PR을 통해 1번 문제는 어느 정도 해결될 것으로 보입니다.

**Comment by youknowone** [comment]
@yous 님께서 한자 후보 선택 키 관련 문제를 수정해 주셔서 새 실험버전을 배포하였습니다.
experimental4를 설치해 보시면 테스트해 보실 수 있습니다.
https://github.com/gureum/gureum/releases/tag/GureumKIM-1.11.0-experimental

**Comment by youknowone** [comment]
한자 후보 선택 관련 버그가 완전히 수정되었습니다 https://github.com/gureum/gureum/releases/tag/1.11.1
