### ISSUE TITLE
Programmer's Dvorak과 충돌

### ISSUE THREAD

**Issue by elbaro** [gureum/gureum#51]
Programmer's Dvorak은 기존 드보락에 숫자나 특수문자를 편하게 만든 배열입니다.
http://www.kaufmann.no/roland/dvorak/
그런데 구름 입력기와 사용시 저건 정상사용이 되는데 구름 입력기의 키 맵핑이 바뀌어 버립니다.
어느쪽이 문제인지 모르겠지만 구름입력기에서 해결되는 부분인지 한 번 확인 부탁드립니다.

**Comment by youknowone** [comment]
최신 베타에서 이 문제를 해결하였습니다. https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre9

**Comment by youknowone** [comment]
1.10이 정식으로 릴리즈되었습니다. 문제가 지속되면 다시 알려주세요

https://github.com/gureum/gureum/releases/1.10.0
