### ISSUE TITLE
Apple 제공앱에서 날짜형식 바뀌는 문제

### ISSUE THREAD

**Issue by 201901kim** [gureum/gureum#510]
<img width="191" alt="2019-01-25 am 10 09 59" src="https://user-images.githubusercontent.com/47016461/51718822-567b2f00-208a-11e9-81b6-02070547f93d.png">

구름입력기를 설치 하기 전에는 새로운 Event 를 생성할 때 yyyy.mm.dd 형식으로 생성되다가
구름입력기 설치 후에는 새로운 Event 생성시 dd-mm-yyyy 형식으로 바뀌네요

하이시에라 파이널버전이고
구름입력기는 현재 올라와있는 최신버전 pre7 을 설치했습니다 (이전버전에서도 같은 증상확인)
구름입력기 "두벌식" 을 사용합니다

제 맥북 문제인가 하고 포멧하고 새로 설치해보고, 아이맥에서도 테스트해봤는데
정확하게 구름입력기 설치 후에 다음과 같은 증상이 재현되네요

**Comment by youknowone** [comment]
이전 베타 버전에서는 기본 키보드 레이아웃으로 US를 사용했는데, 정식 릴리즈는 ABC로 바꾸었습니다.
구름 입력기가 로캘에 관여하는 부분은 이부분 뿐이라 아무래도 수정이 되었을것 같습니다.

파이널컷이 상용 소프트웨어여서 확인이 어려운데, 문제가 여전히 발생하는지 확인 부탁드립니다.

**Comment by youknowone** [comment]
새 버전에서 시스템 입력기를 ABC로 선택하면 수정될 것으로 생각됩니다.
https://github.com/gureum/gureum/releases/tag/1.11.1
