### ISSUE TITLE
쌍자음 중 쌍디귿 입력 불가

### ISSUE THREAD

**Issue by fightingmamoru** [gureum/gureum#511]
구름입력기를 감사하며 사용하고 있는 사용자 입니다.

다른 쌍자음 들은 잘 입력이 되는데 쌍디귿만 입력이 되지 않는 현상이 있어 남깁니다.
도움 부탁 드립니다.

**Comment by youknowone** [comment]
어떤 배열 사용하시는지 알 수 있을까요?

**Comment by fightingmamoru** [comment]
@youknowone 두벌식 배열 사용중 입니다. 키보든 입력소스는 구름입력기와 영문 배열 사용중입니다.

**Comment by youknowone** [comment]
최신 베타에서 재현 되는지 확인 부탁드려도 될까요? https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre8

**Comment by youknowone** [comment]
정식 릴리즈에서 재현되지 않으므로 닫습니다.
