### ISSUE TITLE
기본 한영전환(shift+space) 부활

### ISSUE THREAD

**Issue by xenzo** [gureum/gureum#513]
#215 , #433 현상 재발 문의 입니다.

**Comment by xenzo** [comment]
Gureum-1.10.0-pre7.pkg 설치 버전입니다.

**Comment by youknowone** [comment]
캡스락 전환에 다소 결함이 있어 기본 전환을 살렸다가 베타8에서 다시 죽였습니다

**Comment by youknowone** [comment]
https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre8
