### ISSUE TITLE
베타 7에서 세벌식 모아치기가 작동하지 않는 거 같습니다.

### ISSUE THREAD

**Issue by Frostydawn** [gureum/gureum#514]
모하비 10.14.3입니다. Gureum-1.10.0-pre7.pkg로 업데이트시 세벌식 모아치기가 작동하지 않습니다. Gureum-1.10.0-pre6.pkg으로 내리니 정상작동하구요. 확인 부탁드립니다.

그리고 맥 세벌식 유저들 유저들에게 가뭄의 단비같은 프로그램 감사드립니다.

**Comment by Frostydawn** [comment]
베타 8에서는 해결되었네요. 감사합니다.

**Comment by youknowone** [comment]
동작 확인해 주셔서 감사합니다!
