### ISSUE TITLE
맥북에서 화면을 덮었다가 다시 켜면 입력이 느립니다

### ISSUE THREAD

**Issue by ImBada** [gureum/gureum#520]
화면을 덮었다가 다시 켜면 입력이 엄청 느리게 작동합니다.
해당 현상은 영어 키보드 입력기로 전환 후 다시 구름으로 바꾸면 정상으로 돌아옵니다.
혹시 업데이트 확인 때문이면, 해당 기능을 켜고 끌 수 있는 옵션을 추가해도 좋지 않을까 싶습니다.

**Comment by youknowone** [comment]
#438 과 같은 이슈입니다

**Comment by ImBada** [comment]
Duplicate of #438
