### ISSUE TITLE
옛한글 입력시 아래아 등 중성이 입력이 안됩니다.

### ISSUE THREAD

**Issue by ianjoo** [gureum/gureum#527]
여러번 제기되었던 문제인 듯 하나 제 맥북에서 여전히 작동하지 않습니다.
예를 들면 ""을 쓰려고 두벌식에서 "ㄴㅏㅏㄴ"을 입력하면 "ᄂᆫ"이라고 뜹니다.
직업상 옛한글을 많이 입력해야 하는 상황인데 부디 속히 도와주시면 정말 감사하겠습니다.

**Comment by ianjoo** [comment]
질문을 닫으신 이유가 무엇인지요?

**Comment by youknowone** [comment]
@soomtong 혹시 닫으신 이유가 있으면 코멘트해 주셔요

**Comment by yous** [comment]
#208 이슈와 비슷해 보입니다만, 버전이 많이 달라서 원인은 다를 수 있습니다.

**Comment by ianjoo** [comment]
@youknowone 됩니다. 정말 감사드립니다. 업무가 한층 더 편리해졌습니다.
하나 더 여쭙자면, 혹시 방점 입력은 불가능한지요? ( 〮,  〯) 이것까지 된다면 한층 더 편리할 것 같습니다.

**Comment by youknowone** [comment]
제가 옛한글 입력 시스템을 잘 모르고 libhangul을 그냥 붙인거라 쉬운 입력방법 말고는 잘 모르겠는데, 혹시 일반적으로는 방점 입력을 어떻게 하는지 아시나요? 한컴 한글이라던가요.

**Comment by ianjoo** [comment]
[이곳](https://ohi.pat.im/)의 온라인 한글 입력기에서는 옛한글 옵션을 선택하고 "가"를 입력한 다음 (세벌식에서) Shift+Y를 누르면 "가〯"가 출력됩니다. (두벌식에서는 왜인지 방점 입력이 안되네요.)

**Comment by ianjoo** [comment]
다시금 감사드립니다. 이 질문은 이만 닫도록 하겠습니다.

**Comment by youknowone** [comment]
방점 입력이 어떻게 되나 저도 확인해보면 좋을것 같습니다.

@pat-al 위의 온라인 입력기도 팥알님이 만드셨네요! 혹시 방점 처리 하고 있는 libhangul 포크 아시는게 있으시면 소개 부탁드려도 될까요?

**Comment by yous** [comment]
@ianjoo 두벌식의 경우엔 잘 모르겠는데요, @pat-al 님께서 만드신 신세벌식 P2 옛글 등의 자판에서는 Shift + Y, Shift + U로 '가〯', '가〮' 등을 입력할 수 있는 것을 확인했습니다.

현재 1.10.0-pre8 버전을 기준으로 3beol 님의 libhangul을 사용할 수 있도록 빌드한 것이 있으니 한번 시도해보시기 바랍니다. https://github.com/yous/gureum/releases/tag/GureumKIM-1.10.0-pre8-contrib

**Comment by soomtong** [comment]
아이고, 제가 이슈를 닫았네요. 
13시간 전이면 한참 야간 업무에 마무리하고 이슈 점검하고 있을 때 였을 것 같습니다. (요즘 자는 시간 빼고 업무 중이라)

@ianjoo 님 정말 죄송합니다. 진심으로 사과 드립니다. 
지난 이슈들 보시면 아실 수 있지만 (변명 같네요) 제가 아무 코멘트 없이 닫지 않거든요. 
어떤 경유로 클릭이 되었는지 모르겠지만 제 실수 입니다.

다시 한 번 사과 드립니다. ㅜㅜ

**Comment by ianjoo** [comment]
> 아이고, 제가 이슈를 닫았네요.
> 13시간 전이면 한참 야간 업무에 마무리하고 이슈 점검하고 있을 때 였을 것 같습니다. (요즘 자는 시간 빼고 업무 중이라)
> 
> @ianjoo 님 정말 죄송합니다. 진심으로 사과 드립니다.
> 지난 이슈들 보시면 아실 수 있지만 (변명 같네요) 제가 아무 코멘트 없이 닫지 않거든요.
> 어떤 경유로 클릭이 되었는지 모르겠지만 제 실수 입니다.
> 
> 다시 한 번 사과 드립니다. ㅜㅜ

아닙니다, 괜찮습니다. ^^ 신경쓰지 마십시오.

**Comment by ianjoo** [comment]
@yous 됩니다. 정말 감사합니다! 업무가 한결 편해졌습니다.
