### ISSUE TITLE
웨일 브라우저에서 숫자와 특수문자가 두번씩 입력됨

### ISSUE THREAD

**Issue by gomjii** [gureum/gureum#529]
pre8로 업데이트 한 후 두벌식 입력소스에서 한글 외의 특수문자, 숫자들이 11 22 ?? 이런식으로 입력이 됩니다.

또 사소한 부분인데 pre8에서 구름 입력기에 관하여(회색부분으로 눌러지지가 않음)/버전 확인 (반응없음)이 확인되었습니다.

마지막으로 덕분에 잘쓰고 있습니다. 감사합니다.

**Comment by youknowone** [comment]
두 번 입력되는건 어떤 애플리케이션에서 나타나는 현상인가요?

**Comment by gomjii** [comment]
주로 웨일 브라우저에서 확인했습니다.

**Comment by jinside** [comment]
안녕하세요~

저도 웨일 브라우저에서만 요 현상이 보이고 있습니다.
사파리와 크롬에서는 보이지 않고 있습니다. (OSX 10.14.4, 구름 1.10.0)

"쿼티" 자판 설정에서는 모든 글자가 문제가 없습니다.
"두벌식" 자판 설정에서는 한글을 제외한 나머지 문자들(숫자, 기호 등)이 두번씩 입력이 됩니다.

한글을 입력 중에는 한글 이외의 글자를 누르면 다음칸에 1문자만 나옵니다.
공란 혹은 한글의 조합이 끝나고 새로 입력하는 단계에서는 중복 입력 현상이 보입니다.

덧붙 : 늘 감사합니다. ^^

**Comment by youknowone** [comment]
이 문제는 웨일 팀에 보고를 넣었습니다

**Comment by youknowone** [comment]
이 문제를 수정하는 실험 빌드를 만들었습니다. 큰 문제가 발견되지 않으면 다음 업데이트에 포함됩니다.

https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.1-experimental

**Comment by youknowone** [comment]
문제를 수정한 1.10.1을 배포했습니다. https://github.com/gureum/gureum/releases/tag/1.10.1

문제 확인에 큰 도움 주신 웨일 브라우저 팀에 감사의 말을 전합니다.
