### ISSUE TITLE
pre8 ESC 기능 사라짐 현상.

### ISSUE THREAD

**Issue by 1ilsang** [gureum/gureum#530]
안녕하세요. vim 에서 구름을 정말 편하게 사용하고 있습니다.

다만 ESC 옵션을 켰을 때 기존의 ESC 기능이 작동되지 않아 조금 불편합니다.

예를 들면 카카오톡에서 한글로 채팅을 한 뒤 ESC를 누르면 채팅창이 종료 되지 않고 vi 모드와 같이 쿼티로 바뀌어 두 번 눌러야 하는 단점이 있습니다.

혹시 vim 모드일때에만 ESC 기능이 작동할 수 있을까요?

spec
Mac Mojave

**Comment by soomtong** [comment]
아 이건 정말 좀 타협이 필요하겠네요.
꼭 vim 에디터가 아니어도 유사한 기능을 제공하는 (vim 모드를 제공하는 경우) 이 기능을 잘 사용하고 있거든요.
구름 패널 세팅하는 곳에서 이 기능을 bypass 할 수 있도록 앱(프로그램)을 지정할 수 있도록 하면 될 것 같은데
딱 생각해 봐도 개발 공수가 꽤 들어갈 것 같습니다. ^^

**Comment by yous** [comment]
제가 #425 이슈에서 이해한 바로는 ESC를 눌렀을 때 자판도 영문으로 전환되고, 창의 ESC 기능도 작동해야 정상적인 동작인 것 같은데, 이번 pre8 버전에서 동작이 바뀐 것인지, 아니면 카카오톡 등에서만 동작이 달라지는 것인지 확인이 필요할 것 같습니다.

**Comment by 1ilsang** [comment]
@yous 카카오톡 뿐만 아니라 여하 다른 프로그램에서도 모두 ESC기능이 한 번에 되지 않고 있습니다. 모두 쿼티를 거쳐야만 ESC 기능이 작동합니다.

**Comment by youknowone** [comment]
pre6에서 7/8로 넘어갈때 자판 전환 처리하는부분이 조금 바뀌었는데 그것때문인가 싶네요
