### ISSUE TITLE
Donation 할 수 있는 방법이 있나요?

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [gureum/gureum#535]
beta pre8, pre9 버전 릴리스 감사합니다.
안정성이 많이 향상된 느낌이라 만족합니다!

요즘 다른 오픈소스 프로젝트 보면 donation 할 수 있는 방법이 많던데요,
혹시 구름 입력기 프로젝트에도 기부 할 수 있는 방법이 있는지 궁금합니다.

**Comment by yous** [comment]
현재 프로젝트 페이지에 Sponsor 버튼이 추가되었습니다.

**Comment by youknowone** [comment]
프로젝트 페이지 (현재 페이지의 상단)에도 Sponsor 버튼을 추가하였고, 구름 입력기 최신버전을 설치하면 메뉴에 '후원하기'를 추가하였습니다. 좋은 제안 감사합니다
