### ISSUE TITLE
캡스락키가 반복적으로 비활성화되는 문제

### ISSUE THREAD

**Issue by JaeyunJun** [gureum/gureum#542]
오래전부터 한/영 단축키로 cmd+space를 이용하고있습니다.
따라서 캡스락 키는 영문 대소문자 변경용도로만 사용중입니다.
현재 구름입력기 rc2 버전 기준으로 캡스락 키를 누르면 불이 한번 들어오고 바로 꺼지는 문제가 있습니다.
아마 캡스락으로 오래 눌러야만 활성화되는 기능으로 인해 영향을 받은 것 같습니다.
해당기능을 조절할 수 있으면 좋을 것 같습니다.

**Comment by yous** [comment]
Caps Lock 키 옵션을 끄는 방법은 다음과 같습니다. 입력 소스에서 맥 기본 한글 자판을 추가하시면 '한 / A 또는 Caps Lock 키로 마지막으로 사용한 라틴 입력 소스 전환' 등의 옵션이 보입니다. 이를 체크 해제해주시면 옵션을 끌 수 있습니다. 이후에 맥 기본 한글 자판은 다시 빼시면 됩니다.

#413

![Screenshot 2019-06-03 11 09 38](https://user-images.githubusercontent.com/853977/58771611-1ad01300-85f0-11e9-9399-3aa73cd718a7.png)

**Comment by JaeyunJun** [comment]
@yous 님께서 답변주신 내용대로 원래부터 해당 옵션을 해제하고 사용했습니다.
현재 발생되는 이슈는 체크가 해제된 상태에서의 증상입니다.
혹시 몰라 다시 체크했다가 해제해보았는데 증상이 동일합니다.

**Comment by youknowone** [comment]
문제를 수정한 rc3를 배포했습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-rc3

**Comment by jeemyeong** [comment]
![image](https://user-images.githubusercontent.com/13030735/65061521-123ff480-d9b5-11e9-8b5a-218e772a71d3.png)
![image](https://user-images.githubusercontent.com/13030735/65061545-1f5ce380-d9b5-11e9-9ac4-af67c91ea794.png)

@yous 
저는 저 옵션이 보이지 않는데요, 제 맥북이 오래됐기 때문일까요?

**Comment by yous** [comment]
기본 한글 자판을 아무거나 하나 추가하면 아마 메뉴에서 보일 겁니다.

**Comment by jeemyeong** [comment]
@yous 

오 되네요. 감사합니다!
