### ISSUE TITLE
텔레그램에서 글 입력 후 엔터로 바로 전송이 안되는 증상

### ISSUE THREAD

**Issue by JaeungHyun** [gureum/gureum#543]
카톡이나 아이메시지 앱을 이용할때는 엔터로 전송이 바로 되는데
텔레그램에서는 바로 전송이 안되네요

글자를 입력하고 엔터를 한번 치면 커서가 마지막 글자 아래에 밑줄처럼 있다가
다음칸으로 이동하고 여기서 엔터를 한번 더 입력해야 전송이 됩니다.

**Comment by tobark** [comment]
Telegram for macOS에서는 해당 증상이 나타나는데, Telegram Desktop은 괜찮네요. 우선 Telegram Desktop 사용을 추천드립니다.

https://desktop.telegram.org/

**Comment by youknowone** [comment]
#165 
이 문제는 텔레그램의 버그로 보입니다.
텔레그램 쪽에 버그 리포트 부탁드립니다.

**Comment by frombit** [comment]
기본 한글입력기는 문제가 없습니다. 
구름입력기 , 기본한글, 영문 이렇게 번갈아가면서 테스트해봐도 바로 증상이 나오네요
