### ISSUE TITLE
norman layout 추가

### ISSUE THREAD

**Issue by marocchino** [gureum/gureum#549]
안녕하세요.

제가 쓰는 레이아웃이 없어서 혹시나 하는 마음에 추가요청 넣어봅니다.

https://normanlayout.info/

쿼티와의 차분은 다음과 같습니다.
```diff
-"`1234567890-=\\qwertyuiop[]asdfghjkl;'zxcvbnm,./~!@#$%^&*()_+|QWERTYUIOP{}ASDFGHJKL:\"ZXCVBNM<>?"
+"`1234567890-=\\qwdfkjurl;[]asetgynioh'zxcvbpm,./~!@#$%^&*()_+|QWDFKJURL:{}ASETGYNIOH\"ZXCVBPM<>?"

**Comment by yous** [comment]
안녕하세요, 이번에 1.11.1 버전이 출시되면서 환경설정에서 시스템 레이아웃을 설정할 수 있도록 되었습니다.

로마자 입력기 설정의 키보드 레이아웃을 Norman으로 고르시면 사용하실 수 있을 것 같습니다.

<img width="415" alt="Screenshot 2020-08-06 12 09 24" src="https://user-images.githubusercontent.com/853977/89486301-b608dd80-d7dd-11ea-92fa-dc6e2e2c2a52.png">

**Comment by marocchino** [comment]
감사합니다.
