### ISSUE TITLE
옛한글과 채움문자 제거

### ISSUE THREAD

**Issue by dohyunkim** [gureum/gureum#55]
옛한글을 테스트 삼아 입력해봤습니다. 
기본 설정 상태에서 세벌식옛글 키보드를 선택하고 입력하니 중성이 자꾸 지워집니다.
혹시 해서 환경설정에서 “채움문자 제거”를 “채움문자 보임”으로 바꾼 후 다시 해보니 정상 입력됩니다.
일반 유저로써 옛한글 입력과 채움문자 간의 연관성을 알아채기가 어렵습니다.

**Comment by youknowone** [comment]
최신 베타에서 채움문자 관련 옵션을 제거하였고 옛한글 입력 관련된 버그도 수정이 되었습니다.

https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre9

**Comment by youknowone** [comment]
1.10을 정식으로 릴리즈하였습니다. 문제가 지속되면 다시 알려주세요. https://github.com/gureum/gureum/releases/1.10.0
