### ISSUE TITLE
Caps Lock 길게 누를때 영문 대문자가 입력되지 않는 현상

### ISSUE THREAD

**Issue by B4TT3RY** [gureum/gureum#550]
- macOS 버전: 10.14.5
- 구름 버전: 1.10.0
- 문제가 발생하는 애플리케이션 이름과 버전:
- 문제가 있는 동작: 영문 입력기에서 Caps Lock 키를 길게 눌러 불이 들어오는데 영문 대문자가 나오지 않고 한글이 나옵니다. (한글 입력기에서 길게 누르면 영문 대문자가 나옵니다.)
- 기대하는 정상 동작: 영문 입력기에서 영문 대문자가 나오는 것
- 재현 방법: 

베타 버전에서 추가된 기능인걸로 아는데 어디서 활성화 시키는지 잘 모르겠네요..

**Comment by B4TT3RY** [comment]
그리고 해당 오류 관련인지는 모르겠지만 영문을 입력하다가 한글로 변경해야할때 캡스락 기능이 켜져버려서 한글을 입력하지 못하고 영문 대문자가 나오는 문제가 있네요

**Comment by jinside** [comment]
저도 이부분은 개선이 필요할 거 같습니다.
shift-space 조합으로 구름 두벌식과 구름 쿼티를 오가는데... Caps Lock 사용시에 대문자 변환이 원활하지 않고요.
한글-영문 조합을 오가다가 Shift-Space 로 변환하니 대문자로 나오더라고요.
여전히 Caps Lock 이 한영전환에 영향을 끼치고 있는 것 같고요. 동시에 고유의 기능도 작동하는 거 같습니다.
옵션으로 선택할 수 있게 해주시면 어떨까 싶고요.

숫자나 기호가 두번 입력되는 건 왜 그런지 모르겠네요. 이런 현상도 있어요.

덧붙임..... 좋은 프로그램 개발해주셔서 감사합니다.

**Comment by yous** [comment]
Caps Lock 관련 기능을 켜고 끄는 방법은 다음 링크를 참고해주세요. https://github.com/gureum/gureum/issues/542#issuecomment-498090598

맥 시스템 설정을 참고해서 따라가도록 하였는데, 구름 입력기 환경 설정에는 보이지 않으니 시스템 설정과 별개로 구름 환경 설정에서 처리하도록 바꾸는 것이 나을지도 모르겠다는 생각이 듭니다.

**Comment by jinside** [comment]
네~ 알려주신 방법으로 잘 해결 되었습니다. ^^
빠른 피드백 감사드려요...

요약 : macOS 기본 한글 자판을 추가해서 Caps Lock 옵션을 빼고 다시 기본 한글자판을 삭제하면 끝.

**Comment by B4TT3RY** [comment]
저 방법으로 적용하면 Caps Lock을 통한 한영전환은 작동하지 않는 것 아닌가요?

**Comment by yous** [comment]
맞습니다. 옵션을 켜면 캡스락으로 한영 전환, 길게 누르면 캡스락 기능이 작동하도록 구현된 상태입니다.

**Comment by B4TT3RY** [comment]
저는 Caps Lock으로 한영전환을 하는데 해당 문제가 생긴 상황이라..

**Comment by yous** [comment]
네, 아무래도 캡스락 기능에도 개선이 좀 더 필요한 상황인 것 같습니다.

**Comment by youknowone** [comment]
다음 릴리즈에서 수정됩니다

**Comment by youknowone** [comment]
실험빌드: https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.1-experimental

**Comment by youknowone** [comment]
이 문제가 수정된 새 버전이 배포되었습니다. https://github.com/gureum/gureum/releases/tag/1.10.1
