### ISSUE TITLE
TextWrangler 에서 자판이 두 번씩 입력됩니다.

### ISSUE THREAD

**Issue by yagain7** [gureum/gureum#554]
- macOS 버전: 10.14.5
- 구름 버전: 1.10.0
- 문제가 발생하는 애플리케이션 이름과 버전: TextWrangler 5.5.2
- 문제가 있는 동작: 한글 두벌식이나 세벌식에서 한 글자 입력시 동일한 글자가 한 번 더 나타납니다. 
- 기대하는 정상 동작: 한 글자 입력시 한 글자만 입력되어야 합니다.
- 재현 방법: 
두벌식 선택 후 "두벌식입력" 이라고 타이핑하면 "둡두벐벌식식입입력력"이라고 디스플레이되고,
세벌식390 선택 후 "세벌식390입력" 이라고 타이핑하면 "세세벌벌식식390입입력력" 이라고 디스플레이됩니다.

**Comment by youknowone** [comment]
이 문제를 수정하는 실험빌드입니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.1-experimental

다음 버전에서 수정됩니다

**Comment by youknowone** [comment]
이 문제를 수정한 새 버전이 배포되었습니다 https://github.com/gureum/gureum/releases/tag/1.10.1

**Comment by yagain7** [comment]
수정 감사합니다. 잘 쓰겠습니다.^^
