### ISSUE TITLE
CapsLock 한영 변환 기능 끄기

### ISSUE THREAD

**Issue by wphestiraid** [gureum/gureum#555]
- macOS 버전: 10.14.5
- 구름 버전: 1.10.0
- 문제가 발생하는 애플리케이션 이름과 버전: 모든 곳
- 문제가 있는 동작: CapsLock으로 언어 전환을 원하지 않으나 언어 전환이 되고 길게 눌러야 CapsLock 기능이 동작
- 기대하는 정상 동작: CapsLock으로 언어 전환이 되지 않고 짧게 눌러도 기본적인 CapsLock 기능이 동작
- 재현 방법: 그저 CapsLock을 눌러보세요.

**Comment by yous** [comment]
Caps Lock 옵션을 끄는 방법은 이 링크를 참조하세요. https://github.com/gureum/gureum/issues/542#issuecomment-498090598

**Comment by wphestiraid** [comment]
@yous 저는 해당 옵션을 끄고 사용 중이었는데 구름 입력기를 통해서 다시 활성화가 된 건가요?

**Comment by yous** [comment]
저 시스템 환경설정에서 보이는 'Caps Lock 키로 자판 전환' 옵션은 시스템에 저장이 되는데요, 그 값을 구름 입력기에서 읽어서 사용하고 있습니다. 기본 한글 입력기를 추가했을 때 해당 옵션이 꺼져 있는 채로 나온다면 구름에서 제대로 읽지 못했거나 적용이 되지 않은 버그일 가능성이 있습니다. 그 경우엔 임시로 체크했다 다시 해제하시면 꺼질 것 같습니다.

**Comment by wphestiraid** [comment]
@yous 빠른 답변 감사합니다. 👍
