### ISSUE TITLE
맥 엘 캐피탄에서도 되게 해주세요.

### ISSUE THREAD

**Issue by makintosh-2** [gureum/gureum#564]
맥 os 엘 캐피탄입니다. 어느 날 업데이트 하라고 떠서 했더니만....
아시겠지만 안되네요..ㅠㅠ 
찾고 찾아보니 os최신버전에만 사용가능한듯한데....
os 업데이트가 보통 조심스런 일이 아니라 업데이트 안하고 있는 상황입니다....
플리즈....구버전도 다시 사용가능하게 해주시면 안될까요?

- macOS 버전: 10.11.6
- 구름 버전: 1.20.8
- 문제가 발생하는 애플리케이션 이름과 버전:  
- 문제가 있는 동작:

**Comment by youknowone** [comment]
https://github.com/gureum/gureum/releases 에서 구 버전 다운받아서 설치하시면 좋을것 같습니다.

아마 이전에 쓰시던 버전은 이 버전입니다
https://github.com/gureum/gureum/releases/tag/GureumKIM-1.8.9

**Comment by makintosh-2** [comment]
p {margin-top:0px;margin-bottom:0px;} 


	
	
아...됩니다요..감사드립니다....
