### ISSUE TITLE
Capslock을 예전처럼 쓸수가 없네요.

### ISSUE THREAD

**Issue by seungmin84** [gureum/gureum#566]
새 버전에서 일부로 기능 변경을 하신건지 모르겠는데

이전 버전까지는 캡스락이 대소문자 변경 기능이었는데

이번 업데이트 이후 한영전환으로 강제 변환되었습니다.

이전 사용자들도 호환이 되게 옵션을 주면 좋을거 같은데 

업데이트 부탁드립니다.

**Comment by yous** [comment]
Caps Lock 관련 기능을 켜고 끄는 방법은 다음 링크를 참고해주세요. https://github.com/gureum/gureum/issues/542#issuecomment-498090598
