### ISSUE TITLE
세벌식390에서 "세벌식 정석 강요" 시 ㄹㅂ 받침 입력 불가

### ISSUE THREAD

**Issue by nainu** [gureum/gureum#567]
- macos 버전: 10.14.5
- 구름 버전: 1.10.0
- 자판: 세벌식 390
설정 화면:
![image](https://user-images.githubusercontent.com/18378/59588606-f3fefa00-9122-11e9-8d4f-c2e0e72c3a9f.png)

- 문제가 발생하는 애플리케이션: 크롬, iterm, slack (앱과는 상관없이 발생하는 것 같습니다)
- 문제가 있는 동작: 짧 을 입력하고자 하는데 390 에서는 ㄼ 받침의 단축키가 없어서 llfw3 로 입력해야 하는데, 이 경우 ㅂ 가 다음 글자로 넘어갑니다.
자판은 여기서 확인하였습니다.
https://www.google.com/search?q=390+%EC%9E%90%ED%8C%90&tbm=isch&source=iu&ictx=1&fir=KwiAZbhwB7sVpM%253A%252CeKBtANDCW0GfIM%252C_&vet=1&usg=AI4_-kSWZRBuCA9OPZ-aF3g2J63-OZvlww&sa=X&ved=2ahUKEwjO5PTrh_DiAhVGi7wKHYh4Ae8Q9QEwB3oECAYQEg#imgrc=KwiAZbhwB7sVpM:

- 기대하는 정상 동작: w 3 로 ㄼ 받침을 "정석 강요" 모드에서도 동작했으면 좋겠습니다.
- 재현 방법:
  - iterm 실행
  - L 입력: ㅈ
  - L 입력: ㅉ
  - F 입력: 짜
  - W 입력: 짤
  - 3 입력: 짧
짧 글자를 입력할 수 있어야 합니다.

**Comment by youknowone** [comment]
말씀하신 조합의 데이터가 빠져있네요. https://github.com/gureum/gureum/blob/master/OSXCore/data/keyboards/hangul-combination-39.xml

**Comment by youknowone** [comment]
https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.2-experimental

이 문제를 수정한 새 실험버전을 배포했습니다.

**Comment by youknowone** [comment]
이 문제의 수정이 포함된 새 버전을 배포하였습니다. https://github.com/gureum/gureum/releases/tag/1.11.1

**Comment by nainu** [comment]
잘 동작하는 것 확인했습니다. 감사합니다. :bow:
