### ISSUE TITLE
한글입력기에서 기본 입력 모드를 영문으로 하는 옵션

### ISSUE THREAD

**Issue by junhochoi** [gureum/gureum#573]
- macOS 버전: 10.14.5
- 구름 버전: 1.10.0
- 사용중인 한글/영문 배열: 한글 두벌식
- 문제가 발생하는 애플리케이션 이름과 버전:
- 문제가 있는 동작:
  구름 입력기를 기본으로 하면 새 창으로 이동했을 때 기본 입력이 한글 입력 모드가 되는데,
  한글을 주로 사용한다면 괜찮겠지만 영문과 같이 쓰거나 개발하는 경우에는
  기본 입력이 영문으로 할 수 있는 옵션이 있으면 좋겠습니다. 현재는 입력 포커스가 바뀔 때 마다
  한영전환 키를 눌러서 영문으로 바꾸어 쓰고 있습니다.
- 기대하는 정상 동작:
- 애플 기본 한글 입력기의 동작:
- 재현 방법:

**Comment by yous** [comment]
안녕하세요, 혹시 '도큐멘트의 입력 소스로 자동으로 전환' 항목에 체크가 되어있는 상태인가요?

<img width="668" alt="Screenshot 2019-06-28 16 14 24" src="https://user-images.githubusercontent.com/853977/60324448-d00fa400-99bf-11e9-940c-37c087393d20.png">

**Comment by junhochoi** [comment]
네 체크되어 있는데 끄고 해도 차이는 없네요.

**Comment by junhochoi** [comment]
#119 에 나와 있는 대로 다시 설치해 보았더니 원하는 대로 동작 합니다. 이 이슈는 닫도록 하겠습니다. 감사합니다.
