### ISSUE TITLE
^[키로 영문 전환 시 Shift+Space를 두 번 눌러야 한글 전환이 되는 문제

### ISSUE THREAD

**Issue by jeiea** [gureum/gureum#583]
- macOS 버전: 10.14.6
- 구름 버전: 1.10.1
- 사용 중인 배열: 두벌식 / 쿼티
- 수행한 것
  - 구름 설정에서 vi 모드 설정을 켭니다.
  - 두벌식 상태에서 ^[를 눌러 쿼티로 전환합니다.
  - Shift+Space를 누릅니다.
- 기대한 동작: 두벌식으로 다시 돌아갑니다.
- 실제 동작: 쿼티가 유지되며, 다시 Shift+Space를 누르면 두벌식으로 전환됩니다.
- 애플 기본 한글 입력기의 동작: vi 모드가 없기에 해당 사항이 없습니다.

**Comment by yous** [comment]
안녕하세요, 어떤 환경에서 ^[를 눌렀을 때 Shift+Space를 두 번 눌러야 두벌식으로 전환되나요?

방금 Safari로 이 페이지 댓글 입력창에서 테스트해봤으나 잘 변경되는 것 같습니다.

**Comment by jeiea** [comment]
저는 vscode와 크롬에서 테스트해봤습니다.

2019년 7월 26일 (금) 오후 7:19, Chayoung You <notifications@github.com>님이 작성:

**Comment by jeiea** [comment]
사파리 주소창에서도 같은 현상이 일어났고, 대략 두벌식에서 ^[를 누르면 구름입력기의 쿼티 상태로, 그 다음 Shift+Space를 누르면 애플 입력기의 쿼티 상태로, 그 다음 Shift+Space를 눌러야 구름입력기의 두벌식으로 넘어가는 것 같습니다.

**Comment by youknowone** [comment]
애플 쿼티로 넘어가는건 구름 기능이 아닌데, 혹시 시스템 자판 전환 단축키를 구름과 같이 설정해 두셨나요?

**Comment by jeiea** [comment]
네. 제어판에서 그렇게 하라는 것 같았고 애플 기본 자판을 제거할 수 없어서 그렇게 설정했는데 그렇게 쓰는 게 아닌 모양이네요. 기능을 탐구할 시간이 부족해서 제껴뒀는데 내일 다시 알아보겠습니다.

**Comment by jeiea** [comment]
시스템 자판 전환 단축키를 해제하고 구름 입력기 설정에서 입력기 바꾸기 단축키만 Shift+Space로 하는 게 제가 원한 설정이었네요. 덕분에 해결했습니다.

**Comment by youknowone** [comment]
잘 해결되었다니 다행입니다!
