### ISSUE TITLE
클린 삭제 방법 (언인스톨, uninstall)

### ISSUE THREAD

**Issue by JeffGuKang** [gureum/gureum#584]
좋은 프로그램 감사합니다. 항상 잘 쓰고 있습니다.

오류 발생시 클린 설치를 통해 해결하거나, 가끔씩 인스톨된 프로그램들을 지울경우를 위해 
언인스톨 하는 방법도 제공해주시면 좋겠습니다.

**Comment by youknowone** [comment]
바이너리는 `/Library/Input Methods/Gureum.app`을 삭제하면 되고,
설정은 `~/Library/Preferences/org.youknowone.Gureum.plist` 을 삭제하면 됩니다.

어디 문서를 만들어 두는게 좋겠네요.

**Comment by yous** [comment]
일반적인 삭제 방법은 추가되었습니다. #608, #624

**Comment by JeffGuKang** [comment]
감사합니다.
