### ISSUE TITLE
로마자로 바꾸기 단축기 한글로 바꾸기 단축기가 적용이 안됩니다.

### ISSUE THREAD

**Issue by DHKim24** [gureum/gureum#589]
- macOS 버전: 10.14.6
- 구름 버전: 1.10.1
- 사용중인 한글/영문 배열: 두벌식 한글 / 쿼티
- 문제가 발생하는 애플리케이션 이름과 버전: 
- 문제가 있는 동작: 로마자로 바꾸기 단축키, 한글로 바꾸기 단축키가 사용이 도지 않습니다.
<img width="673" alt="스크린샷 2019-08-16 오후 8 17 21" src="https://user-images.githubusercontent.com/54175490/63164382-3aa99b80-c063-11e9-8aaa-67b3e606d486.png">

- 기대하는 정상 동작: 로마자로 바꾸는 단축키를 누르면 영어가 나오고 한글로 바꾸는 단축키를 누르면 한글이 되어야 되는데 그렇지 않습니다.

단축키 다른것으로 바꿔도 똑같네요 스크린샷 첨부합니다.

**Comment by yous** [comment]
제보 감사합니다. #590 PR에서 해당 기능을 복원했고, 다음 릴리스에 포함될 것 같습니다.

**Comment by DHKim24** [comment]
감사합니다
