### ISSUE TITLE
설정창 미동작 (1.10.2-experimental1)

### ISSUE THREAD

**Issue by dongyoonlee** [gureum/gureum#591]
- macOS 버전: 10.14.5 (18F132)
- 구름 버전: Version 1.10.2-experimental1 (1.10.2-experimental1)
- 사용중인 한글/영문 배열:세벌식390(구름)/ABC(기본입력기)
- 문제가 발생하는 애플리케이션 이름과 버전: System Preferences
- 문제가 있는 동작: 설정창이 동작하지 않습니다.

![image](https://user-images.githubusercontent.com/16536584/63662471-7da10700-c7f9-11e9-866f-f5c8015f0654.png)

- 기대하는 정상 동작:설정 화면이 잘 뜬다
- 애플 기본 한글 입력기의 동작:
![image](https://user-images.githubusercontent.com/16536584/63662518-b640e080-c7f9-11e9-8c56-cd820c5fab05.png)

- 재현 방법: 세벌식390 활성화 상태에서 > 메뉴 > Open Keyboard Preferences... > 설정 안보임 

로그 확인방법 알려주시면 확인해볼 수 있습니다.
임시버전의 경우 이슈 등록 방법이 따로 있다면 그쪽으로 다시 올리겠습니다.
임시버전의 경우 티켓으로 처리하지 않고 계시다면 편하게 close해주셔도 됩니다.

**Comment by dongyoonlee** [comment]
아래 유사한 이슈가 있네요.
저의 경우는 입력기는 잘 동작 합니다. 설정만 보이지 않는 이슈입니다.

**Comment by dongyoonlee** [comment]
아래 댓글을 다 읽어보니, 동일한 문제라 판단되어 close합니다.

**Comment by yous** [comment]
#546 이슈와 비슷한 상황인 것 같은데, 다음 릴리스를 통해 해결하려고 합니다.
