### ISSUE TITLE
환경설정 창이 표시되지 않습니다. (1.10 ~)

### ISSUE THREAD

**Issue by temosan** [gureum/gureum#592]
- macOS 버전: 10.14.5 
- 구름 버전: 1.10.2-exper
- 사용중인 한글/영문 배열: 쿼티, 390
- 문제가 발생하는 애플리케이션 이름과 버전: -
- 문제가 있는 동작: 환경설정에서 고급설졍이 표시되지 않아 모아치기를 사용하지 못하고 있습니다.
- 기대하는 정상 동작: -
- 애플 기본 한글 입력기의 동작: -
- 재현 방법: 1.10 -> 1.10.1업데이트 이후 증상

**Comment by temosan** [comment]
#552에서 공통증상 확인완료

**Comment by youknowone** [comment]
메뉴에 환경설정을 추가한 새 버전을 배포하였습니다

https://github.com/gureum/gureum/releases/tag/1.11.1
