### ISSUE TITLE
환경설정을 입력소스별로 다르게 출력하는 방법을 탐색

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#595]
환경설정에서 구름은 입력기 배열에 관계없이 항상 같은 설정이 나옵니다.

예: 로마자 입력기에서도 한글 입력기 설정이 나옵니다.

환경설정 뷰를 만들거나 열 때 현재의 배열을 알 방법이 있으면 불필요한 설정을 빼고 보여줄 수 있을 것입니다.

**Comment by Jae-eun** [comment]
해보겠습니다~

**Comment by youknowone** [comment]
더 이상 system preferences에 보이지 않아 구현할 필요가 없습니다
