### ISSUE TITLE
한자 입력 후보 마지막에 한글 원래 입력을 표시

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#596]
"한<한자>"을 입력하면, 마지막 후보로 '한'이 표시됩니다.

macOS 내장 입력기의 동작을 참고하여 동일한 동작을 하도록 수정합니다.

<img width="104" alt="image" src="https://user-images.githubusercontent.com/69878/64366451-39133800-d051-11e9-8a6d-68b038180a3e.png">

**Comment by dohyun-kim29** [comment]
제가 하겠습니다

**Comment by youknowone** [comment]
HanjaComposer.buildCandidates에서 keyword를 후보 마지막에 넣는걸로 될 것 같습니다

**Comment by dohyun-kim29** [comment]
감사합니다!!

2019년 9월 8일 (일) 오후 2:26, Jeong YunWon <notifications@github.com>님이 작성:

**Comment by youknowone** [comment]
참고: https://github.com/gureum/gureum/pull/622/commits/7d86efcdb729db6076f06a71c048bca45aeeb442

**Comment by youknowone** [comment]
#639 에서 이 이슈가 해결되었으므로 7d86efc 를 다시 반영하면 될것 같네요
