### ISSUE TITLE
한자 입력 후보를 내장입력기처럼 서식을 적용해 표시

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#597]
뜻에 회색 작은글꼴 적용이 되어 있습니다.

내장 입력기
![image](https://user-images.githubusercontent.com/69878/64366720-c6ef2300-d051-11e9-8182-7f0e4087ea2d.png)

구름 입력기
![image](https://user-images.githubusercontent.com/69878/64366817-0289ed00-d052-11e9-8dfc-79d95610b715.png)

**Comment by presto95** [comment]
제가 시도해보겠습니다!

**Comment by youknowone** [comment]
`HanjaComposer.buildCandidates()` 에서 위 서식을 적용해 만든 `NSAttributedString`을 만들어 반환합니다. `searchCandidates()`의 반환이 NSString이기 때문에 여기부터 조정해줄 필요가 있어 보입니다

**Comment by presto95** [comment]
애트리뷰트를 주는 것이 지원되지 않는 것 같습니다.

- 한자 후보를 `NSAttributedString`으로 생성하고 이것에 여러 애트리뷰트를 주었지만 적용되지 않았습니다.
  - `string`을 바꾸는 것은 잘 적용되었습니다.
- `IMKCandidates` 객체의 `setAttributes(_:)` 메소드를 사용하여 후보를 보여주는 윈도우에 대해 스타일을 적용해 보았으나 적용되지 않았습니다.

**Comment by youknowone** [comment]
확인 감사합니다. 사용한 코드를 보고싶은데, 브랜치 하나 만들어 올려두시고 링크 걸어주실수 있을까요?

**Comment by presto95** [comment]
https://github.com/gureum/gureum/pull/616

**Comment by youknowone** [comment]
안되는것 같으니 이슈는 닫아두겠습니다. 문제 확인해주셔서 감사합니다
