### ISSUE TITLE
긴한자 검색 정상 동작하지 않음

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#603]
- macOS 버전: 
- 구름 버전: 
- 사용중인 한글/영문 배열: 모든 한글 영문 자판
- 문제가 발생하는 애플리케이션 이름과 버전:
- 문제가 있는 동작: `<alt+enter>한자` 를 입력하면 '한자'가 들어가는 후보가 완성되지 않음
- 기대하는 정상 동작: '한자'를 블럭 잡아서 단축키를 입력했을 때와 같은 동작이 기대됨
- 애플 기본 한글 입력기의 동작: 상응하는 동작 없음
- 재현 방법:

**Comment by Jae-eun** [comment]
한자

**Comment by Jae-eun** [comment]
해보겠습니다~
