### ISSUE TITLE
단어 앞에 공백이 있을 시에 한자 변환이 되지 않음

### ISSUE THREAD

**Issue by gaki2745** [gureum/gureum#606]
macOS 버전: MacOS Mojave 10.14.6
구름 버전: 1.10.1-31-g4d794b9-Debug
사용중인 한글/영문 배열: 모든 한글 영문 자판
문제가 발생하는 애플리케이션 이름과 버전:
문제가 있는 동작: 가령 ' 사과' 로 단어 앞에 공백을 입력 하고 단어와 공백을 같이 선택하여 <alt+enter> 시에 한자 변환 cadidate가 뜨지 않는 문제가 발생
기대하는 정상 동작: 기존의 두벌식 키보드와 동일하게 단어 나 문장 앞에 공백이 있어도 한자나 이모티콘 변경 candidate가 떠야한다.
애플 기본 한글 입력기의 동작: 두벌식 키보드의 단어 한자 변환
재현 방법: ' 사과' 로 단어 앞에 공백을 입력 하고 단어와 공백을 같이 선택하여 <alt+enter>

**Comment by youknowone** [comment]
앞뒤로 공백은 제거하고 검색하면 좋겠습니다.

**Comment by Jae-eun** [comment]
@gaki2745 하시는건가요? 아니면 제가 하겠습니다~

**Comment by youknowone** [comment]
`HanjaComposer.buildHanjaCandidates()`에서 검색에 쓸 keyword 변수를 만들어서 검색을 하는데, 이 변수를 처리해 쓰면 됩니다

**Comment by gaki2745** [comment]
수정해서 pull request 하겠습니다~

**Comment by youknowone** [comment]
@gaki2745 그새 작업을 해버리신것 같아서, 다른 이슈 찾으시면 좋을 것 같아요 😢

**Comment by gaki2745** [comment]
아 올리셨군요 넵 알겠습니다~ !
