### ISSUE TITLE
전부 '과일'로 통일된 이모티콘 

### ISSUE THREAD

**Issue by eunjiChung** [gureum/gureum#607]
- macOS 버전: 10.14.6
- 구름 버전: 1.10.1
- 사용중인 한글/영문 배열: 두벌식 / 쿼티

- 문제가 있는 동작: 과일 이모티콘을 입력할때 전부 '과일'로만 통일돼 있음 
- 기대하는 정상 동작: 사과를 입력하면 사과 이모티콘이 뜨는 것
- 예상 문제 : DB가 업데이트됨

**Comment by yous** [comment]
참조: #474.

CLDR 저장소가 GitHub으로 이전했습니다. https://github.com/unicode-org/cldr/blob/master/common/annotations/ko.xml

**Comment by youknowone** [comment]
DB가 업데이트 된 것일수도 있고, 이모티콘 디비 처리하는 코드가 대표이름만 처리하고 나머진 처리 안하는거일수도 있을것 같습니다. 어느쪽이든 수정이 필요합니다.

**Comment by whitelips** [comment]
사과의 경우 아래와 같이 '빨간 사과'로 저장되어 있습니다.
- 빨간 사과:🍎:빨간 사과

검색의 문제로, '빨간' 또는 '빨간 사과'로 검색해야 리스팅됩니다.
#615 이슈와 같이 검색방법을 libhangul 에서 gureum 으로 변경해서 구현하면 해결될 내용입니다.

**Comment by youknowone** [comment]
#643 에서 fuzzy search 도입하면서 해결되었습니다.
