### ISSUE TITLE
CI에 swiftformat 도입하고 HACKING에 문서화

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#613]

**Comment by yous** [comment]
#610 PR에서 .travis.yml에 script 엔트리를 추가했으니 swiftformat을 추가하기 한결 쉬워졌을 겁니다. `Pods/`, `libhangul-objc/` 디렉터리만 빼고 돌리면 될 것 같네요. iOSApp, iOSShared 쪽에 고쳐야 할 게 좀 있는 것 같고요.

**Comment by presto95** [comment]
🙌

**Comment by youknowone** [comment]
iOS는 유지보수 안하고 있으니 검사하지 말고 그냥 놔둡시다
