### ISSUE TITLE
Emoji DB를 fuzzy search 방식으로 변경

### ISSUE THREAD

**Issue by JimJeon** [gureum/gureum#615]
#263 에서 @youknowone 님이 Comment 남겨주신 내용을 참고하여

> [fuse-swift](https://github.com/krisk/fuse-swift)를 이용해서 이모티콘 검색부분을 수정.

할 예정입니다.

**Comment by yous** [comment]
#643

**Comment by youknowone** [comment]
Fuzzy search는 도입되었으므로 #659 에 성능 이슈를 남기고 이 이슈는 닫겠습니다.
