### ISSUE TITLE
OBS  에서 한글 입력이 안되네요. 

### ISSUE THREAD

**Issue by koentrance** [gureum/gureum#626]
- macOS 버전: 10.14.6 
- 구름 버전: 1.10.1
- 사용중인 한글/영문 배열: 두벌식/쿼티
- 문제가 발생하는 애플리케이션 이름과 버전:  OBS 23.2.1 
- 문제가 있는 동작: OBS 실행 한글 입력이 안됩니다. 쉬프트 스페이스를 누르면 한칸이  뛰어지기만 하고 한글 입력으로 바뀌지 않습니다.  
OBS가 켜져 있는 상태에서는 크롬 등 다른 어플로가서 한글 전환을 시도해도 안됩니다. 
한글이 입력되는 유일한 때는  
커맨드 스페이스를 눌렀을 때  spotlight 검색 칸이 뜨고 그때는 한,영 전환이 유효하게 잘 됩니다. 
- 기대하는 정상 동작:  한글로 전환되어야 합니다. 
- 애플 기본 한글 입력기의 동작: 정상으로 한글 자판으로 입력이 잘 됩니다. 
- 재현 방법:

**Comment by soomtong** [comment]
OBS 가 뭔지 정보라도 좀 주시는게 어떨까요?
이슈를 올리는 기본적인 방법이라도 숙지하시고 요청하시면 좋겠습니다.

**Comment by youknowone** [comment]
주석 마크가 남아있어서 본문이 안보였던거 같습니다. OBS가 뭔지는 알려주셨으면 좋았을거 같은데 Open Broadcaster Software 같네요

**Comment by youknowone** [comment]
새로 올려주셔서 이전 리포트는 닫을게요 #627
