### ISSUE TITLE
tools/*.sh 에서 xcpretty를 optional로

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#628]
xcpretty는 빌드에 필수적인 도구가 아닌데도 설치하지 않으면 빌드스크립트를 실행할 수 없습니다.

xcpretty 가 있는 경우에만 사용하도록 할 수 있을 것입니다.

**Comment by yous** [comment]
`if command -v xcpretty >/dev/null` 등으로 확인할 수 있을 겁니다.

**Comment by youknowone** [comment]
저는 `which xcpretty` 해보는 방법을 생각했었네요

**Comment by yous** [comment]
둘 다 사용하는 데엔 별 문제 없을 거라고 봅니다. 여기 둘의 차이점에 대해 좀 설명되어 있습니다. https://stackoverflow.com/questions/592620/how-to-check-if-a-program-exists-from-a-bash-script

**Comment by yous** [comment]
#656
