### ISSUE TITLE
HanjaComposer와 EmoticonComposer 합치기

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#637]
처음 만들때는 한글/로마자 처리를 따로 해야해서 나눠 놨는데, 같은 일을 하는 코드가 중복이어서 결국 합쳐야 할 것 같습니다

모드 전환할때
- 레퍼런스할 원 입력기(한글 or 로마자)
- 검색할 후보 영역(한자/이모티콘 등)

을 넘겨서 검색하게 만들면 두 composer가 구분될 필요가 없어 보입니다

**Comment by presto95** [comment]
🙌

**Comment by yous** [comment]
#646
