### ISSUE TITLE
showsInputForHanjaCandidates 옵션 삭제

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#640]
옵션을 제거하고 맥 내장 입력기처럼 마지막에 후보를 덧붙이는 것으로 동작을 고정합니다

https://github.com/gureum/gureum/commit/7d86efcdb729db6076f06a71c048bca45aeeb442

**Comment by youknowone** [comment]
@presto95 저 커밋 cherry-pick 해서 올려주시면 될거 같습니다. 원하지 않으시면 알려주시면 제가 처리하겠습니다 :D

**Comment by presto95** [comment]
올렸습니다! 리베이스된 커밋도 해시값이 살아있는건가요?? 깃 로그 창에서 해시값을 확인할 수 있나요?

**Comment by youknowone** [comment]
`git gc` 돌려서 날리지 않으셨으면 로컬엔 살아있을거에요

**Comment by youknowone** [comment]
질문을 잘못 이해했던거 같네요. git reflog 해보셔요 최근 50개정도 볼 수 있어요

**Comment by presto95** [comment]
아 그걸로 찾으신건가요?? 생각보다 이전 기록들이 엄청 많이 나오네요 감사합니다!

**Comment by youknowone** [comment]
세 가지 다른 얘기가 섞여서 정리해 봅니다

1. 커밋 id 찾은건 그걸로 찾은건 아니고 이전에 원래 PR 올리셨을 때 따로 기록해 두었어요 https://github.com/gureum/gureum/issues/596#issuecomment-531532408

2. git gc 얘기는 제 로컬에는 없는 커밋이라 저걸 안다고 해서 cherry-pick 하거나 할 순 없고, 아마 @presto95 님 로컬 저장소에서는 가능할거라는 얘기였어요. (git gc하면 dangling commit이라 날아갑니다)
해보지는 않았지만, 아마 제가 받으려면 해당 PR을 제 로컬에 받으면 가능할거라는 생각이 듭니다.  참고: https://help.github.com/en/articles/checking-out-pull-requests-locally

git reflog는 HEAD가 이동한 경로에 관한 로그입니다. 제 HEAD는 저 커밋을 가리킨 적이 없으니 나오지 않겠지만, @presto95 님은 직접 작업을 하셨으니 로컬 저장소에서 reflog를 해보면 저 커밋이 어딘가 들어 있겠지요.

**Comment by presto95** [comment]
아아 이해했습니다!
