### ISSUE TITLE
카탈리나에서 Caps Lock으로 한영전환 안됨

### ISSUE THREAD

**Issue by psj8252** [gureum/gureum#664]
- macOS 버전: 10.15
- 구름 버전: 1.10.1
- 사용중인 한글/영문 배열: 세벌식 390/쿼티
- 문제가 발생하는 애플리케이션 이름과 버전: 입력기 전환
- 문제가 있는 동작: caps lock 키를 이용해서 구름 입력기 쿼티와 세벌식 390을 전환할 수가 없습니다. 정확히는 구름 입력기를 이용했을 때, Use the 한/영 key to switch to and from ABC 라는 옵션을 체크할 수가 없습니다. (맥의 기본 쿼티와 세벌식 자판을 이용했을 때는 해당 옵션을 사용할 수 있었고 체크하면 caps lock으로 전환이 가능했음)
- 기대하는 정상 동작: 구름 ime 를 사용했을 때도 caps lock으로 자판 전환이 가능하는 것
- 애플 기본 한글 입력기의 동작:
- 재현 방법: 
원래 mac 10.14에서 구름입력기의 세벌식 390과 쿼티만 있던 상태로 잘 쓰고 있다가 10.15로 업데이트를 하니 저렇게 됨.

**Comment by soomtong** [comment]
dup #569

**Comment by youknowone** [comment]
중복된 이슈여서 이쪽은 닫도록 하겠습니다. 이후의 트래킹은 링크된 #569 참고 부탁드립니다.
