### ISSUE TITLE
업데이트 알림창...

### ISSUE THREAD

**Issue by ginisnet** [gureum/gureum#676]
- macOS 버전: 10.11.6
- 구름 버전: 1.8.9c
- 사용중인 한글/영문 배열:
- 문제가 발생하는 애플리케이션 이름과 버전:
- 문제가 있는 동작:
- 기대하는 정상 동작:
- 애플 기본 한글 입력기의 동작:
- 재현 방법: 

업데이트 알림이 떠서 두어달 전에 업데이트 했다가
키보드가 제대로 동작하지 않아서 게시판 뒤져 어찌어찌 다시 다운그레이드 했습니다.
그 후로 그냥 잘 사용하고 있는데요.
켤때마다 매번 업데이트 알림창이 떠서 좀 불편합니다.

아래쪽 어딘가에 더 이전 버전에서 
업데이트 알림창 끄는 방법이 있길래 따라해봤는데...
안되네요.

방법이 없을까요?

**Comment by ginisnet** [comment]
뭘 봐야하는지 몰라서.... 요거면 될까요?

<img width="414" alt="스크린샷 2019-10-31 오전 8 56 52" src="https://user-images.githubusercontent.com/57201046/67992530-775b5b00-fc80-11e9-89cc-6130b8183094.png">
<img width="581" alt="스크린샷 2019-11-01 오전 8 20 03" src="https://user-images.githubusercontent.com/57201046/67992533-79bdb500-fc80-11e9-99d5-94697bb1220c.png">

**Comment by soomtong** [comment]
구버전 구름입력기를 수정하지 않고 문제를 해결할 수 있는 방법을 찾아봐야 할 것 같습니다.
우선 해결 되기 전까지 불편하시더라도 그냥 사용하는 방법밖에 없을 것 같아요.

**Comment by yous** [comment]
업데이트 확인할 때 기기의 macOS 버전에 따라 다르게 반응하도록 한다거나, 업데이트 확인을 자동/수동으로 변경할 수 있는 옵션을 만들 수도 있겠네요.

**Comment by youknowone** [comment]
이 문제는 다음 버전에는 수정하려 하지만 macOS 10.11은 지원하지 못할 것 같습니다. 이 이슈를 참고해서 업데이트 서버 접근을 차단해서 알림 창을 뜨지 않도록 막으실 수 있습니다.
