### ISSUE TITLE
드보락 자판이 추가되면 좋겠습니다.

### ISSUE THREAD

**Issue by winslows11** [gureum/gureum#68]
안녕하세요, 맥에서 편리하게 쓸 수 있는 구름 입력기가 있어 참 감사할 따름입니다.
다름이 아니라 현재 구름 입력기에는 영문 드보락 자판이 존재하지 않아 Shift+Space로 드보락-한글간 전환이 불가능한데요, 혹시 드보락 자판도 내장하실 계획이 없는지 궁금합니다.
드보락 사용자가 많지는 않지만 적잖이 있는 것으로 아는데, 많은 도움이 되리라 생각합니다.
참, 가능하다면 맥 OS 기본 입력기의 Dvorak에 해당하는 일반 드보락 자판과 단축키는 쿼티를 따라가는 드보락 자판 (Dvorak - Qwerty ⌘) 두 종류가 모두 있으면 좋겠습니다.
다시 한 번 감사드립니다. 늘 건승하세요!

**Comment by wsshin** [comment]
두벌식 상태에서 드보락 기준 단축키를 입력하는 것은 "애월입력기"라는 것을 쓰면 가능한 모양이더군요.  하지만 세벌식 상태에서 드보락 기준 단축키를 입력하는 것은 아직까지 바람입력기에서만 가능합니다.
저도 그래서 아직까지 바람입력기를 쓰고 있는데, OS를 요세미티로 업그레이드 하고나서부터는 바람입력기의 여러 가지 버그 때문에 쓰기가 짜증나는 경우가 많네요...  
저도 구름입력기에서 드보락을 지원하기 시작하면 바로 갈아타려고 합니다.
