### ISSUE TITLE
맥 카탈리나 미리알림 한글 자모 분리현상

### ISSUE THREAD

**Issue by thecminus** [gureum/gureum#686]
- macOS 버전: 10.15.1(19B88)
- 구름 버전: 10.15.1(19B88)
- 사용중인 한글/영문 배열: 구름 두벌식 / U.S
- 문제가 발생하는 애플리케이션 이름과 버전: 미리알림
- 문제가 있는 동작: 미리 알림 앱에서 한글 작성시 자모 분리
- 기대하는 정상 동작: 정상적인 한글 입력
- 애플 기본 한글 입력기의 동작: 미리알림 앱에서 자모 분리 없이 쓰여집니다.
- 재현 방법: 미리 알림 앱에서 새로운 이벤트 생성 후, 입력할 때 -> 할 일 이라고 치면 ㅎ ㅏ ㄹ ㅇ ㅣㄹ  
이렇게 쓰여집니다.

<!--
버그 신고의 경우 위 서식을 가능한 채워서 제출해 주시면 큰 도움이 됩니다.
채울 수 없는 칸은 비워 두셔도 됩니다.

유료 애플리케이션 및 Cocoa가 아닌 앱의 호환성 문제는 빠른 시일 내에 해결되지 않을 수 있습니다.
내장 한글 입력기와 구름 입력기에서의 동작을 비교 확인해 주세요.
두 입력기에서 동시에 발생하는 같은 오류는 입력기가 아닌 애플리케이션의 오류일 가능성이 높습니다.

**Comment by yous** [comment]
제보 감사합니다. 현재 10.15.1에서 재현되는데, 구름 버전은 1.10.1인가요? 일단 #682 이슈와 동일해보입니다.
