### ISSUE TITLE
1.11.0 개발자 2버전의 환경설정이 아에 동작하지 않습니다.

### ISSUE THREAD

**Issue by practice0507** [gureum/gureum#697]
- macOS 버전: macOSX 10.12.2
- 구름 버전:  1.11.0 개발자2
- 사용중인 한글/영문 배열: 두벌식 쿼티
- 문제가 발생하는 애플리케이션 이름과 버전: 구름 입력기
- 문제가 있는 동작: 오른쪽 커맨드키 한영 전화은 물론이고 환경설정 자체가 적용이 안됨.
- 기대하는 정상 동작: 구름 입력기 환경설정에서 체크한것들이 저장되고 제대로 동작.
- 애플 기본 한글 입력기의 동작: 이상없음.
- 재현 방법: 
 상단 메뉴바에서 입력기 누르고 환경설정에 들어가 오른쪽 커맨드키를 한영키로 사용하고 싶은데
사용이 되고 안되고도 있지만 체크를 해도 구동도 안되고 체크 된 상태로 닫아도 다시 체크가 풀려있습니다.
그리고 내부 단축키 설정에서도 오른쪽에 아무것도 안뜸니다. 권한 이나 모니터링 문제인가 싶어서 모니터링 옵션은 체크 했다 안했다고 해보고 해봤는데 변화가 없습니다.

**Comment by yeonho1** [comment]
해당 버그를 수정했습니다. (코드 한 줄만 변경하였더니 잘 작동하더군요) pull request 711번을 참고해주세요.

**Comment by hobeats** [comment]
전 여전히 안되네요.. ㅠ

**Comment by youknowone** [comment]
수정된 버전 테스트해보실 수 있는 실험버전 다운로드 링크입니다

https://github.com/gureum/gureum/releases/download/GureumKIM-1.11.0-experimental/Gureum-1.11.0-experimental3.pkg

**Comment by youknowone** [comment]
업데이트가 포함된 새 버전을 배포하였습니다. https://github.com/gureum/gureum/releases/tag/1.11.1
