### ISSUE TITLE
카카오톡에서 구름입력기 선택 불가능 

### ISSUE THREAD

**Issue by n0chatt3r** [gureum/gureum#699]
- macOS 버전: 카타리나 10.15.2
- 구름 버전: 1.10.0
- 사용중인 한글/영문 배열: 두벌식(한글)
- 문제가 발생하는 애플리케이션 이름과 버전: 카카오톡(최신)
- 문제가 있는 동작: 구름 입력기 변경 작동 안함
- 기대하는 정상 동작: 구름입력기 선택 가능
- 애플 기본 한글 입력기의 동작: 기본입력기 정상 동작 
- 재현 방법:

1. 카카오톡 채팅창 실행
2. 구름입력기로 변경 시도

**Comment by n0chatt3r** [comment]
처음 설치 후 재부팅 하지않고 바로 사용하였을때 문제 발생 - 
재부팅 후 정상적으로 작동됨을 확인.

**Comment by roeniss** [comment]
이 이슈 덕분에 해결했습니다. 

이 부분 제가 문서에 좀 추가해도 될까요? @n0ch4t

**Comment by n0ch4t** [comment]
네넹 아직 해결이 안되었나 보네요 ㅠㅠ @roeniss

**Comment by roeniss** [comment]
반영 완료했습니다
