### ISSUE TITLE
1.10.1 카탈리나 관련 이슈 목록

### ISSUE THREAD

**Issue by elensar92** [gureum/gureum#701]
- macOS 버전: 카탈리나 10.15.3 
- 구름 버전: 1.10.1
- 사용중인 한글/영문 배열: 세벌식 최종 / 두벌식 / 영문
- 문제가 발생하는 애플리케이션 이름과 버전: Sublime Text 3
- 문제가 있는 동작: 사용하다 보면 어느 순간부터 한영 전환이 되더라도 영문만 입력됨
구름 입력기 소스가 아닌 기본 입력기 사용한 소스들은 정상 동작
- 기대하는 정상 동작:
- 애플 기본 한글 입력기의 동작: 정상
- 재현 방법: 

그릭고 세벌식의 모아치기 기능을 쓸수가 없습니다. 설정을 할 수 있는 텝 자체가
없어졌습니다

**Comment by yeonho1** [comment]
설정의 경우에는 1.11.0 experimental2 버전에서 환경설정이 구름 메뉴에 생겼습니다. 다만, 한영 전환이 되더라도 영문만 입력되는 현상은 발견하지 못했습니다.

**Comment by youknowone** [comment]
사라진 환경설정을 복구하였습니다. 수정된 버전 테스트해보실 수 있는 실험버전 다운로드 링크입니다.

https://github.com/gureum/gureum/releases/download/GureumKIM-1.11.0-experimental/Gureum-1.11.0-experimental3.pkg

**Comment by youknowone** [comment]
환경설정이 업데이트가 포함된 새 버전을 배포하였습니다. 영문만 입력되는 것은 내부적으로 입력기가 크래시를 겪는 경우이므로 새 버전에서도 다시 발생하면 알려주세요.

https://github.com/gureum/gureum/releases/tag/1.11.1
