### ISSUE TITLE
환경설정이 표기되지 않는문제

### ISSUE THREAD

**Issue by harryhan24** [gureum/gureum#703]
- macOS 버전: 10.15.3
- 구름 버전: 1.10.1
- 사용중인 한글/영문 배열: Han 2set / Unicode
- 문제가 발생하는 애플리케이션 이름과 버전: -
- 문제가 있는 동작:환경설정이 표기되지않습니다.
![image](https://user-images.githubusercontent.com/20278882/74832682-2ec4cc00-535b-11ea-8f80-937df63f88cd.png)

- 기대하는 정상 동작: 환경설정이 정상적으로 수정할 수 있는상태
- 애플 기본 한글 입력기의 동작: - 
- 재현 방법: 
brew cask install gureumkim로 설치 완료 후 재시작 -> 환경설정확인하기

##### 이외에 해결을 위해 사용했지만 안되었던 방법
- 이전버전인 1.10.0으로 설치하기
- brew가 아닌 직접 릴리즈 패키지를 다운받기

항상 정말 잘쓰고있습니다. 이슈에 등록된 비슷한 사례들과 관련하여 답글달아주신 내용들을 쭉한번 적용을 해보았는데 여전히  표기되지않아 어려움이 있어 이슈를 작성하였습니다. 혹시라도.. 해결할 수 있는 방법을 알려주시면 바로 테스트해보겠습니다. 

혹시라도 도움됙실지 모르겠지만 콘솔에 구름입력지 패키지명과 관련하여서는 설정메뉴를 열때마다
아래와같은 로그가 찍히는것같습니다.
register name: com.apple.inputmethodkit.abnormaldeath object: org.youknowone.inputmethod.Gureum token: f45d0 pid: 1302

**Comment by yeonho1** [comment]
카탈리나에서는 시스템 환경설정에서 설정이 뜨지 않습니다. 1.11.0 experimental2 버전으로 업데이트 하신 뒤, 구름 입력기로 입력할 수 있는 상태에서 구름 로고 > 환경설정 클릭하시면 구름 입력기를 설정할 수 있습니다.
