### ISSUE TITLE
세벌식에서 "이중 모음 정석 강요" 옵션 추가 필요. 

### ISSUE THREAD

**Issue by nowage** [gureum/gureum#71]
세벌식 모아치기는 정말 편하고 좋은 기능입니다. 그러나, 모아치기 기능이 제대로 구현되기 위해서는 이중 모음 정석 강요 기능 옵션이 구현되어야 합니다. 
예를 들면, 
"아자"를 ㅇ,ㅏ,  ㅏ,ㅈ 의 순으로 입력하던 ㅏ,ㅇ,  ㅈ,ㅏ의 순으로 입력하던 상관업이 "아자"로 입력 됩니다. 그래서,타이핑할 때 톡톡 두번의 소리만 들렸는데 글자 두개가 입력됩니다. 이중 모음이 안쓰였을 때는 이렇게 경쾌하게 입력이 되는데, 
"오이"를 입력할 때는 ㅇ,ㅗ,  ㅣ,ㅇ라고 입력하면 "외ㅇ"라고 입력되어 이중모음(ㅗ,ㅜ,ㅢ)을 입력 할때는 모아치기가 사실상 불가능해 집니다. 
따라서 모아치기가 가능하려면 ㅗ,ㅜ모음이 이중모음으로 쓰일때는 오른손 자판에 있는 /(ㅗ),9(ㅜ),8(ㅢ)를 써야만 입력이 가능하게 "이중 모음 정석 강요"옵션이 필요합니다. 옵션기능이 아니더라도 대부분의 세벌식 유저가 이중모음 정석 강요 방식으로 타이핑을 하거나 해야 하기 때문에  세벌식 최종 자판은 이중모음 정석강요 방식으로 바꿔주시면 감사하겠습니다.

**Comment by youknowone** [comment]
최신 베타에서 `세벌식 정석 강요` 옵션이 추가되었습니다.

https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre9

**Comment by youknowone** [comment]
1.10을 정식으로 릴리즈하였습니다. 문제가 지속되면 다시 알려주세요. https://github.com/gureum/gureum/releases/1.10.0
