### ISSUE TITLE
한/영 변환을 1.8.5. 때처럼 업데이트 가능할까요 (오히려 현재 가장 안정적)

### ISSUE THREAD

**Issue by fahr27** [gureum/gureum#712]
- macOS 버전: 10.15.3.
- 구름 버전: 1.8.5.
- 사용중인 한글/영문 배열: shift space
- 문제가 발생하는 애플리케이션 이름과 버전: shift space 한영전환이 어플 자체에서 되지 않고 맥 자체 설정 변경해야함 (1.10.1 이후)
- 문제가 있는 동작: shift space 동작이 맥 자체에서 설정되면 크롬 원격접속, 페러랠즈 등 다른 앱에서 shift space로 한영전환 불가
- 기대하는 정상 동작: 1.8.5. 처럼 자체적으로 shift-space 설정 (맥 설정 건드리지 않고)
- 애플 기본 한글 입력기의 동작: ctrl-space 설정 그대로 --> 1.8.5. 설치 후 shift-space로 자동 작동
- 재현 방법: 

1. 사용환경 : MBP16 + parallels 15 (윈도우 10) + 크롬원격데스크톱

1) 구름 1.10.1. 에서는 자체환결설정이 없음, 맥설정 (키보드-단축키-입력소스)에서 shift-space로 변경 필요
    - parallels 15에 설치된 윈도우 10도 shift-space 설정되어 있음
      그러나 맥 자체설정에서 shift-space로 된 경우 parallels-윈도우10에서는 shift-space로 한영 불가
      크롬원격데스크톱으로 접속하는 원격기기도 shift-space 한영전환 되어있음. 이 경우 parallels와 마찬가지로 맥에서 shift-space로 된 경우 한영전환 불가

2) 구름 1.8.5. 설치함
     이 경우 MBP-parallels-크롬원격 모두에서 shift-space로 한영 전환 가능
     CAPS-lock 한영 전환이 저절로 꺼짐 (설정에 체크되어 있음에도 불구하고)

3) 사용한지 오래된 맥미니 (구름-페러렐즈-크롬원격 환경 동일)에서는 예전 구름 버젼부터 업그레이드 해왔는데, 희안하게도 현재 맥미니에 설치된 구름은 1.10인데도 shift-space 사용에 지장이 없습니다 (맥설정 바꾸지 않아도). 아마도 1.8.5. 설정이 저장된(?)채로 맥과 구름이 같이 업데이터 되어서 그런게 아닌가... 잠시 생각을.

1.8.5. 때처럼 맥 설정 자체에서 shift-space로 바꾸지 않아도 사용할 수 있도록 만들어주시면 안될까요 ㅠㅜ
현재 1.8.5.로 다운그레이드 해서 정말 잘 사용하고 있습니다.

**Comment by soomtong** [comment]
제목을 조금 다듬었습니다.

**Comment by youknowone** [comment]
새 버전에서 다음과 같이 업데이트하겠습니다.

![image](https://user-images.githubusercontent.com/69878/85588574-c32e9a80-b67d-11ea-95da-dad496cb10fb.png)

**Comment by fahr27** [comment]
감사합니다!



2020년 6월 25일 (목) 오전 12:50, Jeong YunWon <notifications@github.com>님이 작성:

**Comment by youknowone** [comment]
수정된 버전 테스트해보실 수 있는 실험버전 다운로드 링크입니다

https://github.com/gureum/gureum/releases/download/GureumKIM-1.11.0-experimental/Gureum-1.11.0-experimental3.pkg

**Comment by JaehJeong** [comment]
Catalina 10.15.5 에서 정상적으로 잘 작동합니다.
그리고 이번 실험 버전에서 구름환경설정으로 바로 갈 수 있어서 정말 편합니다.
그리고 자세한 설명까지 있어서 처음 사용하는 사람도 편하게 세팅을 할 수 있을 듯 합니다.

잘 반영해 주셔서 정말 감사합니다.

**Comment by youknowone** [comment]
새 버전을 정식 배포하였습니다 https://github.com/gureum/gureum/releases/tag/1.11.1

**Comment by JaehJeong** [comment]
저도 좀전에 메일 받았어요 ㅎ

*
*

*Jae Ho Jeong, M.D.*

Clinical Assistant Professor

Department of Oncology

Asan Medical Center

88, Olympic-ro 43-gil, Songpa-gu, Seoul, 05505, Republic of Korea

Tel: +82-2-3010-3223, Fax: +82-2-3010-6961

E-mail: jaeho.jeong@amc.seoul.kr or imdrho@gmail.com
