### ISSUE TITLE
option 키를 이용한 특수문자(영문액센트) 입력기능 문제

### ISSUE THREAD

**Issue by windburial** [gureum/gureum#715]
- macOS 버전: 10.15.5
- 구름 버전: 1.11.0-experimental3
- 사용중인 한글/영문 배열: 한글 세벌식최종 / 영문 Dvorak
- 문제가 발생하는 애플리케이션 이름과 버전: 특수문자(option 조합) 입력기능 영문모음액센트 입력(â, ô, ü, ã 등)

- 문제가 있는 동작: 하기 재현방법 참조
- 기대하는 정상 동작: 하기 재현방법 참조

- 애플 기본 한글 입력기의 동작: 영문입력기 문제이므로 별도 한글입력기 정상동작 없음

- 재현 방법: 
1. 텍스트 입력프로그램 구동(프로그램 불문)
2. 구름 내장 영문자판 선택
3. option 키를 누른 상태에서 i 를 눌렀다 뗀 후 a 를 타건 (이하 option+i, a 형식으로 표기).
_ 기대되는 입력(맥OS 기본 영문입력기上 입력값) â ≠ 실제입력 a.
_ option+[einu], [aeiou] 군에서 동일 현상 발생(ê,ó,ã,ü 대신 e,o,a,u 입력 / option+n, [eiu] 제외(해당 문자는 기본입력기도 미지원)).
_ 참고1: 한글자판 상태에서 option+i, a 타건 시  ˆㅇ  입력됨.
_ 참고2: 상기 현상은 dvorak에서 발생 확인하였으나, qwerty에서도 동일현상 재현 예상됨. 
_ 참고3: 현재 experimental3 내 기능인 시스템자판(로마자) 지정으로 해당 현상 우회하여 사용 중. 끝.

**Comment by youknowone** [comment]
참고3에서 언급해 주신대로 로마자 자판으로 통해 해결되는 문제이고, 별도로 수정은 하지 않으려고 합니다. 대신 새 버전부터 로마자 자판을 기본으로 권장하고 있고, 별다른 문제가 없으면 나머지 자판은 제거하려고 합니다. 리포트 감사합니다!

로마자 자판이 포함된 1.11.1: https://github.com/gureum/gureum/releases/tag/1.11.1
