### ISSUE TITLE
세벌식 커뮤니티 자판 지원을 요청드립니다. ㅜㅜ

### ISSUE THREAD

**Issue by jongsinyang** [gureum/gureum#727]
- macOS 버전:10.15.6(19G73)
- 구름 버전: 10.15.6(19G73)
- 사용중인 한글/영문 배열: 신세벌식P2
- 문제가 발생하는 애플리케이션 이름과 버전:
- 문제가 있는 동작: 환경설정 창 노출 없음
- 기대하는 정상 동작: 카탈리나 OS 지원
- 애플 기본 한글 입력기의 동작:
- 재현 방법: 

안녕하세요, 구름입력기에 입문해서 잘 사용하고 있습니다.
제가 사용하는 키보르가 작아서 신세벌식P2 를 이용하고 있습니다.

최근 구름입력기 정식 버전이 출시되었습니다. 
노고에 감사드립니다.

다만, 신세벌식P2를 비롯하여 커뮤니티 자판 지원이 되지 않아 여전히 그림의 떡입니다.
개발에도 문외한이라 ㅜ―ㅜ
세벌식 커뮤니티 자판 지원을 요청드립니다. ㅜㅜ

**Comment by yous** [comment]
안녕하세요, 구름 입력기의 버전은 다음 방법으로 알 수 있습니다.

구름 입력기를 사용하는 상태에서 메뉴 바의 구름 입력기 아이콘 클릭 → '구름 입력기에 관하여' 클릭

<img width="187" alt="Screenshot 2020-08-06 11 50 16" src="https://user-images.githubusercontent.com/853977/89485134-10ed0580-d7db-11ea-8642-7a8df52e9d51.png">
<img width="284" alt="Screenshot 2020-08-06 11 50 26" src="https://user-images.githubusercontent.com/853977/89485140-15192300-d7db-11ea-9d5f-37d96a91df4c.png">

1.11.1 버전부터 '환경설정...' 메뉴가 추가되었으니 여기에서 환경설정을 하실 수 있습니다.

최근 1.11.1 버전이 출시된 후 세벌식 커뮤니티 자판을 추가하여 1.11.1-contrib 버전을 따로 빌드하였으니 참고해주세요.
https://github.com/gureum/gureum/releases/tag/1.11.1-contrib

이 버전에 문제가 있다면 이슈로 알려주시기 바랍니다.

**Comment by jongsinyang** [comment]
안녕하세요. 넵
제가 미처 cotrib 버전 업데이트 확인을 못하고 글을 올렸습니다.

올리고 확인을 하니 업데이트가 되어있더라고요, ㅜ
번거롭게 해드려 죄송합니다.

노고에 감사드립니다!
