### ISSUE TITLE
자판 전환 단축키 비활성화 기능

### ISSUE THREAD

**Issue by yous** [gureum/gureum#73]
자판 전환을 Cmd + Space로만 하고 싶습니다. 구름의 자판 전환 단축키를 끌 수 있었으면 좋겠습니다.

**Comment by youknowone** [comment]
다음 버전부터 자판 설정에 X 버튼이 추가되어 단축키를 지울 수 있습니다. 테스트버전은 다음 링크에서 받아보실 수 있습니다 https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre1
