### ISSUE TITLE
방향키로 한자 목록 이동에 오류가 발생합니다

### ISSUE THREAD

**Issue by mingminging** [gureum/gureum#731]
- macOS 버전: 10.15.6
- 구름 버전: 1.11.1
- 사용중인 한글/영문 배열: 두벌식/로마자
- 문제가 발생하는 애플리케이션 이름과 버전: 
- 문제가 있는 동작: 옵션+엔터로 한자/이모티콘 목록에 진입 후 방향키로 목록을 내리면 1번에서 2번항목으로 가는 것이 아니라 목록이 건너뛰어서 저 아래있는 한자로 이동이됩니다. 
- 기대하는 정상 동작: 방향키로 1번에서 2번 항목으로 이동이 원활하게 되었으면 좋겠습니다. 
- 애플 기본 한글 입력기의 동작:
- 재현 방법: 
구 입력 
옵션+엔터 입력
한자목록에서 2번째에 있는 입 구를 입력하기 위해 아래 방향키 입력
스크롤이 갑자기 4/5지점으로 이동하면서 언덕 구로 이동 

언덕 구가 선택 되는 것이 아니라 입 구가 선택되었으면 좋겠습니다.
-->
![화면-기록-2020-09-08-오후-6 20 33](https://user-images.githubusercontent.com/47773613/92458568-88f68300-f200-11ea-816a-9b9abe125754.gif)

**Comment by yous** [comment]
디버그 버전에선 재현되지 않고 릴리스 버전에선 재현되어 원인이 뭔가 보니 '九: 아홉 구' 항목이 목록에 두 개 존재해서, 아래 방향키를 누르는 순간 두 번째 '九: 아홉 구'의 다음 항목이 선택됩니다.
