### ISSUE TITLE
네이버 검색창에 한글로 검색시 첫 자음이 영어로 입력됩니다.

### ISSUE THREAD

**Issue by hankooksaram** [gureum/gureum#733]
- macOS 버전: 10.15.6
- 구름 버전: 1.11.1
- 사용중인 한글/영문 배열: 두벌식/쿼티
- 문제가 발생하는 애플리케이션 이름과 버전: 모든 인터넷 브라우저에서 네이버 검색창
- 문제가 있는 동작: 네이버에서 검색할 때 첫 글자(자음)가 영어로 나오는 현상
- 기대하는 정상 동작: 첫 글자가 바뀌지않고 정상적으로 입력됐으면 좋겠습니다.
- 애플 기본 한글 입력기의 동작: 동일 상황에서 애플 기본 한글 입력기에서는 첫 글자가 ㅇㅏㄴ녕 이런식으로 분리되는 현상이 있어서 구름 입력기를 깔았는데 구름 입력기도 위 문제로 인해 해결책이 되지 못 했음.
- 재현 방법: 
첫 번째 방법)
네이버 홈에 들어가면 기본적으로 검색창에 키보드 커서가 깜빡이고 있습니다. 이때 좌우 빈 여백 공간 아무데나 클릭을 하면 그 깜박임이 사라집니다. 이 때 키보드에서 입력을 하면 자동으로 검색창에 입력이 되는데 이때 키보드가 한글로 되어 있어도 첫 글자(자음)이 영어로 나옴 ex) '안녕' 을 치면 'dㅏㄴ녕' 이렇게
두 번째 방법)
혹은 네이버 홈에서 어떤 단어를 검색 후, 따로 마우스를 움직이지 않고 바로 키보드 자판을 쳐서 새로운 검색어를 입력하면 자동으로 검색창에 쓰여있던 기존 검색어가 지워지고 새로 쓴 검색어가 입력이 되는데, 이때 키보드가 한글로 되어 있어도 첫 글자(자음)이 영어로 나옴 ex) '안녕' 을 치면 'dㅏㄴ녕' 이렇게

**Comment by yous** [comment]
네이버 PC 버전에서 쓰는 스크립트 때문인 것 같은데요, 아래는 <https://pm.pstatic.net/dist/js/nmain.58c827fd.js?o=www> 내용의 일부입니다.

검색창 바깥에 포커스가 있을 때 0~9, a~z 키를 입력하면 검색창으로 포커스를 주는 것 같은데요, 그 과정에서 누른 글자는 영어로 입력되는 것 같습니다. 이건 맥 기본 한글 입력기로도 동일하고 윈도우에서도 현상이 똑같은 걸로 보아 네이버 사이트의 개선이 필요해보입니다.

``` javascript
Mi = function () {
  ee.a.isIEJS() ? document.documentElement.scrollTop = 0 : window.scrollTo(0, 0)
},
Pi = function () {
  document.getElementById('query').focus()
},
Oi = function () {
  setTimeout((function () {
    Pi()
  }), 100),
  a() (document).on('keydown', (function (e) {
    var t = e.key,
    n = e.altKey,
    i = e.ctrlKey,
    r = e.shiftKey,
    o = e.metaKey,
    l = e.keyCode;
    if (t && (!t || !(n || i || r || o))) {
      var c = a() (document.activeElement);
      0 !== c.length && 'query' !== c.attr('id') && (c.hasClass('ts_s_input') || function (e) {
        return e >= 48 && e <= 57 || e >= 65 && e <= 90
      }(l) && ('query' !== c.attr('id') && a() ('#query').val(''), window.innerWidth < 1200 && Mi(), Pi()))
    }
  }))
},
```

**Comment by youknowone** [comment]
버그 리포트를 해보았는데, 웹브라우저에서 한글 입력으로 처리할 적당한 방법을 제공하지 않는 관계로 알려진 이슈로 두고 수정 계획은 없다고 합니다.

**Comment by hankooksaram** [comment]
> 네이버 PC 버전에서 쓰는 스크립트 때문인 것 같은데요, 아래는 https://pm.pstatic.net/dist/js/nmain.58c827fd.js?o=www 내용의 일부입니다.
> 
> 검색창 바깥에 포커스가 있을 때 0-9, a-z 키를 입력하면 검색창으로 포커스를 주는 것 같은데요, 그 과정에서 누른 글자는 영어로 입력되는 것 같습니다. 이건 맥 기본 한글 입력기로도 동일하고 윈도우에서도 현상이 똑같은 걸로 보아 네이버 사이트의 개선이 필요해보입니다.
> 
> ```js
> Mi = function () {
>   ee.a.isIEJS() ? document.documentElement.scrollTop = 0 : window.scrollTo(0, 0)
> },
> Pi = function () {
>   document.getElementById('query').focus()
> },
> Oi = function () {
>   setTimeout((function () {
>     Pi()
>   }), 100),
>   a() (document).on('keydown', (function (e) {
>     var t = e.key,
>     n = e.altKey,
>     i = e.ctrlKey,
>     r = e.shiftKey,
>     o = e.metaKey,
>     l = e.keyCode;
>     if (t && (!t || !(n || i || r || o))) {
>       var c = a() (document.activeElement);
>       0 !== c.length && 'query' !== c.attr('id') && (c.hasClass('ts_s_input') || function (e) {
>         return e >= 48 && e <= 57 || e >= 65 && e <= 90
>       }(l) && ('query' !== c.attr('id') && a() ('#query').val(''), window.innerWidth < 1200 && Mi(), Pi()))
>     }
>   }))
> },
> ```

맥 기본 한글 입력기는 영어로 바뀌지는 않고 자소가 분리 되더라고요.. 그리고 윈도우에서는 아무 이상 없이 잘 입력이 되긴 합니다 ㅠ
