### ISSUE TITLE
Reminder 앱에서 받침을 입력할 때 자모가 분리되어 떨어져 나오는 이슈

### ISSUE THREAD

**Issue by jeyraof** [gureum/gureum#749]
- macOS 버전: 10.15.7
- 구름 버전: 1.11.1
- 사용중인 한글/영문 배열: Roman / Han 2 Set
- 문제가 발생하는 애플리케이션 이름과 버전: Reminder.app
- 문제가 있는 동작: 한글의 받침을 입력할 때 받침이 분리되어 떨어져 나온다.
- 기대하는 정상 동작: 정상 작동
- 애플 기본 한글 입력기의 동작: 정상 작동
- 재현 방법: 

1. Reminder.app 에서 새 아이템을 누른다.

2. 기본적인 받침없는 자/모 에서는 아주 잘 된다.
<img width="302" alt="image" src="https://user-images.githubusercontent.com/2032880/101421519-ce2d6c80-3937-11eb-8eb4-e8f388e3fad0.png">

3. `간다` 를 입력하기 위해 "간" 을 입력한 상태에서 "ㄷ", "ㅏ" 를 순차적으로 누르면
<img width="105" alt="image" src="https://user-images.githubusercontent.com/2032880/101421600-fc12b100-3937-11eb-903d-f872ab4a1b81.png"> -> <img width="99" alt="image" src="https://user-images.githubusercontent.com/2032880/101421589-f3ba7600-3937-11eb-8f15-ff82aefdef72.png">

4. 기대값은 "간다" 가 입력 되어야 한다.

**Comment by yous** [comment]
#682 이슈와 같은 현상 같습니다. 일단 Big Sur에서는 다시 고쳐진 것 같네요.

**Comment by jeyraof** [comment]
제 기준 @yous 님이 적어주신대로 Big Sur 로 올린 후부터 잘 작동합니다. 감사합니다.
