### ISSUE TITLE
MacOs 빅서 11.2 버전 업데이트 후 작동하지 않습니다.

### ISSUE THREAD

**Issue by ksgu2011** [gureum/gureum#759]
- macOS 버전: 
- 구름 버전: 
- 사용중인 한글/영문 배열: 
- 문제가 발생하는 애플리케이션 이름과 버전: 
- 문제가 있는 동작:
- 기대하는 정상 동작:
- 애플 기본 한글 입력기의 동작:
- 재현 방법: 

**맥북 m1 사용자입니다. 빅서 11.1버전까지는 작동 잘 하던 구름입력기가 
얼마전 업데이트가 된 빅서 11.2버전 업데이트 후 환경설정 나타나지 않고 작동불가로 뜹니다.
재설치 후에도 마찬가지 입니다. 수정 부탁드립니다.**

**Comment by ksgu2011** [comment]
빅서 업데이트 11.1에서 11.2 업데이트 후 구름입력기 클린설치 해주면 되더군요.

업데이트 후 손쉬운 설정 부터 모두 다 재설치 해야 잘 되네요.

순간 당황했었습니다~

**Comment by borndust** [comment]
m1에서도 구름입력기 되냐고 물어보려고 쓸랬더니.  마침 자문자답 하신게 있군요.
