### ISSUE TITLE
1.7.0 일부 어플에서 입력 문제

### ISSUE THREAD

**Issue by kndol** [gureum/gureum#76]
Mavericks 10.9.2의 문제인지 구름 입력기의 문제인지 모르겠지만, 일부 어플에서 입력에 문제가 있습니다.
1. 한글로 표시되어 있지만 영문이 입력됩니다. - 이때 구름 입력기 아이콘을 클릭 후 다시 입력 창에 돌아오면 한글이 입력됩니다.
2. 엔터키가 제대로 안 먹는 문제 - 엔터키를 입력해서 내용을 전송하는 페이스북 앱 등에서 엔터키를 두번 눌러야 내용 전송이 일어납니다. 이 때 내용에는 줄바꿈이 한번 들어간 상태로 저장됩니다. 지금 이 글을 쓰는 중에도 글 끝에서는 엔터키를 두번 눌러야 줄 바꿈이 됩니다.
3. 백스페이스, delete 키 문제 - 한글 입력 시에 백스페이스와 delete 키가 정상적으로 동작하지 않습니다. 한글자 정도 지운 뒤에 더 이상 글자가 지워지지 않습니다. 영문 입력기로 바꾸면 백스페이스와 딜리트 키가 동작하는데, 이 때 한글 상태에서 백스페이스/딜리트 키를 눌렀던 만큼 특수 문자가 입력되어 있는지, 보이지 않는 문자를 그만큼 지워줘야 합니다.​
4. '​구름 입력기에 관하여'나 '업데이트 확인'을 클릭하면 창이 항상 백그라운드에 떠서 떴는지 확인하려면 앞의 창을 이동해서 봐야 하는 문제가 있습니다.​

**Comment by youknowone** [comment]
관련된 설정이 유지보수가 불가능한것으로 생각해 제거하였습니다
