### ISSUE TITLE
기본 영어 입력기 제거 방법

### ISSUE THREAD

**Issue by jeyraof** [gureum/gureum#768]
- macOS 버전: 11.2.3
- 구름 버전: 1.11.1
- 사용중인 한글/영문 배열: 
- 문제가 발생하는 애플리케이션 이름과 버전:
- 문제가 있는 동작:
- 기대하는 정상 동작:
- 애플 기본 한글 입력기의 동작:
- 재현 방법:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/2032880/121102995-d52b2e00-c839-11eb-9f87-0434b41237c6.png">

https://github.com/gureum/gureum/wiki/Usage-Tip#%EA%B8%B0%EB%B3%B8-%ED%82%A4%EB%B3%B4%EB%93%9C-%EB%A0%88%EC%9D%B4%EC%95%84%EC%9B%83--us-%EB%A5%BC-%EC%A0%9C%EA%B1%B0%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95
과거 작성했던 기본 영어 입력기 제거하는 방법을 수행하기 위해 더이상 일본어 입력기를 추가해도 - 가 활성화 되지 않네요.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/2032880/121103102-0efc3480-c83a-11eb-8cd4-df989d7103cb.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/2032880/121103105-11f72500-c83a-11eb-821b-9db0844e268b.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/2032880/121103119-19b6c980-c83a-11eb-89a3-db63354f3973.png">

다른 방법이 있을까요?

**Comment by jeyraof** [comment]
첨언으로 U.S. 입력기와 ABC 입력기는 함께 있을때 서로 제거가 됩니다.

**Comment by yous** [comment]
이 블로그 글과 같이 해보시기 바랍니다. http://blog.naver.com/tears0091/222168082799

1. 일본어 - 가나 자판 추가
2. 일본어 - 가나 자판 옵션에서 Romaji 체크
3. 영문 자판 제거
4. 일본어 - 가나 자판 제거

**Comment by jeyraof** [comment]
@yous 잘 됩니다. 감사합니다.
