### ISSUE TITLE
커스텀 자판 추가하기 알려주세

### ISSUE THREAD

**Issue by borndust** [gureum/gureum#769]
몇페이지 앞의 커스텀 자판 추가 이슈는 봤습니다만, 맥린이도 따라하는 자기만의 3벌식 키보드 만들기 같은 정보들이 있는지 묻습니다. 

- macOS 버전: 
아직 없어요 

- 구름 버전:  
아직 없어요

- 사용중인 한글/영문 배열: 
혼자 만들어서 쓰고 있어서 이름 없어요

- 문제가 발생하는 애플리케이션 이름과 버전: 
문제도 아직 없어요

- 문제가 있는 동작: 
하게된다면 하게 될 모든 것

- 기대하는 정상 동작: 
m1맥북에어의 키보드 배열 (거의 모든 키) 변경, 한글 자판 배열 (만들어서 쓰는 중인 3벌식으로) 변경, 

- 애플 기본 한글 입력기의 동작:

- 재현 방법: 
캡스록은 쉬프트로, G는 /로 이런 식으로 모든 키를 다 바꾸는 방법 (이건 검색해서 이런 저런 방법이 나오는데, 제가 원하는게 맞는지 알지를 못해서.  그냥 따라하게 강좌 링크 정도만 남겨주셔도 감사하겠니다.)
키보드 한글 배열을 수정하는 방법. (제 지금 한글배열이 아주 특이합니다)
초성ㅇ+초성ㄱ=초성ㅋ 종성ㅇ+종성ㄴ=종성ㄶ 이와 같이 3벌식 입력법을 수정하는 방법 (특이한 배열 위에서 한글 조합하기)

방법을 알려주시면 고맙겠습니다.  적으면서도 "이거 본 사람들이 귀찮아서 답 안 쓰겠다" 싶어요.
그냥 알려줄 분이 혹시나 있을까 했습니다.
<

**Comment by soomtong** [comment]
구름 입력기가 사용하는 libhangul 이 몇 종류 있어요.
하나는 기본 번들되고 있는 libhangul 이고 다른 하나는 세벌식 커뮤니티에서 지원하는 libhangul 자판이 있어요.
구름 입력기 contrib 이라는 정보로 찾아보시면 이 자판이 반영된 코드 저장소가 있습니다.
그 코드를 참고해 보시면 원하는 부분을 확인하실 수 있을 듯 해요.
말씀하신 조합법은 세모이 자판을 참고하시면 될 듯 해요.

**Comment by youknowone** [comment]
official libhangul의 최신버전에서는 xml 파일로 자판 설정하는걸 지원하니까 이걸 추가하면 임의의 사용자 자판을 지원할수 있을거 같긴 해요.

**Comment by borndust** [comment]
모자란 질문에 넘치는 답변 고맙습니다.  
덕분에 뭔가 또 시도하게 되네요. 
아마 시도 하자마자 부터 죄다 막혀서 하나도 못할 게 뻔하지만, 그래도 해보고 싶었습니다.

**Comment by borndust** [comment]
모자란 질문에 넘치는 답변 고맙습니다.
덕분에 뭔가 또 시도하게 되네요.
아마 시도 하자마자 부터 죄다 막혀서 하나도 못할 게 뻔하지만, 그래도 해보고 싶었습니다.

**Comment by borndust** [comment]
모자란 질문에 넘치는 답변 고맙습니다.
덕분에 뭔가 또 시도하게 되네요.
아마 시도 하자마자 부터 죄다 막혀서 하나도 못할 게 뻔하지만, 그래도 해보고 싶었습니다.
> 
> 
> 구름 입력기가 사용하는 libhangul 이 몇 종류 있어요.
> 하나는 기본 번들되고 있는 libhangul 이고 다른 하나는 세벌식 커뮤니티에서 지원하는 libhangul 자판이 있어요.
> 구름 입력기 contrib 이라는 정보로 찾아보시면 이 자판이 반영된 코드 저장소가 있습니다.
> https://gitlab.com/3beol/libhangul
> 그 코드를 참고해 보시면 원하는 부분을 확인하실 수 있을 듯 해요.
> 말씀하신 조합법은 세모이 자판을 참고하시면 될 듯 해요.

**Comment by borndust** [comment]
고맙습니다. 
"기능이 있다" 정도만 알아도 "되는데 내가 못한 거다" 라고 알고 시도라도 하게 되니 작은 힘이 됩니다.
> 
> 
> official libhangul의 최신버전에서는 xml 파일로 자판 설정하는걸 지원하니까 이걸 추가하면 임의의 사용자 자판을 지원할수 있을거 같긴 해요.

**Comment by youknowone** [comment]
혹시 오해하게 썼나 싶어서 정리 조금 더 할게요.

구름입력기를 새로 빌드하지 않고 할수 있냐? -> 현재로서 할수 없습니다.

구름입력기를 고쳐서 이런 기능을 추가할수 있냐?
- libhangul xml 설정을 지원하면 파일만 바꿔 넣으면 되는 사용자 자판 기능을 추가할 수 있습니다.
- soomtong님 말씀대로 그냥 코드를 고쳐서 추가할 수도 있습니다. (전통적 방법)

**Comment by borndust** [comment]
>     * 님 말씀대로 그냥 코드를 고쳐서

고맙습니다. 빌드 관련 글부터 보게 되네요.  고맙습니다.
