### ISSUE TITLE
m1은 언제쯤 지원하시는지 계획이 있으신가요?

### ISSUE THREAD

**Issue by mm11game** [gureum/gureum#770]
m1에서 사용하려고 하는데요. 

command키로는 전환이 잘되는데,
capslock키로는 전환이 잘 안됩니다. 

제발 m1도 지원해주세요 ㅠ

**Comment by kjoonlee** [comment]
#746 참고하시면 될 듯요.

**Comment by mm11game** [comment]
감사합니다

2021년 8월 5일 목요일, kjoonlee ***@***.***>님이 작성:

**Comment by soomtong** [comment]
애플 실리콘(M1 계열)을 지원하는 버전이 등록되었습니다.
https://github.com/gureum/gureum/releases/tag/1.12.1
확인 해주세요.
