### ISSUE TITLE
F3 단축키의 기능을 끄거나 다른키로 변경할 수 있게 해주세요.

### ISSUE THREAD

**Issue by 128beat** [gureum/gureum#777]
- macOS 버전: 11.6
- 구름 버전: 1.11.1
- 사용중인 한글/영문 배열: 두벌식/ABC

빅서환경에서 자잘하게 발생하던 한글입력과 관련된 문제들이 
구름입력기를 통해 대부분 해결되었습니다. 
개발해주신 분들께 깊히 감사드립니다.

구름입력기가 켜있으면 F3키가 구름입력기-환경설정 단축키로 강제됩니다.
글로벌 단축키로 등록되어 모든 어플리케이션에서 F3키를 사용할수 없습니다.

사실 입력기의 환경설정은 단축키가 필요한만큼 자주 쓰는 기능은 아니라고 생각됩니다.
다른키로 변경하거나 단축키를 없애 주시길 부탁드립니다.

**Comment by youknowone** [comment]
말씀하신 단축키는 구름 입력기의 단축키가 아니고, ABC 자판도 구름 입력기가 제공하는게 아닌 macOS가 제공하는 것입니다

**Comment by 128beat** [comment]
아. ABC자판은 글쓰는 양식에 사용중인 자판배열을 쓰도록 되어 있어서 그냥 언급한것 뿐입니다. 
F3키의 단축키는 구름입력기에서 강제하는 단축키가 맞습니다. 입력기로 구름입력기가 선택된 상태에서 F3키를 눌러보시면 알겁니다.

제가 주로 사용하는 어플중에 F3키를 사용하는 어플리케이션이 있는데 구름입력기를 켠상태에선 사용할수가 없거든요. 구름입력기를 끄면 문제 없습니다.

**Comment by soomtong** [comment]
나중에 이 이슈를 참고할 수 있게 '바람' 라벨을 달아 두었습니다.
