### ISSUE TITLE
dvorak 사용시 단축키 매핑 관련 제안

### ISSUE THREAD

**Issue by orchistro** [gureum/gureum#785]
- macOS 버전: 12.0.1
- 구름 버전: 사용하지 않고 있음 (단축키 매핑 관련 문제로 인해)
- 사용중인 한글/영문 배열: 두벌/dvorak
- 문제가 발생하는 애플리케이션 이름과 버전:
- 문제가 있는 동작:
- 기대하는 정상 동작:
- 애플 기본 한글 입력기의 동작:
- 재현 방법: 

버그 신고라기 보다는 dvorak 사용자의 입장에서 조금 더 편하게 쓸 수 있으면 해서 제안 드립니다.
단축키 매핑을 직전 영문 키보드 매핑에 따르도록 하면 좋겠습니다.
이해를 돕기 위해 부연설명 드리겠습니다:

예를 들어, cmd-c (copy to clipboard) 단축키를 사용하는 경우를 생각해 보겠습니다.
dvorak 자판으로 타이핑을 하고 있을 때에는 cmd키와 함께 아래 그림의 키 (querty키맵으로는 i, dvorak 키맵으로는 c) 를 누릅니다:
<img width="300" alt="Screen_Shot_2021-10-31_at_15_04_53" src="https://user-images.githubusercontent.com/1239809/139570360-e10773df-0ccd-4ee8-b93a-128b4717b8dd.png">

하지만 두벌 자판으로 타이핑을 하고 있을 대에는 cmd키와 함께 아래 그림의 키 (querty키맵으로는 c, dvorak 키맵으로는 j) 를 눌러야만 합니다:
<img width="302" alt="Screen_Shot_2021-10-31_at_15_07_06" src="https://user-images.githubusercontent.com/1239809/139570414-d8fdb9d1-907c-4d8c-ac5f-81929c516eb6.png">

즉, dvorak 사용자들은 단축키를 누를 때 단순히 muscle memory만으로 누르는 게 불가능하며, 현재 자판이 dvorak인지, 두벌인지를 확인해 가면서 눌러야만 하는 불편함이 있습니다.

이를 해결할 수 있으면 좋겠습니다.

해결 방안 한가지는 처음에 제안드렸듯이,
두벌자판으로 바꾸기 직전의 영문 자판을 확인하여 그 자판 배열에 맞춰서 단축키 입력을 받도록 하는 것은 어떨까요?
예를 들어, querty를 사용하다가 두벌로 전환하였을 경우, cmd-c (querty 기준 c) 를 누르면 복사,
dvorak을 사용하다가 두벌로 전환하였을 경우, cmd-i (querty 기준 i) 를 누르면 복사
이렇게 동작하도록 말입니다.

그리고, 방금 말씀드린 동작은 애플 기본 한글 입력기의 동작과는 다른 동작입니다.

감사합니다~

**Comment by yous** [comment]
안녕하세요, 다음과 같이 해보시기 바랍니다.

1. 기존 Dvorak 자판은 유지한 채
2. 구름 한국어 입력 소스 "두벌식" 추가
3. 메뉴 바에서 구름 아이콘을 클릭하여 "환경설정..." 버튼 클릭

![Screenshot 2021-10-31 15 41 06](https://user-images.githubusercontent.com/853977/139571560-fe6de9eb-4f22-444f-960e-cbf035eff515.png)

4. 위 이미지에서 "로마자 입력기 설정" 아래의 "키보드 레이아웃" 선택 항목을 "Dvorak"으로 변경

이렇게 하시면 항상 Dvorak 단축키로 사용하실 수 있을 것 같습니다.

**Comment by orchistro** [comment]
> 1. 위 이미지에서 "로마자 입력기 설정" 아래의 "키보드 레이아웃" 선택 항목을 "Dvorak"으로 변경

됩니다!!! 고맙습니다!!!
이슈는 close 하겠습니다.
