### ISSUE TITLE
Caps Lock (캡스락) 전환 옵션... 저만 안 뜨는 건가요..?

### ISSUE THREAD

**Issue by seungflash** [gureum/gureum#788]
- macOS 버전: 12.0.1(21A559)
- 구름 버전: 1.11.1
- 사용중인 한글/영문 배열: 두벌식/맥ABC
- 문제가 발생하는 애플리케이션 이름과 버전: 전체
- 문제가 있는 동작: '캡스락 전환 옵션이 아예 뜨지 않음'
- 기대하는 정상 동작: '순정처럼 캡스락으로 한/영전환'
- 애플 기본 한글 입력기의 동작:
- 재현 방법: 재설치를 해도 안 뜸

<img width="1092" alt="스크린샷 2021-11-29 오후 7 28 34" src="https://user-images.githubusercontent.com/95218653/143852789-59e8b714-fafd-420e-a250-59f98ff4dbd2.png">
<img width="667" alt="스크린샷 2021-11-29 오후 7 29 22" src="https://user-images.githubusercontent.com/95218653/143852814-c9199326-4e67-4db6-82a0-4320360da664.png">

현재 맥북프로 16인치 2021 (M1 Max) 사용중입니다
이 문제는 제가 인텔 맥북을 썼을때부터 있었는데요

다른 분들은 어떻게 뜨는지 정말 궁금할 정도로
제 맥에서는 'Caps Lock' 전환 옵션이 단 1도 뜨지 않습니다
(물론, 구름을 빼고 맥 순정 자판만 올렸을땐 당연히 뜹니다)

사실 인텔 맥 썼을땐 그냥 제 맥의 문제인가 싶었는데
새로 구매한 M1 max 맥북에서도 똑같네요...

권한 재설정, 재부팅 등등 할 수 있는건 모두 해봤습니다
혹시 해결법이 있을까요?

**Comment by yous** [comment]
안녕하세요, 애플 기본 두벌식 자판을 추가하면 Caps Lock 옵션을 보실 수 있습니다. 원하는 옵션으로 설정한 후 기본 두벌식을 제거하시면 됩니다. https://github.com/gureum/gureum/issues/778#issuecomment-930412813

**Comment by seungflash** [comment]
> 안녕하세요, 애플 기본 두벌식 자판을 추가하면 Caps Lock 옵션을 보실 수 있습니다. 원하는 옵션으로 설정한 후 기본 두벌식을 제거하시면 됩니다. [#778 (comment)](https://github.com/gureum/gureum/issues/778#issuecomment-930412813)

아... 저 질문글은 못 찾았는데, 옵션을 켜고 기본 두벌식 자판을 지워야 했군요;;
답변 감사합니다!

**Comment by youknowone** [comment]
이거 구름 환경설정에도 문구 추가를 해둬야 할거 같네요
