### ISSUE TITLE
iTerm2에서 shift+space로 변환시 space가 입력되는 현상

### ISSUE THREAD

**Issue by arecibo** [gureum/gureum#802]
- macOS 버전: 12.3.1
- 구름 버전: 1.12.0
- 사용중인 한글/영문 배열: ABC/Han 2Set
- 문제가 발생하는 애플리케이션 이름과 버전: iTerm2 3.4.15
- 문제가 있는 동작: shell에서 shift+space를 누르면 공백이 추가된 후에 한영전환이 됩니다.
- 기대하는 정상 동작: shell에서 shift+space를 누르면 즉시 한영전환이 됩니다.
- 애플 기본 한글 입력기의 동작: 제대로 작동합니다.
- 재현 방법:
1. 구름입력기 환경설정을 다음과 같이 합니다: 한글/로마자 바꾸기 단축키를 shift+space
1. 시스템 환경설정 -> 단축키 -> 입력소스 에서 'Select the previous input source'를 Ctrl+Shift+Space로 하고 체크하기. 'Select next source in input menu'는 체크하지 않기
1. iTerm을 실행하고 Zshell(5.8) 에서 shift+space를 눌러보기

**Comment by youknowone** [comment]
![image](https://user-images.githubusercontent.com/69878/167262686-883bfbed-53ed-4038-aa11-fd44318f2a96.png)

iTerm 설정에서 `Improved support for input method editors like AquaSKK` 를 켜면 됩니다

https://github.com/gnachman/iTerm2/pull/279
