### ISSUE TITLE
안마태 키보드가 왜 기본 아이콘인가요?

### ISSUE THREAD

**Issue by anaclumos** [gureum/gureum#824]
영문의 기본 레이아웃인 쿼티가 아무런 텍스트가 없는 주황 구름 아이콘이듯이, 표준으로 사용되며 가장 많은 사람들이 사용하는 두벌식이 하늘 구름 아이콘이 되어야 할 것 같은데, 오히려 두벌식에는 2라는 글자가 있고 안마태 키보드가 기본 하늘 구름 아이콘으로 나타나있길래 의문이 들어서 문의 남깁니다.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/31657298/168419829-199a4cb6-3760-4c08-bbcc-5f66cd58ecfc.png">

**Comment by youknowone** [comment]
전용 아이콘을 만들지 않았으므로 기본 아이콘이 뜹니다
