### ISSUE TITLE
오른쪽 키로 언어전환이 안되요

### ISSUE THREAD

**Issue by KKgabriel** [gureum/gureum#827]
- macOS 버전:  12.4
- 구름 버전:   1.12.2
- 사용중인 한글/영문 배열: 두벌식, 로마자
- 문제가 발생하는 애플리케이션 이름과 버전: 1.12.2 업데이트 하자마자 어디에서나 작동안됨
- 문제가 있는 동작: 구름입력기 환경설정에 있는 오른쪽 키로 언어전환 기능이 안됨 선택지에 있는 커맨드, 옵션, 컨트롤 키 모두 안되네요
- 기대하는 정상 동작: 구름입력기 환경설정에서 '설정하는 오른쪽 키로 언어전환'에서 설정된 키로 한영전환을 하고싶은데 설정해도 전환이 안됨
- 애플 기본 한글 입력기의 동작: ..?
- 재현 방법:  입력모니터링 쪽에 Gureum 등록 되어 있으나 작동안됩니다 그외로 구름입력기 환경설정에서 '입력 모니터링 설정하러 이동하기' 버튼 클릭하면 아무 반응이 없고 구름입력기 환경설정창이 잠깐 프리징 걸립니다 '다른 키보드 설정하러 이동하기' 버튼도 동일함 삭제하고 클린 재설치 해봤지만 동일합니다..!

**Comment by kty0113** [comment]
저도 동일한 증상이라서 
1.12.0 로 내려서 사용중입니다.

**Comment by rkdls** [comment]
저도 감사하게도 잘쓰고 있지만 동일한 증상이 발생하고 있습니다.

**Comment by yous** [comment]
1.12.1, 1.12.2 버전의 경우 App Sandbox와 관련한 권한 문제인 것 같습니다. #828 PR에서 수정될 것 같아 다음 버전에 적용될 것 같습니다.

**Comment by youknowone** [comment]
@tebica

**Comment by youknowone** [comment]
새 버전을 배포했습니다 https://github.com/gureum/gureum/releases/tag/1.13.0

**Comment by rkdls** [comment]
잘 적용 되네요 감사합니다!
