### ISSUE TITLE
최신 macOS 베타(10.13)에서 입력기를 추가하지 못하는 문제

### ISSUE THREAD

**Issue by skinmaker1345** [gureum/gureum#831]
- macOS 버전: 13.0 베타(22A5286j)
- 구름 버전: 1.12.2
- 사용중인 한글/영문 배열: 세벌식 / 쿼티
- 문제가 발생하는 애플리케이션 이름과 버전: 
- 문제가 있는 동작: 입력 소스에 추가할 수 없음
- 기대하는 정상 동작: 입력 소스에 정상적으로 구름입력기가 추가됨
- 애플 기본 한글 입력기의 동작:
- 재현 방법: 
![](https://cdn.discordapp.com/attachments/898886636434260008/990266512633892915/Jun-25-2022_23-42-35.gif)

- macOS 베타의 오류인지 구름 입력기의 오류인지 모르겠습니다.
베타1부터 증상이 있었으며, 베타 2에서도 동일 증상이 발생합니다.
구름 입력기와 무관한 맥오에스 베타의 문제이고, 구름 입력기에 대한 조치가 필요 없다면 이슈 닫도록 하겠습니다. :)

**Comment by skinmaker1345** [comment]
베타 3에서 해결되었습니다 :)

**Comment by youknowone** [comment]
확인 감사합니다!
