### ISSUE TITLE
텍스트 편집기, 애플 기본 노트등에서 한영 변환이 되지 않아요

### ISSUE THREAD

**Issue by daehyeon1999** [gureum/gureum#835]
- macOS 버전: 12.4
- 구름 버전: 1.13
- 사용중인 한글/영문 배열:
- 문제가 발생하는 애플리케이션 이름과 버전: 텍스트 편집기 (1.17), 메모 (4.9)
- 문제가 있는 동작: 텍스트 입력을 하려고 하면 무조건 영어로만 써집니다. 한영 버튼을 눌러도 한영 변환이 되지 않아요.
- 기대하는 정상 동작: 한영 변환
- 애플 기본 한글 입력기의 동작: 한영 변환
- 재현 방법: 
    - 텍스트 편집기, 메모 앱을 켜서 입력을 해본다
    -  한영 변환을 해본다.
    - 한글이 입력되는지 확인해본다.

**Comment by soomtong** [comment]
입력기 아이콘을 눌러서 나오는 
구름 입력기에 관하여 등의 메뉴가 잘 나오고 있는지 확인 가능하실까요?

**Comment by daehyeon1999** [comment]
아뇨 구름 입력기 자체가 선택이 안됩니다.

**Comment by soomtong** [comment]
그러면 다른 원인으로 입력기가 제대로 로딩(사용가능하도록)이 되지 않은 상황 같습니다.
구름 입력기를 재설치 하여 우선 정상 로딩되도록 해주시면 될 것 같아요.

**Comment by daehyeon1999** [comment]
알겠습니다~
