### ISSUE TITLE
“세벌식 정석 강요” 옵션이 동작하지 않음

### ISSUE THREAD

**Issue by saturnsky** [gureum/gureum#853]
- macOS 버전: 13.0.1
- 구름 버전: 1.13.0
- 사용중인 한글/영문 배열: 세벌식 최종
- 문제가 발생하는 애플리케이션 이름과 버전: 모든 어플리케이션
- 문제가 있는 동작: 이중 모음용 ㅗ나 ㅜ가 이중모음을 완성하지 못하는 경우에도 모아쓰기 처리가 종료됨 / 일반 모음 ㅗ(v)나 ㅜ(b)도 이중모음을 완성함
- 기대하는 정상 동작: 이중 모음용 ㅗ나 ㅜ는 이중모음을 완성하는 경우에만 모아쓰기 처리를 종료해야 함 / 일반 모음 ㅗ(v)나 ㅜ(b)는 이중모음을 완성해서는 안 됨
- 애플 기본 한글 입력기의 동작: 모아쓰기 미지원
- 재현 방법:
  1. 세벌식 최종으로 자판을 설정
  2. 쿼티 키보드 기준으로 j9sc 순으로 키를 입력 -> 운ㅔ 이 입력됨 (ㅜ는 이중모음용 모음이기 때문에, ㅔ는 ㅜ와 결합하여 웬이 입력되어야 함)
  3. 쿼티 키보드 기준으로 jbcs 순으로 입력 -> 웬 이 입력됨 (ㅜ는 단일모음용 모음이기 때문에, ㅜ는 ㅔ와 결합할 수 없어 우ㅔᆫ 이 입력되어야 함)

**Comment by youknowone** [comment]
아마 겹받침에만 동작하고 모음에는 동작 안하는 상황일까 싶네요. libhangul의 기능을 쓰고 있는데, libhangul에서 조합용 ㅗ와 일반 ㅗ를 구분하고 있는지 잘 모르겠어요

**Comment by karipe** [comment]
확인해 보니 종성에서는 동작하고 중성에서 동작하지 않는 상황이 맞고, libhangul에서 조합용 ㅗ와 일반 ㅗ를 구분하지 못하는 것이 원인이 맞습니다.
https://github.com/libhangul/libhangul/blob/a3d8eb6167cb92fe9d192402bb9b8dbe20ff7e26/doc/gen_hangulkeyboards.py#L387-L401

**Comment by karipe** [comment]
9kc(궤가 입력되어야 하는데 구ㅔ가 입력됨) 같은 문제들을 추가로 확인했는데, libhangul의 중성 조합 처리에 세벌식이랑 맞지 않은 부분이 많은 것 같네요.

**Comment by youknowone** [comment]
#859 를 머지하였으므로 닫습니다
