### ISSUE TITLE
Arc 브라우져에서 한글 입력중 글자가 사라지거나 잘못 입력됩니다.

### ISSUE THREAD

**Issue by jeyraof** [gureum/gureum#860]
- macOS 버전: 13.0.1 (22A400)
- 구름 버전: 1.13.0 (1.13.0)
- 사용중인 한글/영문 배열: Roman / Han 2set
- 문제가 발생하는 애플리케이션 이름과 버전: Arc 0.81.2 (36600)
- 문제가 있는 동작: 한글입력에서 글자가 사라집니다.
- 기대하는 정상 동작: 한글의 정상적인 입력
- 애플 기본 한글 입력기의 동작: 정상적인 입력
- 재현 방법: 구름입력기를 쓰고 Arc 브라우져에서 Cmd+L 을 통해 검색 프롬프트를 띄우고, 그곳에서 한글을 입력하면 간헐적으로 글자가 사라집니다.

https://user-images.githubusercontent.com/2032880/211163426-072f06b4-1539-4dfd-808c-e5a43e99ac5f.mov

**Comment by saturnsky** [comment]
#840 과 같은 문제인 것 같습니다.

**Comment by stars-flow** [comment]
저도 같은 문제가 있어서 애플 기본 한글 입력기로 바꿨는데도 동일한 현상 발생합니다. 
저는 Arc 브라우저의 문제라 판단해 그쪽에 bug report 넣었습니다.

**Comment by jeyraof** [comment]
감사합니다!

**Comment by jeyraof** [comment]
@saturnsky @stars-flow cc. @youknowone 
이번 [패치](https://arc.net/e/D25B2EEA-7506-4850-A169-3B2A00802889)로 해소가 된 것 같네요 ㅎㅎ. 클로징 하겠습니다.


<img width="573" alt="image" src="https://github.com/gureum/gureum/assets/2032880/e112b653-8f4d-4030-b0f0-573b09b95465">
