### ISSUE TITLE
[기능 추가 부탁] "한/영 전환 아이콘 표시" 에 더해서 ...

### ISSUE THREAD

**Issue by lum7671** [gureum/gureum#901]
- 구름 버전: 1.13.2

오늘 보니 입력 커서 쪽에서 "한/영 전환 아이콘 표시" 가 되네요.
Shift-Space 에서는 안되고, 오른쪽 Opt 키로 한/영 전환 할 때 아래와 같이 표시가 되는군요.

하나 더 가능하면 부탁드리고 싶은 것은 현재 상태 (한 or 영) 을
커서에 색을 입힌다던지, 아님 아래에 같이 입력기 전환이 표시되는 앱 같은 경우
커서 위에 작은 점으로 색을 표시해서 현재 입력 언어를 표시하는데요.

이것도 되었으면 좋겠습니다. 

현재 입력 언어 를 색으로 표시하는 기능요.

부탁드립니다.

https://github.com/user-attachments/assets/22b2af79-27ba-49ef-9c45-14e7f857e0ba

**Comment by youknowone** [comment]
해당 기능은 구름이 구현한 기능이 아니라 운영체제에서 추가한 기능입니다. 입력기에서는 이런 기능을 구현할 방법이 제공되지 않아 말씀하신 기능은 추가할 수 없습니다

**Comment by lum7671** [comment]
> 해당 기능은 구름이 구현한 기능이 아니라 운영체제에서 추가한 기능입니다.

그렇군요.

참고로, 제가 사용하는 프로그램 링크입니다.
[[Input Source Pro - Switch and track your input sources with ease](https://inputsource.pro/)](https://inputsource.pro/)
