### ISSUE TITLE
ㅇㅂ(v) 나 ㅇㅍ(f)  같은 자음도 지원하나요?

### ISSUE THREAD

**Issue by Sir0xb** [gureum/gureum#903]
ㅇㅂ   /  ㅇㅍ
이런 자음도 지원 가능한지요.
영어 발음 표기에 상용하기에 참 좋은 자음인데
조상님들이 다 만들어 준걸 지금은 입력하기가 참 힘드네요.
지원했으면 좋겠습니다.

**Comment by youknowone** [comment]
옛한글 (두벌식 옛글, 세벌식 옛글) 자판을 써보세요. 조합 방법은 해당 자판 이름으로 검색하시면 자료가 조금 나옵니다.
예: https://ko.wikipedia.org/wiki/%EB%91%90%EB%B2%8C%EC%8B%9D_%EC%98%9B%EA%B8%80
