### ISSUE TITLE
삭제후에도 구름입력기 키보드 레이아웃이 있던 곳이 비어있습니다..

### ISSUE THREAD

**Issue by doxxx93** [gureum/gureum#904]
- macOS 버전:  15.0.1 (24A348)
- 구름 버전:  삭제
- 사용중인 한글/영문 배열: 
- 문제가 발생하는 애플리케이션 이름과 버전:
- 문제가 있는 동작: 바이너리, 설정 모두 삭제후에도 이와 키보드 레이아웃이 원래 상태로 돌아가지 않습니다.

<img width="827" alt="image" src="https://github.com/user-attachments/assets/6f254bb3-d906-491d-9529-ff3e6e234b0a">
<img width="827" alt="image" src="https://github.com/user-attachments/assets/72748966-6799-4e0a-8663-6fa82ff532cd">
<img width="827" alt="image" src="https://github.com/user-attachments/assets/32eadd2d-e915-4469-b675-202224c700e1">

- 기대하는 정상 동작: 
- 애플 기본 한글 입력기의 동작: 정상 동작합니다.
- 재현 방법: 

구름 입력기가 제대로 종료되지 않은 상태에서 gureum app을 삭제했던 것 같아서

재 설치후 제대로 종료후 삭제했습니다. Library에서 바이너리와 설정까지 모두 삭제했습니다.

**Comment by youknowone** [comment]
macOS 에서 결정하는 부분이고 구름입력기가 관여할수 있는 부분이 아닙니다.
