### ISSUE TITLE
vi모드 esc 키 외에 Ctrl + [ 추가 요청

### ISSUE THREAD

**Issue by eastnwise** [gureum/gureum#93]
vi모드 체크 시, esc키를 누르면, 한글자판에서 로마자판으로 전환이 되는 데, esc키 외에 Ctrl + [키도 같은 기능이 되도록 적용해주셨으면 합니다. 실제 vim에서 Ctrl + [ 조합은 esc와 동일한 기능을 하는 키 바인딩입니다.

**Comment by soomtong** [comment]
https://github.com/gureum/gureum/pull/448

**Comment by youknowone** [comment]
#466

**Comment by youknowone** [comment]
이 기능을 추가한 1.10.0 베타2를 릴리즈했습니다. 다음 정식 버전에 포함됩니다. https://github.com/gureum/gureum/releases/tag/GureumKIM-1.10.0-pre2
