### ISSUE TITLE
iTerm 2에서 한영전환시 스페이스바 입력

### ISSUE THREAD

**Issue by kndol** [gureum/gureum#96]
Shift-Space로 한영 전환하는데 iTerm 2에서 문제가 있네요.
줄의 처음이나 한글 뒤에서 Shift-Space 하면 정상적으로 한영 전환이 됩니다.
영문을 쓴 뒤 Shift-Space 누르면 스페이스바가 입력되며 한영 전환이 됩니다.
입력기 버전 1.8.0

**Comment by youknowone** [comment]
이 문제는 iTerm의 버그일 가능성이 높아 보입니다. 현재 버전에서도 해결되지 않았습니다.
하지만 capslock 으로 자판 전환 기능이 추가되어 다른 단축키를 쓸 경우 다소 문제를 덜 겪으리라 생각됩니다.

**Comment by ujuc** [comment]
1.10.1 에서 해당 버그가 발견됩니다.
iTerm2 뿐만아니라 jetbrains IDEA에서 사용하는 터미널에서도 발견됩니다.

Shift+Space 으로 사용하면 무조건 발현됩니다.
일반모드 입력시 Shift+Space는 빈칸이 입력되기에 발생하는 문제로 보입니다.

**Comment by junhochoi** [comment]
저도 1.10.1 사용중인데 동일 문제를 겪고 있습니다. (iterm2 + shift-space로 한영전환) xcode 에서는 발생하지 않네요.

**Comment by junhochoi** [comment]
꼼수를 찾았는데,

iTerm2 Preference -> Keys -> Key Bindings -> + 
Keyboard Shortcut 에 Shift-Space
Action 에 "Do Not Remap Modifiers"나 "Remap Modifiers in iTerm2 Only"로 하니
빈칸 입력이 없어지네요.

**Comment by youknowone** [comment]
https://github.com/gureum/gureum/issues/802#issuecomment-1120234781
